- CONTRIBUTING.md
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Initial CONTRIBUTING.md file for the containers projects that want to use it.  I'm still a little hazy on how we can grab this from the other projects, but need to drop a file here so I can play with that.  This is a first cut.
@vrothberg @rhatdan PTAL
> Add initial contributing for the Container's projects

- .github/CONTRIBUTING.md
I looked more closely and realized there were two CONTRIBUTING.md files
already in the repo, so this commit moves the detailed one into the
right path.
Closes #4.
Signed-off-by: Justin W. Flory <git@jwf.io>
> Move contributing guidelines to correct path (closes #4)

- pkg/config/config.go
Change default value of pidslimit and hooksdir.
Add hooksdir to default config.
> change default value of pidslimit and hooksdir

- pkg/config/config.go
- pkg/config/default.go
- pkg/config/merge.go
- pkg/config/merge_test.go
We want to hide Optional Bools from the default configuration.  Callers should only have to deal with boolean
fields and not deal with optionals.
Add accessor functions for all optional bools, easier.
> Change optional bools to be private options

- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
We also want to be able to default namespaces to host, so that HPC
machines can default to not using most of the namespaces by default.
> Add missing fields to be used with podman

- pkg/config/config.go
- pkg/config/config_test.go
Also re-add DefaultMountsFile since we need a holding place to be
used in libpod.
> Fix handling of SELinux labeling

- pkg/config/config.go
- pkg/config/config_test.go
Fix spelling mistakes found using codespell.
> Run code through codespell

- pkg/unshare/getenv_linux_cgo.go
- pkg/unshare/getenv_linux_nocgo.go
- pkg/unshare/unshare_linux.go
if CGO is enabled, make sure to use C.getenv instead of os.Getenv to
read environment variables.  It is required since rootless libpod
joins the user namespace through Cgo.
The variables set via C.setenv are not visible through os.Getenv, as
the latter uses sync.Once to read the variables once.
Requires: https://github.com/containers/libpod/pull/4911
> unshare: add getenv from cgo

- pkg/config/default.go
The default alternative path for seccomp.json should be /etc/containers/seccomp.json
The DefaultNetwork in network config should be bridge
> Fix a couple of defaults

- pkg/config/config.go
- pkg/config/config_test.go
This is causing issues in rootless and remote mode.  We should not be creating
directories on the fly.
Also stop exporting functions that are not used by Buildah and Podman.
> Stop validating networkconfig by default

- pkg/config/default_linux.go
We should vendor this into buildah afterwards because its latest release does not build on 32bit machines.
> Fix 32bit build by using unix.CGROUP2_SUPER_MAGIC

- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
In root running containers we want to approach the MAX  Number of processes and
open files, so that services running Podman will work when they have lots of open
files or processes.  In rootless containers this number can not be changed.  This
patch will only increase the numbers if the process is allowed.
Docker set the limit to 2**20 (1048576), it looks like this was the max for RHEL5 OS.
So we fall back to attempt to set this limit if the MAC_PROC limit is not allowed.
> Setup default ulimits to nproc & nofile of current process

- pkg/config/config.go
- pkg/config/config_test.go
This function should be called to return a default config to be used
by callers.
> Add Default function to read containers config

- pkg/config/default.go
> Use slirp4netns for default network when in rootless mode

- pkg/config/default.go
it is needed by Buildah to set file capabilities.
More details here: https://github.com/containers/buildah/issues/2176
> config: add CAP_SETFCAP to the default capabilities

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Allow users to modify the default ammount of time to wait to send SIGKILL
after you tell a container to stop with a SIGINT.
> Add StopTimeout for podman

- pkg/capabilities/capabilities.go
These labels allows users to specify the list of capabilities required
to run their container image.
Setting a image/container label "io.containers.capabilities=setuid,setgid"
will tell container engines that the contained image should work fine withi
just these two capabilties, instead of running with the default capabilities,
Defined as a list, since this has not been standardized yet, we want to make
this a standard, and the standard label might be different then the label we
choose, so eventually we might need to add a standard label.
> list of label specification for required capabilities 

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
feature required from https://github.com/containers/libpod/issues/4535#issuecomment-592062482
pull_policy is the same as podman run --pull option to determine whether to pull a new image when running a container.
Accepted "always", "missing", and "never". Default value is "missing".
> Add pull_policy to LibpodConfig

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/libpodConfig.go
During the transition period of replacing libpod.conf with containers.conf, pkg/config should also read the libpod.conf if it exists.
This patch reads the libpod.conf in NewConfig() and converts the configurations to ContainersConfig Struct.
> Support and prefer libpod.conf if exists

- pkg/config/config.go
Export CheckCgroupsAndAdjustConfig() as global function and remove it from NewConfig(). So we can handle it in libpod and avoid Buildah to display cgroup warning message when reading containers.conf.
> remove CgroupsAndAdjust from NewConfig

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_override.conf
In NewConfig(), settings in the file whose name we're passed should
matter more than the hardwired default files, or the file named in the
CONTAINERS_CONF environment variable.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>
> NewConfig(): passed-in configuration file should matter most

- pkg/config/libpodConfig.go
Currently podman ships with libpod.conf,  We need to remove the noice
for these warnings from buildah for the time being.  We can fix this
once podman is shipping without libpod.conf.
> Drop deprecated warnings to debug

- pkg/config/config.go
- pkg/config/default.go
Callers should use containers/storage directly.
Also remove MergeDBConfig, this is no longer used by any callers.
> Drop StorageConfig from containers config structures

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/libpodConfig.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
containers/common pkg/config is for more engines then just libpod.
We want to use the 'libpod' section to configure parts of buildah.  Renaming this
section to engine, makes it more obvious to users that these fields can effect other
container engines.
Certain fields are still libpod specific, so we do not change those fields.
> Change references to libpod to engine 

- pkg/config/config.go
when the env variable is set, use its value for locating the user
configuration file.
> config: honor XDG_CONFIG_HOME

- pkg/config/config.go
- pkg/config/default.go
- pkg/config/libpodConfig.go
Signatures are an engine struct rather then something
per/container.  Moving to proper location.
> Move SignaturePolicyPath to Engine instead of Containers

- pkg/config/config.go
When using podman by putting the prebuild binarys into the users homedirectory, paths in the config starting with "\~" are not resolved as this is normally done by the shell.
Resolving "\~" to HomeDir enables the user (or a config provider) to publish a config which doesn't require adaption for each user (e.G. by changing /home/<username>/usr/bin/cni as this now becomes ~/usr/bin/cni).
This commit adds a new func resolveHomeDir(string) (string, error) which resolves a given path if it contains a reference to homedir or returns the path unchanged when not.
It throws an error when it's unable to get the users HomeDir.
Signed-off-by: Raphael Höser <raphael@hoeser.info>
I'm aware that this is a fairly uncommon usecase, but would make it easier to provide rootless install guides for podman and …
> isDirectory resolve ~ to User HomeDir

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
The `pause:3.1` has wrong configs for non-amd64 images as they all claim
to be for amd64.  The issue has now been fixed in the latest
`pause:3.2`.
[1] https://github.com/kubernetes/kubernetes/issues/87325
> use `pause:3.2` image for infra containers

- pkg/config/default.go
- pkg/config/nosystemd.go
- pkg/config/systemd.go
For packages that don't ship with systemd, this changes the default for those distros.
> Only default to systemd if built with the systemd buildtag

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
We need to identify the list of containers that support KVM separation, these
containers can run with a different SELinux label, and we might be able to
make different decisions in the container engines about how to launch these
containers.
> Add RuntimeSupportsKVM to config.Engine

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
We need to be able to disable cgroups when running container engines inside of containers.
> Add support for cgroups configuration

- pkg/config/libpodConfig.go
Previous versions of podman ignored the EventsLogger setting
in libpod.conf and defaulted to "file".  Containers.conf
should follow this for backwards compatibility.
> Hard code libpod.conf EventsLogger to File

- pkg/config/default.go
by default do not create a user namespace.  A user namespace also
requires mappings to be specified and that is not possible with a
static setting.  We cannot default to "auto" as it requires additional
configuration for the root user.
> config: change default for userns to host

- pkg/config/default.go
cgroupns="private" should be used only on cgroup v2.
On cgroup v1 it would be a breaking change, and also we'd need to
check whether the kernel supports cgroup namespaces.
> config: default to cgroupns="host" on cgroup v1

- pkg/capabilities/capabilities.go
- pkg/config/config.go
- pkg/config/config_test.go
We need to normalize the capadd and capdrop functions, and
we need to return errors if the caller gives us bad input.
> Fix config.Capabilities function call

- pkg/config/default.go
Currently if a rootless user runs podman in his homedir, and does
not have /etc/containers/policy.json on the system and does not
have ~/config/policy.json in his homedir, the command fails with
an error.
$ podman pull fedora
Error: error pulling image "fedora": unable to pull fedora: open /etc/containers/policy.json: no such file or directory
If the user has no root rights on the system, he can not create the file.
However the system would work fine if he created the file in his homedir.
With this change, we will force the default to be the file in his homedir if
BOTH files do not exist.  Now the error message for a rootless container would
be.
$ podman pull fedora
Error: unable to pull fedora: open /home/dwalsh/.config/containers/policy.json: no such file or directory
And the user has …
> Specify default paths to policy.json file

- pkg/auth/auth.go
- pkg/auth/cli.go
auth pkg supports login empty argument
libpod PR applies this PR https://github.com/containers/libpod/pull/6078
> auth pkg supports login empty argument

- pkg/auth/auth.go
- pkg/auth/cli.go
This moves more of the burden from callers, by directly implementing `AuthFile` and `CertDir`, defining a CLI option for `GetLoginSet`, documenting the expectations more clearly.
It also makes some functions private, it’s unclear if there are any other callers. (It also seems quite tempting to make most of the options private as well.)
See the individual commit messages for details.
Cc: @QiWang19
> Simplify option handling

- pkg/config/default.go
Pids-limit is not supported on rootless cgroup V1 systems.
> Don't set pids limit on rootless cgroupv1 systems

- pkg/config/config.go
The rootless config path was wrong when running with XDG_CONFIG_HOME
set.
Reported-in: github.com/containers/libpod/issues/6163
> pkg/config: set correct path in XDG_CONFIG_HOME

- pkg/config/config.go
- pkg/config/libpodConfig.go
If the user has a libpod.conf file with an option of "", then
we will ignore it and use the value from containers.conf.
Also the Set variables are only to be set, if a user specified an
override command, not if they were set in the libpod.conf file.
> Ignore empty strings from libpod.conf

- pkg/config/config.go
Even though these are not read from the config file, they are
still required as fields to pass data in libpod.
> Revert removal of Set flags

- pkg/sysinfo/sysinfo_linux.go
In case we failed to find out what version of cgroup we have,
it makes little sense to return that pids cgroup controller
is available, and yet the current code does it.
Fix this.
For some reason this code chose not to use information already fetched,
and call cgroups.FindCgroupMountpoint() instead. This is not a cheap
call, as it has to parse the whole nine yards of /proc/self/mountinfo,
and the info it tries to get (whether the pids controller is present)
is already available from cgMounts map.
This also prepares the code for the upcoming changes in runc (https://github.com/opencontainers/runc/pull/2411).
> fixes for pkg/sysinfo/checkCgroupPids

- pkg/config/config.go
- pkg/config/libpodConfig.go
Also add new function to allow container engines to tell users
where to edit containers.conf file.
> Add full path for error messages on containers.conf

- pkg/config/config.go
* as workaround user can use --identity option when given commands
requiring a SSH key
> V2 Store identity associated with remote URL

- pkg/config/containers.conf
Copied @parmentelat patch from  https://github.com/containers/libpod/pull/6566
> replace error-prone non-ASCII quotes in template config

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/config/config_test.go
- pkg/version/version.go
The default AppArmor profile is now prefixed with `container-default-$VERSION`, whereas the version is now part of a new `version` package.
Fixes https://github.com/containers/libpod/issues/6724
> Fix AppArmor profile prefix and name

- tools/rebuild_quay_ctr_images.sh
We recently discovered that the build triggers that are employed on
quay.io for the Buildah, Podman, and Skopeo container images do not
refresh the images as frequently as we thought.  Due to Docker using
the `--no-cache` flag under the covers at quay to do the builds, our
images were always using the pre-existing cache unless the `FROM` target
or the Dockerfile changed.  This rarely happened and it would take
weeks or more before the stable version would bump up to the latest
version available.  Ditto the upstream and testing variants.
I've created a script that can be run `by-hand` or via cron to update the
various images.  The script takes the project name and the creds for
an administrator on our repos on quay.io.  If those values are not supplied
the script will ask for them and the …
> Add script to rebuild images on quay.io

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/config/config_test.go
- version/version.go
The default AppArmor profile is now prefixed with
`container-default-$VERSION`, whereas the version is now part of a new
`version` package.
Signed-off-by: Sascha Grunert <sgrunert@suse.com>
Backport-of: commit 12b04a21d8ce7c76ad592299f1a9dd27ff96a747
> [0.14] Change AppArmor profile prefix and fix name-check

- pkg/config/config.go
We had a race condition where the sync.Once was called, and initializing
the default Config, but another thread hit it simultaniously and got the
nil value.
This patch will always return a correct value.
> Remove race condition on sync.Once

- pkg/config/config.go
We had a race condition where the sync.Once was called, and initializing
the default Config, but another thread hit it simultaniously and got the
nil value.
This patch will always return a correct value.
Backpord-of: commit 2ba9aff8fc5aa1edb9b2c0d111eb12e93ed73070
> [0.14] Remove race condition on sync.Once

- pkg/config/containers.conf
stop_timeout has to be defined in the engine section not
the engine.runtimes section.
> Fix location of stop_timeout in default containers.conf

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_default.conf
Add env for setting variables for engine to use.
close #31 
> Add env to [engines] for engine to use

- pkg/config/config.go
- pkg/config/config_test.go
Remove the often-unused result value from readConfig().
> readConfig(): don't return a pointer that's often ignored

- pkg/config/containers.conf
stop_timeout has to be defined in the engine section not
the engine.runtimes section.
Cherry-pick: commit b1dc0118e22012a67bb0bb93f099008b030a6603
> [0.14] Fix location of stop_timeout in default containers.conf

- tools/rebuild_quay_ctr_images.sh
While trying to run down an issue with cron, I releasized that the
only differences between the steps for the stable, testing and upstream
was the name of the repo.  So I put the builds of those three
flavors under a for loop and shrunk the script down quite a bit.
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
> Use a loop to go through repos in quay script

- pkg/config/default.go
Only return the Pids Limit for container engines running as root or
with cgroupv2 and Systemd as a cgroup manager.
Trying to do this will rootless containers on cgroup V1 is not allowed.
> PidsLimit should return 0 if rootless and cgroupfs manager

- pkg/config/config.go
- pkg/config/config_test.go
Add Reload() to reload configurations from containers.conf files.
> Add config reload

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
Allow users to setup N destinations for connecting to podman services.
> Add support for multiple service destinations

- pkg/config/config.go
- pkg/config/default.go
I am experimenting with supporting CNI in rootless Podman.  There is
no harm in preparing common to support such case and allow a custom
per-user configuration.
> rootless: permit custom configuration for cni

- go.mod
- pkg/image/pull.go
Add retry functions to retry on some commands and can be shared by Skopeo, Podman.
> Add retry helper functions

- pkg/config/systemd.go
The current logic is that, if Podman was built with the systemd build flag, we will always select systemd cgroups by default. Then, if we detect no systemd dbus session, we will swap to cgroupfs. Problem: there are cases where a systemd dbus session is available, but systemd cgroups don't work - most notably, rootless mode on cgroups v1 systems. Special-case this so that we will not try to force systemd mode and break rootless containers.
Fixes https://github.com/containers/podman/issues/6982
> Ensure that rootless cgroupsv1 will select cgroupfs

- pkg/config/systemd.go
- version/version.go
The current logic is that, if Podman was built with the systemd
build flag, we will always select systemd cgroups by default.
Then, if we detect no systemd dbus session, we will swap to
cgroupfs. Problem: there are cases where a systemd dbus session
is available, but systemd cgroups don't work - most notably,
rootless mode on cgroups v1 systems. Special-case this so that we
will not try to force systemd mode and break rootless containers.
Fixes https://github.com/containers/podman/issues/6982
Cherry-picked commit a61c5e2c9bb3b6a7a0764d4aebcc269145136b1c.
Signed-off-by: Matthew Heon <matthew.heon@pm.me>
> [0.14] Ensure that rootless cgroupsv1 will select cgroupfs

- pkg/retry/retry.go
Move the retry helper functions to pkg/retry.
> Move retry code to pkg/retry

- pkg/config/libpodConfig.go
"Found deprecated file $HOME/.config/containers/containers.conf,
please remove." was pointing to the wrong file. Should be libpod.conf.
Also the Warning about EventsLogger had the format string args mixed
up.
Additionally raise the log level of these messages to WARN to have them
displayed more prominently.
> Fix deprecation warnings about libpod.conf and raise log level

- docs/containers.conf.5.md
- pkg/config/containers.conf
hooks_dir_path was in wrong location, should be under Enigne section
network_cmd_path was not documented.
> Fix documenation

- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
Move hooks_dir in test files to [engine] table.
> Move testdata hooks_dir to [engine]

- pkg/config/default.go
Use the XDG_CONFIG_HOME environment variable, if it is defined, to locate policy.json and the cni plugins directory in rootless mode.  This is the standard way to locate user-specific configuration files.
XDG_CONFIG_HOME is already respected in rootless mode for configuration files such as containers.conf, storage.conf, and registry.conf but here `~/.config` was hardcoded.
> Respect XDG_CONFIG_HOME for policy.json and cni

- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
We need access to this function in Podman to translate
user entry into standardized format.
> Export NormalizeCapabilities function

- pkg/apparmor/apparmor_linux.go
The `execAAParser()` function also takes `stderr` into account when
parsing the output. This function is right now only called by the
`getAAParserVersion()` function. Depending on the system configuration,
it might be possible that `apparmor_parser` prints a warning, for
example if `/etc/apparmor/parser.conf` does not exist on the system. To
thake this input not into account for the version parsing, we now just
use `stdout` as the returned result.
> Omit apparmor_parser warnings when parsing the version

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
Mostly all AppArmor errors are now wrapped to provide additional context
to the user what actually went wrong. We now only use the spelling
`AppArmor` rather than `apparmor` to give the errors a uniform look.
> Wrap AppArmor errors to provide more debug information

- pkg/config/libpodConfig.go
We are throwing warning about libpod.conf when no files are
found.
> Do not mention libpod.conf if no files found

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
Add an option to control the default behavior of `podman save` or other
container engines.  If set to "true", the engine will create a
multi-image (docker) archive.  By default, Podman will interpret
additional arguments as tags that'll be stored in the archive's
manifest.  Docker interprets additional arguments as images to allow for
creating multi-image archives.  This option allows users to chose how
they wish the default behavior to look like, so we don't break
compatibility with existing Podman workloads while being compatible
with Docker.
> multi_image_archive: add option for `podman save`

- docs/containers.conf.5.md
- pkg/config/default.go
Currently it is difficult to modify the path to the storage.conf
file for setting up testing. It is hard coded to use /etc/containers/storage.conf.
Adding this envionment variable, will allow us to write tests on storage.conf
that do not override the system defaults.
> Add CONTAINERS_STORAGE_CONF Environment hanlding for testing

- docs/containers.conf.5.md
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
We want to make sure that the TERM envionment variable is always
set.
> Add TERM=xterm to default setting for env

- .travis.yml
- go.mod
- vendor/modules.txt
Golang 1.12 is already EOL so we should stick to the latest release.
> Bump golang to 1.15

- pkg/config/containers.conf
Uncommenting the nofile example will result in a syntax error as there are extra
quote (") characters. Remove them.
Fixes: bd0a08c617cc ("Add new fields to containers.conf")
Signed-off-by: Patrick Talbert <ptalbert@redhat.com>
> containers.conf: Fix ulimits nofile example syntax

- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_linux.go
- pkg/config/config_windows.go
getCustomConfigFile for windows and darwin
podman remote clients that run on windows and darwin cannot use the isRootless to determine the configuration file locations.  here we do by OS and also honor the environment variable.
Signed-off-by: Brent Baude <bbaude@redhat.com>
>  getCustomConfigFile for windows and darwin

- pkg/config/default_linux.go
The nested elseif `else {if cond {}}` can be replaced with `else if cond {}`.
> Fix nested elseif

- .gitignore
- .golangci.yml
- Makefile
This also updates the target directory of the linter binary, which is
now inside the repository instead of `$GOBIN`.
> Update golangci-lint and add config

- pkg/config/config.go
- pkg/config/config_local.go
- pkg/config/libpodConfig.go
- pkg/config/util_supported.go
- pkg/sysinfo/sysinfo_linux.go
We now use wrapped errors instead of indirectly wrapping them by
`fmt.Errorf`. The error messages have also been cleaned-up to reduce
duplicate words like `failed`.
> Change fmt.Errorf calls to be replaced by errors package

- pkg/config/config_windows.go
customConfigFile() has to return the full path to the file
LOCALAPPDATA only returns a directory.
I also recommend using APPDATA instead of LOCALAPPDATA.
If a domain user would logon to a new computer they would
automatically have their containers.conf from the last
login at a different pc. No manual copy is needed since
windows syncs the APPDATA dir by default in a domain
environment at login.
So the config file path on windows would be:
`C:\Users\<username>\AppData\Roaming\containers\containers.conf`
> fix windows containers.conf path

- .golangci.yml
- pkg/seccomp/conversion.go
- pkg/seccomp/conversion_test.go
- pkg/seccomp/filter.go
- pkg/seccomp/filter_test.go
- pkg/seccomp/seccomp_linux.go
- pkg/seccomp/validate.go
- pkg/seccomp/validate_test.go
The new `BuildFilter()` API can be used by runc/libcontainer to build
a libseccomp filter from the spec. This means that they also do not need
any internal structures any more because we indirectly build it from the
internal `Seccomp` type.
The new `ValidateProfile()` API can be used by higher level consumers,
which want to ensure that a seccomp profile string can be transferred
into a libseccomp filter.
Refers to https://github.com/opencontainers/runc/issues/2565
---
Short summary of the back and forth conversion between types: Right now it works like this:
1. CRI-O receives the profile as path and unmarshals it into the `Seccomp` type (formerly from seccom/containers-golang, now in this library)
2. CRI-O uses this library to convert the `Seccomp` type in to the runtime spec seccomp type …
> Add BuildFilter() and ValidateProfile() API

- pkg/seccomp/validate_test.go
This tests the last failure branch of the profile validation.
> Add seccomp validation unit test for failing BuildProfile()

- pkg/config/config.go
- pkg/config/config_test.go
Set pullpolicy case-insensitive for fixing https://github.com/containers/podman/issues/7246. And  to replace the duplicate code in podman with c/common code.
WIP Podman patch: https://github.com/containers/podman/pull/7585
> ValidatePullPolicy case-insensitive

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
> Allow pidfd_getfd by default in seccomp.json

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
This syscall is proposed for the kernel but does not exists yet.  Having it in
the default syscall table is causing crun to print warning messages.
> remove fchmodat2 from seccomp.json file

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Some users want to stick to "docker" format especially since some older
container registries don't properly support OCI images.
> Allow users to specify the default format for image builds

- pkg/config/containers.conf
In Fedora Rawhide, I have eliminated some CAPABILITIES from the
default list to make containers more secure. The containers.conf
should be listed here as well.  The default list in code is still
the Docker defaults, but I have eliminated three from the default
list
AUDIT_WRITE, MKNOD, NET_RAW
In Fedora 33 we have eliminated just MKNOD and NET_RAW.
> Specify the recommended defaults for security

- docs/containers.conf.5.md
- pkg/config/containers.conf
The current description is wrong it says that no-common does
not use cgrous, when it should say there is no cgroup
created for the conmon process.
Fixes: https://github.com/containers/common/issues/321
> Fix description of no-common options for cgroups

- pkg/report/template.go
- pkg/report/template_test.go
* Always Normalize --format value
* Additionaly fixed case where {{range}} with embedded \n caused
double \n\n on output
* Updated tests to cover these cases
> Fix --format corner cases

- pkg/config/default.go
Fix handling of storage.conf path, so that we can use it when testing podman.
Currently the Environment variable is not handled correctly.
There is a matching patches in containers/storage and eventually
containers/podman to allow the user of alternative storage.conf files in testing.
> Set storage path correctly

- pkg/config/config_local.go
Certain systems do not include
"/usr/share/zoneinfo",
"/etc/zoneinfo",
Which is causing failures to verify timzeones set to "", which is
the default.
> Don't check for timezone, unless user specified one

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
This flag would allow users to run the podman command
in podman-remote mode by default. If you are primarily using
podman to access a remote server, you might want to enable this
flag and not have to install podman-remote as well as podman command.
> Enabled the remote flag to be accessible by users

- pkg/config/containers.conf
This sysctl is an inclusive range and since the intention is to only
allow ping for root, setting it to `0 0` is adequate. This change
ensures that if a container is run from a user namespace where GID 1
isn't mapped, we won't get an EINVAL back when attempting to write this
sysctl value which would then cause an OCI runtime error.
Fixes #345
> fix: Set `ping_group_range` to `0 0` by default

- pkg/parse/parse.go
- pkg/parse/parse_test.go
- pkg/parse/parse_unix.go
- pkg/seccomp/supported.go
- vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
- vendor/modules.txt
We want to split out buildah/pkg/parse for components other
containers/engines are using without pulling in the buildah library.
> Move some volume and device parsing from buildah to common

- pkg/retry/retry.go
When retry with retryable error, add the error to the log meassage providing more info for debugging.
> Print the error to log info

- pkg/config/default.go
We should be sourcing from the image CMD/ENTRYPOINT by default. Having a default prevents us from doing that - we should only be using this for user-configured values that do not come from the image.
Beginning of the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1853455
> We should not be setting a default infra command.

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
> Add support for enabling/disabling kernel keyring in engines

- pkg/subscriptions/subscriptions.go
- pkg/umask/umask_unix.go
- pkg/umask/umask_unsupported.go
Currently callers to the pkg/umask and /pkg/subscriptions
have to make calls lib umask.SetUmask and subscriptions.Subscription
This PR removes the stutter, before people actually use the API.
> Fix Function names to not stutter

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
We decided that making users explicitly list plugins they wanted to use was not a bad thing, and greatly simplifies our implementation. As such, we need a place to do that, and `containers.conf` is the logical location.
> Add a volume plugins field to containers.conf

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Users could have any one of the OCI runtimes installed,
code will search for default.  This way they do not need
to modify defaults if they have "crun" installed.
Search order will be crun, runc, kata
> Find ociruntime instead of hard coding default

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
Systemd is now complaining or mentioning /var/run as a legacy directory.
It has been many years where /var/run is a symlink to /run on all
most distributions, make the change to the default.
Partial fix for https://github.com/containers/podman/issues/8369
> Switch references of /var/run -> /run

- pkg/auth/auth.go
- pkg/auth/auth_test.go
DOCKER_CONFIG environment variable is sometimes used to point
to the config.json.  The container engines use REGISTRY_AUTH_FILE
for similar functionality.  This PR causes programs that use
GetAuthFile to use DOCKER_CONFIG if it set and REGISTRY_AUTH_FILE
is not.
Begins fixing: https://github.com/containers/podman/issues/8796
> Add support for DOCKER_CONFIG

- pkg/completion/completion.go
--arch and --os have a limited number of options, and these
should be filled in automatically.
> Add completions for --arch and --os

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/default.go
In the containers.conf we default to true, but in code and man page
it is defaulted to false. Since Podman wants it defaulted to true
we need to change default and man page to match.
Also fixed the testing for SELinux, which would never succeed on an SELinux box.
Helps fix: https://github.com/containers/podman/pull/8844
> http_proxy is supposed to default to true.

- pkg/retry/retry.go
Also we now log at Warning level, so we should see the warnings on retries.
The current code retries on all failures except ECONNREFUSED.  We believe
this was a mistake, and should have been retrying on ECONNREFUSED, since this
could change on a retry.  On the other hand there are many other errno that
should not be ignored. This PR attempts to use the ERNNO that we assume might
be retryable and not retry on the others.
Fixes: https://github.com/containers/podman/issues/7963
> Do not retry on most syscall failures

- Makefile
- pkg/retry/retry.go
- pkg/retry/retry_linux.go
- pkg/retry/retry_unsupported.go
syscall.ERESTART is not defined on Darwin, so move to
an unsupported package. While this would work on Windows
this code most likey never will, so rather then complicate
code, I just left ERESTART on Windows as not supported.
> Current code fails to compile on Darwin no syscall.ERESTART

- pkg/secrets/filedriver/filedriver.go
- pkg/secrets/filedriver/filedriver_test.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
- pkg/secrets/secretsdb.go
This is the implementation of the backend of secrets. pkg/secrets takes a secret name and data and does operations on that secret data, most namely store, delete, lookup, and list, using a secretsmanager.
The first driver implemented here is a filedriver - where the data is stored unencrypted on disk in a file.
The secrets package can be easily expanded to use more drivers as the package implements an interface to accept different drivers
Related: https://github.com/containers/podman/issues/3264, https://github.com/containers/buildah/issues/1684
> Implement secrets pkg: backend and filedriver

- pkg/config/config.go
- pkg/config/config_test.go
Need to be able to getdefault container environment
based on use provided functions on httpProxy and use
the environment from the host.
This way users can modify the environment from podman
> Add new function to setup default environment

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
More details: https://lore.kernel.org/linux-mm/X+PoXCizo392PBX7@redhat.com/
> seccomp: drop 'vmsplice' from the allowed list

- pkg/retry/retry.go
- pkg/retry/retry_linux.go
- pkg/retry/retry_unsupported.go
Currently the difference between isRetryable and shouldRestart
is not clear in the function names, this simply makes them
more understandable.
> Rename internal functions to make them easier to understand

- Makefile
Fixes the make target all on osx  fixes #406
> fix - make target all on osx

- pkg/secrets/filedriver/filedriver.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
fix name validation to reject secret names that end with "-"
Create filedriver dir with proper permissions
> Fix name validation and dir mode in secrets

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Secret names should not end with "."
> Fix secret name validation

- pkg/config/default.go
For podman, we need to be able to get the log driver from common config.
Signed-off-by: baude <bbaude@redhat.com>
> Add accessor for log-driver

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
- pkg/secrets/secretsdb.go
Fix a bug where if the secret name was a prefix of an existing id, secrets would reject the new name
Now, you can use the secret name as expected
Example: if a secret with id "abcdefg" already exists:
Previously, it would error if you tried to create a secret with name "abc"
Now it allows you to do so
> Fix secret create prefix

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_override.conf
This will allow users to configure the amount of parallel copiess that
the container engines are allowed to do. This allows users to configure
their systems to match their available network settings.
> Add image_parallel_copies engine config

- pkg/chown/chown.go
- pkg/chown/chown_test.go
- pkg/parse/parse.go
This PR is to allow the U flag to be parsed when source volumes need to be chowned based on the container UID and GID.
This is a depency for this Podman PR [8349](https://github.com/containers/podman/pull/8349)
Signed-off-by: Eduardo Vega <edvegavalerio@gmail.com>
> Add U volume flag to chown source volumes

- pkg/report/doc.go
- pkg/report/template.go
- pkg/report/template_test.go
Add compatible template functions
"join":  strings.Join,
"lower": strings.ToLower,
"split": strings.Split,
"title": strings.Title,
"upper": strings.ToUpper,
Add and update tests to exercise these additions.
Update go doc with details of usage.
Fixes #8773
Closes https://bugzilla.redhat.com/show_bug.cgi?id=1915383
> Add compatible template functions

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_override.conf
Currently when pushing images we default to the format
of the source image.  Customers have asked us to allow them
to force a specific image type when pushing to a registry.
> Add image_default_format

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_override.conf
- version/version.go
Revert change to journald as default
This breaks a lot of the tests in Podman. Podman journald support
needs to be fixed, in order to merge this.  Will have to handle
this in the main branch and move defaults later.
> Revert change to journald as default

- pkg/report/template.go
- pkg/report/template_test.go
Previous code and tests did not reflect actual users input and expected
output.
Add remaining compatibilty golang template funcs
- json
- pad
- truncate
https://bugzilla.redhat.com/show_bug.cgi?id=1922077
Fixes #8702
> Updated report.template to be more compatible

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_override.conf
This reverts commit da196fb0f743a90a486aa6eb31df6807f4e67765.
Journald is not yet passing Podman CI.  We need to temporarily revert
the commit to unblock secrets work.
> Revert "Change default log driver to journald"

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
cri-o https://github.com/cri-o/cri-o/pull/4550 depends on this PR to update vendor.
part of https://github.com/kubernetes/kubernetes/pull/98205 for cri-o
> update pause image to 3.4.1

- docs/containers.conf.5.md
- pkg/config/containers.conf
Fix some alphabetic sorting.
Add missing default_network setting to containers.conf
> Add missing values to containers.conf man page

- pkg/report/template.go
- pkg/report/template_test.go
These functions were in podman but used with the report template.
They need to be used with Buildah secrets, so moving into common.
> Move EnforceRange and HasTable out of Podman and into common

- pkg/auth/auth.go
Since the GetDefaultAuthFile() is caused during podman init
it ends up logging the same info line multiple times, with
no way for the user to quiet the output.
Fixes https://github.com/containers/podman/issues/9473
> Stop logging messages about using DOCKER_CONFIG

- .github/dependabot.yml
This allows us to use the vendoring feature from dependabot.
> Add dependabot config file to support vendoring

- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
- version/version.go
add a new public function to retrieve all the capabilities in the
current bounding set.
This is useful for Podman to use only these capabilities when running
with --privileged as it can break running in a container where the
available capabilities can be a subset of the ones available in the
kernel.
> capabilities: add new method BoundingSet()

- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
- pkg/config/config_test.go
follow up to "capabilities: add new method BoundingSet()".
When ALL is used, limit it to the known capabilities in the bounding
set instead of ALL the known capabilities.
> capabilities: ALL returns the bounding set

- pkg/auth/auth.go
- pkg/chown/chown_unix.go
- pkg/chown/chown_windows.go
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/util_supported.go
- pkg/formats/formats.go
- pkg/parse/parse.go
- pkg/parse/parse_unix.go
- pkg/subscriptions/subscriptions.go
golang builtin OS functions, include the path to the object being used,
no reason for us to wrap these errors with an object for a second time.
This just causes stuttering, and looks bad at the CLI level.
Existing tests should catch any errors.
Also stop adding "error" to something that is obviusly an error when it
shows up to the user.
> [NO TESTS NEEDED] Remove some stuttering on return errors

- pkg/auth/auth.go
- pkg/auth/auth_test.go
`REGISTRY_AUTH_FILE` expects a complete path to the authentication file,
however `DOCKER_CONFIG` only refers to a configuration directory. The
function would only return the directory itself and cause confusing
errors when passed onwards to `container/image`.
$ DOCKER_CONFIG="/home/fox/.config/docker" podman pull docker.io/alpine
Trying to pull docker.io/library/alpine:latest...
read /home/fox/.config/docker: is a directory
[...]
$ DOCKER_CONFIG="/home/fox/.config/docker/config.json" podman pull docker.io/alpine
Trying to pull docker.io/library/alpine:latest...
open /home/fox/.config/docker/config.json/config.json: not a directory
[...]
Signed-off-by: Morten Linderud <morten@linderud.pw>
> pkg/auth: Ensure DOCKER_CONFIG refers to config.json

- pkg/config/config.go
Move contents of configs to Trace level, so debug information
will just tell you what the confile files are reading rather
then its contents.
Helps cleanup: https://github.com/containers/podman/issues/4854
> Cleanup debugf information to make debugging more useful

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
In order to run containers within containers via podman
and do a podman exec, we need to allow setns syscalls.
> Add setns to default seccomp.json

- pkg/config/config.go
Rephrase the log message and change the log level from
"warning" to "debug".
My comment https://github.com/containers/podman/issues/9389#issuecomment-782888578
explains why the log message
```
logrus.Warningf("Found default OCIruntime %s path which is missing from [engine.runtimes] in containers.conf", path)
```
does not make sense.
(I don't know if it should be %s or %q in the format string. It was %s before so I left it like that)
Fixes: https://github.com/containers/podman/issues/9389
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
> Change log message in findRuntime()

- pkg/config/config.go
avoid an unuseful warning message when running Podman as root without
enough capabilities.
> config: suggest enable-linger only if euid != 0

- libimage/copier.go
Users may with low bandwidth might want to adjust the number of
parallell pulls in their containers.conf, this hooks up the
contianers.conf settings to the copier opject.
> Add support for image_parallel_copies in containers.conf

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
machine_enabled is a bool that indicates if Podman is running in a
podman-machine VM
> Add support for machine_enabled in containers.conf

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/defaultnet/default_network.go
There are two changes here: firstly, add the ability to specify a subnet for the default CNI network in containers.conf; and secondly, add a package that can be consumed by Buildah and Podman to create said default network. This will allow us to stop shipping a default Podman CNI network, and instead dynamically create it on demand.
> Add support for creating default CNI network

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
This eliminates the concern of log files growing infinitely and also
records all containers for posterity rather then allowing the removal
of a container to destroy the record.
Partially fixes: https://github.com/containers/podman/issues/9158
> Swap default logging to journald

- libimage/pull.go
Dropping support for these would be a regression in tools that switch to this library.  We'd have noticed earlier, but buildah's integration tests that try pulling from `docker-daemon` sources (basically, those touched by https://github.com/containers/buildah/pull/3171) get skipped when there's no dockerd available, and the CI environments that run its integration tests apparently don't currently include a dockerd.
> libimage: restore the ability to pull from docker-daemon and tarball

- libimage/image_tree.go
To remain backwards compatible with the old behavior of Podman, we need
to print the layers in the reverse order.  Also make sure that we branch
correctly when `traversChildren` is true (`--whatrequires` in Podman).
> fix image tree

- libimage/pull.go
Recently images tagged by 64 chars cannot be pulled (e.g. length of `ghcr.io/stargz-containers/tomcat:10.0.0-jdk15-openjdk-buster-org` is 64).
```console
$ podman pull ghcr.io/stargz-containers/tomcat:10.0.0-jdk15-openjdk-buster-org
Error: pull policy is always but image has been referred to by ID (ghcr.io/stargz-containers/tomcat:10.0.0-jdk15-openjdk-buster-org)
```
This is because strings.Contains() is used where strings.ContainsAny() should be used.
This commit fixes this issue.
Please see also:
https://golang.org/pkg/strings/#Contains
> func Contains(s, substr string) bool
> Contains reports whether substr is within s.
https://golang.org/pkg/strings/#ContainsAny
> func ContainsAny(s, chars string) bool
> ContainsAny reports whether any Unicode code points in chars are within s.
> Fix images tagged by 64 chars cannot be pulled when "docker://" prefix is ommitted

- libimage/events.go
- libimage/image.go
- libimage/load.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/push.go
- libimage/runtime.go
- libimage/save.go
Add an event system to libimage.  Callers can opt-in to using events by
requesting an event channel via `(*Runtime).EventChannel()`.  The
returned channel has a buffer of size 100 which should be sufficient
even under high loads.  But, to be on the safe side, writing an event
will time out after 2 seconds to prevent operations from blocking.
Currently, the only user of such an event system is Podman which will
need to convert the `Event` type to what's used internally in libpod.
> libimage: add an events system

- libimage/pull.go
- libimage/search.go
Simplify the transports-sensitive dispatcher when pulling images and use
the default case for transports that do not require special casing.
> pull: simplify transports switch

- libimage/load.go
- libimage/load_test.go
Add unit tests for loading images.  This covers the most important
formats of docker-archive and oci-archive.
> libimage: add load unit tests

- libimage/pull.go
The recent refactoring introduced a bug yielding a pull from the dir
transport a NOP.  I will soon add unit tests for that.
> libimage: fix pull from dir

- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_linux.go
- pkg/config/config_windows.go
On Mac and Windows, automtically read default rootless config location, since
unshare.IsRootless doesn't work.
Should fix when vendored in: https://github.com/containers/podman/issues/9535
[NO TESTS NEEDED] because we still don't test on Mac/Windows :(
> [NO TESTS NEEDED] Fix reading configs on mac and windows

- pkg/config/config.go
- pkg/config/default.go
... before all user configuration files are merged.
This fixes containers/podman#9389.
> Do not emit warnings about OCI runtime paths

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
Commit 98ff7e145c2c changed the default logging driver k8s-file to
journald.  The only consumer of the log-driver is Podman which I think
still needs some more time to stabilize.  Vendoring containers/common
into Podman has revealed quite some warts (see
containers/podman/pull/10222) which reduced my confidence level.
To resolve the chicken-egg-problem of maturing the journald driver, I
want to only partially revert commit 98ff7e145c2c.  The built-in default
remains k8s-file while the containers.conf sets it to journald.  The
intention behind is to make sure that running systems are not impacted
but we can change Fedora to journald to increase coverage.
Once the confidence level is back to normal, we can change the default
to journald.  Latest before RHEL9.
Signed-off-by: Valentin …
> adjust log-driver defaults

- pkg/config/containers.conf
After experimenting with defaulting to journald as the default logging
driver, we have reverted to k8s-file in the built-in defaults in memory
but left journald the default in the containers.conf.
To prevent surprised in downstream packaging which may pick up the
containers.conf file, let's revert it as well.
@rhatdan @containers/podman-maintainers PTAL
> containers.conf: don't set default logging driver

- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
- pkg/config/config_test.go
You should be able to specify --cap-add=all --cap-drop=cap_perfmon
And end up with all capabilties except cap_perfmon.
You should not be allowed to specify --cap-add all --cap-drop all
The outcome would be undefined.
> Fix handling of all capabilities

- .cirrus.yml
These changes bring the YAML configuration and testing-image in-line
with practices and format used by all other containers-org. repos.  The
intention is to make it easier to maintain by maintaining configuration
and behavior hegemony.  Also, besides limiting flakes and surprises,
utilizing a pre-built container image avoids wasting time installing
packages at runtime.  Lastly, remove resource constraints on containers
so they operate with the maximum available.   This is more practical,
given there is but a single testing task and no parallelism is needed.
Signed-off-by: Chris Evich <cevich@redhat.com>
> Cirrus: Use config. in common with all repos.

- libimage/save.go
- libimage/save_test.go
Add save tests.  Also fix a bug when saving a single image but with
multiple tags.
@rhatdan @containers/podman-maintainers PTAL
> libimage: add save tests

- libimage/push.go
- libimage/push_test.go
- libimage/runtime.go
When pushing an image, make sure to ignore the platform of the image to
push exactly what the user wishes to.  Add a test to make sure we're not
regressing in the future.
To preserve previous behaviour with respect to attempting to push a
manifest list, move the platform check below resolving to a manifest
list.
Fixes: #containers/podman/issues/10344
> libimage: push: ignore image platform

- libimage/manifest_list.go
- libimage/manifest_list_test.go
- libimage/runtime.go
Commit b623a24c43b0 fixed an issue when pushing images from of a
platform different than the current machine.  That required to disable
the platform matching logic when looking up the image before pushing it.
It also required some restructuring of the code such that manifest lists
are resolved and their instances looked up.
The restructuring in turn introduced a regression when looking up bare
manifest lists.  To fix the regression and keep the code simple,
introduce an internal field in the LookupImageOptions that indicates
whether we're looking up a bare manifest list or not.
Now we have clearer separation of concerns between looking up images or
manfifests and whether the looked up image needs to match the current
platform or not.
Add some unit tests exercising the manifest-list code …
> libimage: fix manifest list lookup

- libimage/runtime.go
Recent changes in the image-lookup logic will, in many cases, yield a
check whether an image is a manifest list.  This had caused a regression
in Podman's test/system/330-corrupt-images.bats system tests where we're
attempting to delete a corrupted image with a missing manifest.  Since
the manifest is missing, the manifest list check fails.
To make the image lookups more tolerant towards this specific error
case, we need to ignore the error but emit a warning, similar to what
we're already doing in the parent-child checks.
> libimage: lookup: tolerate corrupted image

- pkg/config/config.go
- pkg/config/default.go
This reverts commit 1752a5668095930a6e67df077f82c94e41e0d8a1 as it's
causing a regression as it overwrites any custom OCI runtime with either
rucc, crun or kata.  See the Podman CI failure below:
```
[+0383s] not ok 95 podman build - set runtime
[+0383s] # (from function `die' in file test/system/helpers.bash, line 412,
[+0383s] #  from function `run_podman' in file test/system/helpers.bash, line 220,
[+0383s] #  in test file test/system/070-build.bats, line 70)
```
I currently do not have the time for a proper fix but the next commit
attempting to address the warnings must include tests.
> Revert "Do not emit warnings about OCI runtime paths"

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Set type of rootless networking with:
rootless_networking = "slirp4netns | cni"
slirp is the default
Signed-off-by: Brent Baude <bbaude@redhat.com>
> rootless networking

- libimage/image.go
- libimage/image_test.go
- libimage/testdata/registries.conf
Add unit tests for exercising all kinds of function of an `Image`
object.
Also remove an unused, redundant (and incomplete) `MountPoint` function.
`Mountpoint` is used by Podman instead.
@rhatdan @containers/podman-maintainers PTAL
> libimage: add more image tests

- pkg/config/default.go
We were hardcoding Slirp4netns as the only valid option for rootless when "private" networking was selected. We shouldn't be doing that - the default networking selection in Podman itself is smart enough to figure out what to do, c/common should not decide for us.
> Use Private as default for rootless when we want CNI

- pkg/defaultnet/default_network.go
It's not required (CNI is perfectly happy to accept conflists that do not include it) and it seems to be breaking default network creation as non-root.
> Do not include gateway in generated default networks

- pkg/defaultnet/default_network.go
We need to make sure the default network directory gets created if it does not exist. We previously did this after CNI was initialized but this could race on CNI recognizing the new network, so we moved it before CNI init. Unfortunately, CNI init made the configuration directory, so we now have to do that ourselves.
> Ensure configuration directory is created for networks

- libimage/normalize.go
- libimage/normalize_test.go
- libimage/pull.go
- libimage/pull_test.go
- libimage/runtime.go
For the sake of Docker compatibility, support the tag@digest notation.
In that case, the tag is stripped off the reference and the digest is
the sole source of truth.
Add a number of tests to make sure we're behaving as expected.
Context: containers/podman/issues/6721
@rhatdan @nalind PTAL
> support tag@digest notation

- libimage/pull.go
Fixes: #581
@rhatdan @mtrmac PTAL
> pull: don't resolve short names on explicit docker:// reference

- libimage/pull.go
- version/version.go
Backport commit f9933ce50ec3 plus version bump.
@rhatdan PTAL
> [0.38] pull: don't resolve short names on explicit docker:// reference

- pkg/config/config_test.go
- pkg/config/default.go
- pkg/config/nosystemd.go
- pkg/config/systemd.go
Currently we have users failing to run containers within containers
or on systems without systemd support.  This change will give us
better defaults on these systems.
Fixes: https://github.com/containers/common/issues/580
> Don't use systemd defaults if /proc/1/comm != systemd

- Makefile
- pkg/config/systemd.go
The errors sneaked through CI as we didn't use the systemd build tag for
testing.
@rhatdan @giuseppe PTAL
> pkg/config: fix systemd compile errors

- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
The default netns must be empty. Podman should decide what the default
option is. While podman also defaults to slirp4netns as rootless and
bridge as root, there are also other defaults for `podman run --pod ...`
and `podman pod create --infra=false` where it defaults to the pods
netns. This config field was always ignored by podman and trying to
make it work requires this patch since the default values are incorrect
for podman.
Buildah does not seem to use it either.
Also move the rootless_networking field in the default config file to
the correct containers stanza.
> Do not set the default netns

- pkg/config/config_local_test.go
the config.Write() command looks for the CONTAINERS_CONF setting,
since we were resetting it back to default, it was mistakenly
overwriting the user executing the tests local containers.conf file.
> Tests are writing customer config to host machine

- .cirrus.yml
- pkg/secrets/passdriver/passdriver.go
- pkg/secrets/passdriver/passdriver_test.go
- pkg/secrets/secrets.go
This adds a `passdriver` subpackage to the secrets management package. It is compatible with `gopass`or `pass`to store and retrieve secrets.
`pass`and `gopass`are two small command line based password managers. `pass` is the original one and is just a shell script which makes it easy to store and retrieve passwords from gpg encrypted local files. `gopass`is a rewrite of it in go which adds some nice features (like integrating git)
Here is the website of the `pass`project: https://www.passwordstore.org/
And here for `gopath`:  https://github.com/gopasspw/gopass
This driver can be configured by two options `root`and `key`.
`root`specifies the directory where the secrets are stored. If it is a subdirectory of or directly a already initialized password store, the `key`is automatically set to …
> add passdriver for secrets.

- pkg/secrets/passdriver/passdriver.go
io.Discard was added to go 1.16, prefer ioutil.Discard that is also
present in older Go versions.
> secrets: fix build with go 1.15

- pkg/config/default.go
The default path should be empty in order for podman to distinguish
between a path the was explicitly or to use the default (in memory)
profile.
Fixes: containers/podman#10556
> Leave default seccomp path empty

- libimage/import.go
Signed-off-by: cdoern <cbdoer23@g.holycross.edu>
Making necessary changes in order to reference a platform as described in [this issue on podman](https://github.com/containers/podman/issues/10566). This PR modifies the ImportOptions struct to handle OS/Arch and added two lines so that the config reads in these new parameters. Will open up a new PR on podman to handle parsing of OS/Arch [here](https://github.com/containers/podman/blob/master/pkg/api/handlers/compat/images.go#L168).
This is stemming from implementation of the platform parameter in the docker-compatabile API of podman. As seen [in image_routes.go](https://github.com/docker/engine/blob/7c6a9484ee37b28fa314f716581bdb268cd78ce2/api/server/router/image/image_routes.go#L85) the docker engine handles platform with both fromSrc and …
> made necessary changes to handle OS/Arch while importing an image

- libimage/pull.go
An image can be corrupted if, for instance, a pull or build
operation is killed (e.g., during commit).  In such cases, an image may
be listed even if a layer is missing.
Over time, Podman and Buildah have made various execution paths more
robust to handle such cases gracefully and/or give the users some help
in trying to resolve the issue.  So far, the recommended way was to
remove the corrupted image from storage and then pull it.
The linked Bugzilla issue raised the desire to simplify the recovery by
allowing to pull an image even if the local counterpart is corrupted.
This is especially important for installer scenarios, where users may
restart the installer which would attempt to pull the image again.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1966872
Signed-off-by: …
> libimage: pull: turn image-lookup errors non-fatal

- libimage/pull.go
- version/version.go
Backport of https://github.com/containers/common/pull/609 plus version bump.
@rhatdan @saschagrunert PTAL
> 0.38 backports

- libimage/corrupted_test.go
- libimage/runtime.go
While various execution paths in libimage already handle corrupted
images, `(*Runtime).Exists()` did not and would list an image to exist
in the storage even if it is corrupted.
Some corruptions can only be detected when accessing the individual
data.  A reliable way of accessing such data is to inspect an image.
Hence, an image will only be listed to exist if a) it has been found
and b) can be inspected.  If the inspection fails, the image will be
reported to not exists but without an error.  That allows for users
of libimage to properly recover and repull.
Further, add a new unit tests that forces a data corruption and
gradually recovers from it.
Podman will now behave as follows:
```
$ ./bin/podman run -d --rm nginx ls
ERRO[0000] Image nginx exists in local storage but may be …
```
> libmage: Exists: catch corrupted images

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_override.conf
This adds a 'secret' section to the `config.Config` struct. I do this as a follow up to #514 so we can specify which driver to use by default + its options in the config file. As a next step I'd like to evaluate that config in podman in the `infra.ContainerEngine.SecretCreate` function. At this point we would be able to use the new passdriver for secrets.
> add 'secret' section to the containers.conf struct.

- libimage/corrupted_test.go
- libimage/runtime.go
Commit 964b00275fe2 introduced a regression to Exists() which would
return an error if the image does not exist.
> libimage: fix Exists

- docs/containers.conf.5.md
- pkg/config/containers.conf
Remove cgroup_check which is no longer needed.
Fixes: https://github.com/containers/common/issues/372
> [NO TESTS NEEDED] Sort containers.conf and containers.conf.5.md

- pkg/config/containers.conf
Replaces:  https://github.com/containers/common/pull/556
Signed-off-by: unknowndev233@github unknowndevQwQ@protonmail.com
> Fix spacing on name value pairs to be consistent

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
allow time64 variant of timer_settime which was missed in 4e31f66
Signed-off-by: Jan Palus <jpalus@fastmail.com>
> seccomp: allow timer_settime64

- pkg/seccomp/conversion.go
- pkg/seccomp/default_linux.go
- pkg/seccomp/filter.go
- pkg/seccomp/seccomp.json
- pkg/seccomp/seccomp_linux.go
- pkg/seccomp/types.go
add the currently blocked syscalls to a deny-list and switch the default to ENOSYS.
> seccomp: switch default to ENOSYS

- pkg/report/template.go
- pkg/report/template_test.go
When wrapping table format in range, string extra new lines from table
ends.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1855983
> Strip extra trailing newlines in templates

- pkg/auth/auth.go
- pkg/auth/cli.go
Goes in parity  with https://github.com/containers/podman/pull/10068 and https://github.com/containers/image/pull/1204
Depends on: https://github.com/containers/image/pull/1204
> Use SetCredentials and add verbose to loginopts

- libimage/download.go
- libimage/runtime.go
- libimage/runtime_test.go
Currently if the caller does not specify the BigFilesTemporaryDir,
Podman and Buildah users expect this to default TMPDIR environment
variable or /var/tmp if not set.
Moving to libimage caused a regression in this functionality.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1972282
> Set BigFilesTemporaryDir to GetEnv(TMPDIR) if set or /var/tmp 

- go.mod
- go.sum
- libimage/image.go
- libimage/load_test.go
- libimage/remove_test.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
When removing an image by name, do not remove the image and all its
tags, even if force is set.  Instead, just untag the specified name.
Context: containers/podman/issues/10685
> libimage: force remove: only untag on multi tag image

- libimage/pull.go
- libimage/pull_test.go
- libimage/runtime.go
Allow for looking up images via customizable arch, os and variant.
This prevents `podman run --arch=xxx` from redundantly pulling down the
image if needed.
Context: containers/podman/issues/10648
> libimage: lookup images by custom platform

- libimage/image.go
- libimage/load_test.go
- libimage/remove_test.go
When removing an image by name, do not remove the image and all its
tags, even if force is set.  Instead, just untag the specified name.
Note: adjust the load test to preserve the order in the untagged field.
Also vendor in the latest HEAD in containers/image to fix a bug revealed
in Podman CI.
Backport of commit c6578d76fb0da6f6a87d62ac33306945dc616205.
Context: containers/podman/issues/10685
> [0.38] libimage: force remove: only untag on multi tag image

- pkg/config/config.go
- pkg/config/config_local_test.go
If a root user writes to a config using Write(), and there is not already an /etc/containers/containers.conf, Write() will create it. This config file also needs to be read by non-root podman.
> Allow /etc/containers/containers.conf to be read by non-root

- libimage/corrupted_test.go
- libimage/image.go
- libimage/pull.go
- libimage/runtime.go
We must ignore the platform of a local image when doing lookups.  Some
images set an incorrect or even invalid platform (see
containers/podman/issues/10682).  Doing the lookup while ignoring the
platform checks prevents redundantly downloading the same image.
Note that this has the consequence that a `--pull-never --arch=hurz` may
chose a local image of another architecture.  However, I estimate the
benefit of continuing to allow potentially invalid images higher than
not running them (and breaking workloads).
The changes required to touch the corrupted checks.  I used the occasion
to make the corrupted checks a bit cheaper.
> libimage: pull: ignore platform for local image lookup

- libimage/corrupted_test.go
- libimage/image.go
- libimage/pull.go
- libimage/runtime.go
- pkg/config/config.go
- pkg/config/config_local_test.go
- version/version.go
* libimage: pull: override even --pull=never with custom platfo
* libimage: pull: enforce pull policy for custom platforms
* libimage: pull: ignore platform for local image lookup
* Allow /etc/containers/containers.conf to be read by non-root
* [0.38] libimage: force remove: only untag on multi tag image
@rhatdan @Luap99 @mheon PTAL
Those are the backports for Podman v3.2.2
> 0.38 backports plus bump to v0.38.10

- libimage/runtime.go
- libimage/runtime_test.go
Add a method to the libimage runtime to access (a copy of) its
types.SystemContext.  That can be helpful for callers which may need to
access the system context.
> libimage: `(*Runtime).SystemContext()`

- version/version.go
> bump to v0.38.11

- libimage/pull.go
Do not use the name of the locally resolved image when pulling an image
with a custom platform.  As we recently re-discovered [1], many
multi-arch images in the wild do not adhere to the OCI image spec and
either declare custom or simply wrong platforms (arch, os, variant).
To address such wrong images, we enforce the pull-always policy whenever
a custom arch, os or variant is specified.  We have to do that since we
cannot reliably perform platform matches to any image we would find in
the local containers storage.
To complete the fix, we need to ignore any local image and not use the
locally resolved name which we usually have to do (see [2]).
Let's assume we have a local image "localhost/foo" (arch=amd64).  If we
perform a `pull --arch=arm64`, we would not attempt to be pulling …
> pull: custom platform: do not use local image name

- libimage/image.go
- libimage/load.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/push.go
- libimage/save.go
Some users rely on events being written *after* the operation ran.
Hence, defer all event writes.
Context: containers/podman/issues/10812
> libimage: events: deferred write

- pkg/secrets/secrets.go
- pkg/secrets/shelldriver/shelldriver.go
- pkg/secrets/shelldriver/shelldriver_test.go
*What*
This adds a new secret driver "shell" to the secrets package. It is configured by providing 4 little shell commands that implement Store, Lookup, List and Delete. 
*Why*
It can be used to access all sorts of secret storages that can be accessed via command line like vault or bitwarden. It would also enable us to have a pass/gopass implementations that would also work with HOTP/TOTP, keys from crypto devices etc.
Another usecase could be to resuse secrets from an accessable k8s cluster by providing the correct kubectl calls for the 4 shell commands.
All in all I think this might be very usefull for advanced users that just want to get their specific usecase to work. Sure, having all sorts of specific secret drivers would be better, but this is a convenient integration point. I think …
> feat: add shell secret driver.

- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_broken.conf
Currently if a user puts a typo into a contianers.conf
or puts the keys in the wrong section, then tools using
container-common ignore them. This patch will print them
as warnings, so that the user has some ide.
[NO TESTS NEEDED] Since I have no idea how to test this.
I have tested this locally with Podman.
./bin/podman run alpine echo hi
WARN[0000] Failed to decode the keys ["containers.events_logger" "engine.foo"] from "/home/dwalsh/.config/containers/containers.conf".
WARN[0000] Failed to decode the keys ["containers.events_logger" "engine.foo"] from "/home/dwalsh/.config/containers/containers.conf".
WARN[0000] Failed to decode the keys ["containers.events_logger" "engine.foo"] from "/home/dwalsh/.config/containers/containers.conf".
WARN[0000] Failed to decode the keys …
> Report bad entries in containers.conf to the user

- libimage/filters.go
- libimage/pull.go
- libimage/save.go
- vendor/github.com/mitchellh/mapstructure/.travis.yml
- vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
- vendor/github.com/mitchellh/mapstructure/LICENSE
- vendor/github.com/mitchellh/mapstructure/README.md
- vendor/github.com/mitchellh/mapstructure/decode_hooks.go
- vendor/github.com/mitchellh/mapstructure/error.go
- vendor/github.com/mitchellh/mapstructure/go.mod
- vendor/github.com/mitchellh/mapstructure/mapstructure.go
- vendor/modules.txt
Stop the whack-a-mole selectively patching multi-arch issues by forcing
all internal image lookups to ignore the platform.
In retrospect, the `IgnorePlatform` options for image lookups was a
mistake and I will remove it soon but for now, let's just patch
something we can backport to the v0.38 branch.
> libimage: force internal image lookups to ignore arch

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
We had a bogus setting for secrets in our default containers.conf
[secret] should have been [secrets].
Also added a test to make sure this never happens again.
> Fix default definition of secrets in containers.conf

- Makefile
- pkg/config/config_test.go
- pkg/config/default.go
- pkg/config/nosystemd.go
- pkg/config/systemd.go
Currently we have users failing to run containers within containers
or on systems without systemd support.  This change will give us
better defaults on these systems.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1979497
I did not bump the version yet as I want to wait a bit for more things to pile up.
> [0.38] Don't use systemd defaults if /proc/1/comm != systemd

- libimage/import.go
- libimage/import_test.go
When importing, first create the image and tag it afterwards.  This also
makes sure that an imported image *without* a tag is correctly listed as
"<none>".  Previously, such images were tagged as
"docker.io/library/sha256:$ID" (inherited from older Podman code).
Context: containers/podman/issues/10854
> libimage: import: fix tags

- libimage/filters.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/pull_test.go
- libimage/push.go
- libimage/runtime.go
- libimage/save.go
When writing LookupImage, I thought that it's a good idea to always
attempt to match an image against the local (or requested) platform.
The use case I had in mind is multi-arch support:
`$ podman run image` should only match `image` if it matches the local
platform.  We may have previously pulled `image` for another
architecture.
The core criteria for these checks is that images set their platform
(arch/os/variant) correctly.  As it turned out that is not the case.
We recently performed a number of fixes to better support multi-arch
images and this change should put the last nail in the coffin.
Hence, entirely remove the `IgnorePlatform` option and only perform
platform matches if the arch, os or variant is specified explicitly via
the LookupImageOptions or the runtime's system context …
> libimage: LookupImage: remove IgnorePlatform option

- libimage/import.go
- libimage/import_test.go
When importing, first create the image and tag it afterwards.  This also
makes sure that an imported image *without* a tag is correctly listed as
"<none>".  Previously, such images were tagged as
"docker.io/library/sha256:$ID" (inherited from older Podman code).
Context: containers/podman/issues/10854
> [0.38] libimage: import: fix tags

- libimage/image_tree.go
(*Image)Tree() hit a nil deref when traversing the children of an image
without a physical layer.
There are no tests _here_ for image tree yet, so I hope you trust me :) @rhatdan @Luap99 PTAL
> libimage: image tree: fix nil deref

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/default.go
A new container engine config boolean determining whether files copied into a container should have changed ownership to the primary uid/gid of the container.
> add config option for ChownCopiedFiles

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
Docker does this by default.
Relates to podman#10262
Signed-off-by: Vikas Goel <vikas.goel@gmail.com>
> User option to prepare container after creation for volume copy-up.

- libimage/pull.go
Commit bee8cae83037 enforced the pull policy to "always" when a custom
platform was specified.  The reason for always pulling is that many
multi-arch images are broken; wrong configs, wrong platforms, etc.
We cannot perform reliable platform checks.  While we may to have to
revisit this strategy in the future, it is more important to keep
existing workloads running; a bit between a rock and hard place.
This change complements commit bee8cae83037: if attempt to pull an image
that resolves to "localhost/", set the pull policy "newer" instead of
"always" such that the image may be used instead of erroring out.
Ultimately to preserve previous behavior.
Context: containers/podman/issues/10914
> pull with custom platform: handle "localhost/"

- libimage/runtime.go
When it was first introduced, the blob info cache's location didn't
change from the system-wide default location when we were running in
rootless mode, so we started setting its location ourselves to avoid
triggering permissions errors when updating it.
The image library has since started taking into account that it was
running in rootless mode, but its hardwired default isn't the same as
the one we were setting, so we ended up creating a second cache file.
Stop doing that.
Fixes #682.
> libimage.RuntimeFromStore(): stop overriding the BlobInfoCache location

- libimage/filters.go
- libimage/image.go
- libimage/image_test.go
- libimage/layer_tree.go
- libimage/runtime.go
A set of commits to fix https://github.com/containers/podman/issues/10832:
* Extend the dangling filter from "untagged image" to "untagged image without children" to match Docker.
* Fix a bug in image removal where _some_ removed images were not reported as such.
* Extend the layer tree to also consider images with an empty top layer.
Podman PR: https://github.com/containers/podman/pull/10983
Buildah PR: https://github.com/containers/buildah/pull/3390
> fix "dangling" filter and pruning

- libimage/pull.go
- libimage/pull_test.go
Normalize images pulled from the docker-daemon transport to docker.io
and not to localhost.  That preserves previous behavior of Podman.
Also fix a parsing bug in the pull code that was revealed while testing
the changes; parsing errors should be returned if there is a matching
transport without falling through to pulling the input string as an
image from a registry.
Context: containers/podman/issues/10998
@rhatdan @Luap99 PTAL
> libimage: pull: normalize docker-daemon

- pkg/seccomp/conversion.go
- pkg/seccomp/filter.go
- pkg/seccomp/seccomp_linux.go
- pkg/seccomp/types.go
- version/version.go
This is a partial backport of https://github.com/containers/common/pull/573 to v0.38 branch.
Needed to fix https://github.com/containers/podman/issues/11029 and the likes.
Original description follows.
----
Add support to specify the default errno return value.
The OCI runtime specs already have support for it, and both crun (>=
0.19) and runc (>= 1.0-rc95) have support for it.
(cherry picked from commit adee333df76c02d99c740cf82cdf6074cade49b9)
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
> [0.38] seccomp: add support for defaultErrnoRet

- pkg/seccomp/types.go
This prevents
"defaultErrnoRet": null,
from appearing in seccomp.json, in case `DefaultErrnoRet` is not set
(if set, this is purely cosmetical).
This member is similar to ErrnoRet in type Syscall,
and should also be marked with omitempty.
Fixes: adee333df76c02d99c740c
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
Forward ported from https://github.com/containers/common/pull/689
Cc; @giuseppe
> pkg/seccomp: avoid DefaultErrnoRet: null

- libimage/copier.go
- libimage/image.go
- libimage/import.go
- libimage/pull.go
When copying images into local storage, parse the manifest of the copied image and then look up the IDs of the matching image.
There's a short period of time, between when we copy the image into local storage and when we subsequently go to look for it using the name that we specified for it when we copied it, when the name we wanted to assign to the image could have been assigned to another image by another process.
The manifest that we copied as part of the image that we copied will still be in the right image regardless, and we can use that to find the image's ID, and from there fill out our own Image structure that we return to our caller.
> Add and use libimage.Runtime.imageIDsForManifest()

- pkg/config/config.go
split the DBUS_SESSION_BUS_ADDRESS value so that something like:
unix:path=/run/user/1000/bus,guid=817e9ffcfb383869ad17ea8360e7428a
will ignore ",guid=817e9ffcfb383869ad17ea8360e7428a" when checking
that the path exists.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1984531
> config: split arguments in DBUS_SESSION_BUS_ADDRESS

- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
Add a `LockerForImage()` function that allocates and returns a file-based lock for an image record that we're using to hold a manifest list.  Without some locking mechanism, two processes that wish to update a list at roughly the same time can't do so without risk of accidentally discarding one or the other set of changes.
Multiple processes that merely want to read the list can already safely do so; only cases with multiple writers that need to bother with using this function.
> Add libimage/manifests.LockerForImage()

- libimage/search.go
An authfile path set by `podman search --authfile` is passed in
`SearchOptions`. This fix uses this authfile for accessing
registries.
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
> Use authfile in options to search image

- pkg/config/pull_policy.go
The K8s pull policies are in camel case:
* Always
* IfNotPresent
* Never
Support them in conjunction to Missing, Newer and IfNewer.  Doing it
here prevents Podman (and possibly CRI-O in the future) from adding
custom parsers.
@cdoern @containers/podman-maintainers PTAL
> pull policy: support camel cases

- pkg/auth/cli.go
We decided to remove the flag and opt-in via the options from Podman.
This means we do not need the flags any more, but keep the configuration
itself.
PTAL @rhatdan @mtrmac @vrothberg 
Ref https://github.com/containers/podman/pull/11054
> Remove `--accept-repositories` flag

- version/version.go
Doing the vendor dance.
@rhatdan @TomSweeneyRedHat @containers/podman-maintainers PTAL
Once merged, we can create a `release-0.42` branch and tag+release.
> bump to v0.42

- pkg/config/containers.conf
Some details: https://github.com/containers/common/pull/556#issuecomment-850772563
Signed-off-by: unknowndev233@github <unknowndevQwQ@protonmail.com>
> complete containers#556 to-do list

- Makefile
- go.mod
- pkg/config/default.go
- pkg/config/nosystemd.go
- pkg/config/systemd.go
- vendor/github.com/coreos/go-systemd/v22/internal/dlopen/dlopen.go
- vendor/github.com/coreos/go-systemd/v22/sdjournal/functions.go
- vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go
- vendor/github.com/coreos/go-systemd/v22/sdjournal/read.go
- vendor/modules.txt
> Switch default logdriver and eventslogger to journald, if root

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Current default for image_stream is "testing"
> Add machine_image to containers.conf

- Makefile
Container/storage now only links in libsubid if libsubid tag is set.
no_libsubid tag no longer exists.
> Remove no_libsubid flag

- pkg/parse/parse.go
Closes: https://github.com/containers/podman/issues/10900
Destination path inside containers should be always validated  as
***nix**type absolute path. 
So its recommended to use `path.IsAbs()` instead of `filtepath.IsAbs()` for destination checks. Since `filepath.IsAbs()` will use path_windows on windows host but destination path inside the containers should always be of ***nix** type.
Reference:
https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/path/path.go;l=219
https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/path/filepath/path_windows.go
https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/path/filepath/path_unix.go
> path: dest paths inside container should always be treated as *nix type

- libimage/image.go
- libimage/image_test.go
- version/version.go
Fix the regression detected in https://github.com/containers/podman/pull/11211 and cut a fresh version.
@rhatdan PTAL
See individual commits for descriptions.
> fix untag + v0.43.2

- pkg/sysctl/sysctl.go
Sync with https://github.com/containers/podman/pull/11224
Signed-off-by: Yan-Ming Li <xatierlike@gmail.com>
> Add space trimming check in sysctl.Validate

- libimage/manifest_list_test.go
- libimage/runtime.go
If matching images resolves to a manifest list, return manifest list
instead of resolving to image instance, if manifest list is not found
try resolving image.
> runtime: Add `ManifestList` to `LookupImageOptions`

- libimage/corrupted_test.go
- libimage/disk_usage.go
- libimage/image.go
Make sure to check an image for corruption before running disk usage on
it.  Such checks are already applied on various execution paths but not
yet on disk usage.
Further update the corrupted-image error to include that the image
should be removed to resolve the error.  This should ultimately guide
users to resolve the issue.
Fixes: #751
@Luap99 @giuseppe @containers/podman-maintainers PTAL
> libimage: disk usage: catch corrupted images

- libimage/manifest_list_test.go
- libimage/runtime.go
Adds  `LookupManifest` to `RemoveImagesOptions.`
Following flag allows user to configure RemoveImages in a manner so that
remove func becomes exclusive to removing manifests when needed and not
removing underlying referenced images.
> remove-image: Add optional `LookupManifest` to RemoveImagesOptions. 

- pkg/config/config.go
- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
This should better support rootless CNI usescases.
Fixes https://github.com/containers/podman/issues/11396
> Switch default Rootless Networking to "CNI" for OSX

- docs/containers.conf.5.md
Avoids a nroff warning in the generated manpage
[CI:DOCS]
Signed-off-by: Reinhard Tartler <siretart@tauware.de>
> docs/containers.conf.5.md: Fix manpage section

- pkg/config/util_supported.go
Podman should not use `/tmp/run-...`. The Podman PR#8241 changed the
path to `/tmp/podman-run-...` and added systemd tmpfile config to make
sure the path is not removed. However the tmpDir is set in c/common and
was never changed.
Fixes containers/podman#11478
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> Fix the fallback runtime path

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_linux.go
- pkg/config/config_test.go
- pkg/config/config_windows.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
This field contains a list of directories which should be used to store
some helper binaries, e.g. gvproxy.
Also add a FindHelperBinary method to the config struct to get the full
path to a helper binary.
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> Add HelperBinariesDir field to engine config

- libimage/corrupted_test.go
- libimage/disk_usage.go
- libimage/image.go
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
- pkg/config/util_supported.go
#759 Fix the fallback runtime path 
66fee592b112e40e7a9178d2f39ed48994cf0c9c
#754 Switch default Rootless Networking to "CNI" for OSX
854253d305b4c4fe0df19af74d4833b71afeb7af
#752 libimage: disk usage: catch corrupted images
ade9985425d4c3ad57cef2eb19c7b1e70994b7c0
> Backports for Podman 3.3.2

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_override.conf
Allow users to set the default location for the temporary files used
during image pulls and pushes.
Defaults to /var/tmp;
Overridden via "TMPDIR" environment variable.
Allow special flag "storage" to indicate the the storage should use
the tmp directory in containers/storage/tmp.
Needed to fix: https://github.com/containers/podman/issues/11107
> Add support for image_copy_tmp_dir

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
Signed-off-by: Frederic Crozat <fcrozat@suse.com>
Allow to use krun (symlink to crun, when built with libkrun support) as OCI runtime
> Add support for the krun (runc running in KVM) OCI Runtime

- libimage/image.go
- libimage/image_test.go
- libimage/pull.go
Allow for passing down credentials when comparing a local image with a
remote one.  The linked BZ relates to a regression in `podman auto-update`
but while reading the code I noticed it's also impacting pull policies.
BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
> (*libimage.Image).HasDifferentDigest: add authentication

- libimage/image.go
- libimage/image_test.go
- libimage/pull.go
- version/version.go
Allow for passing down credentials when comparing a local image with a
remote one.  The linked BZ relates to a regression in `podman auto-update`
but while reading the code I noticed it's also impacting pull policies.
BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
Note the version bump.
DO NOT MERGE BEFORE https://github.com/containers/common/pull/775
@nalind @rhatdan PTAL
> [0.42] (*libimage.Image).HasDifferentDigest: add authentication

- libimage/image.go
- libimage/image_test.go
- libimage/pull.go
- version/version.go
Allow for passing down credentials when comparing a local image with a
remote one.  The linked BZ relates to a regression in `podman auto-update`
but while reading the code I noticed it's also impacting pull policies.
BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
Note the version bump
DO NOT MERGE BEFORE #775
@nalind @rhatdan PTAL
> 0.44 digest creds

- pkg/config/config_test.go
- pkg/config/default.go
If you use this field in rootless mode, it will blow up,
since rootless mode can not use the host user namespace.
> UserNS should default to '' rather then host

- libimage/copier.go
allow to specify the compression format and compression level.
> libimage: accept CompressionFormat/CompressionLevel

- pkg/secrets/secrets.go
- pkg/secrets/secretsdb.go
There is code in podman which uses `errors.Cause(err).Error() != "no such secret"`,
this is just bad code. Common should expose this error so podman
can check with `errors.Is()`.
> Export no such secret error

- libimage/copier.go
Add an option to allow for accepting uncompressed layers when
copying OCI images.
Context: github.com/containers/podman/issues/11613
@rhatdan @Luap99 @giuseppe PTAL
> copier: add OciAcceptUncompressedLayers option

- libimage/load.go
When loading a path we have to "guess" the underlying format and hence
attempt loading supported formats in a specific order.  When all
attempts have failed make sure that all loading errors are reported up,
in addition to debug logs, such that users can parse them for useful
information.
Fixes: github.com/containers/podman/issues/11730
> libimage: load: improve error messages

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Add machine teable to configure podman machine options. Move
machine_image to the machine table, and add disk size to the machine
table.
> Add machine table to containers.conf

- libimage/copier.go
- libimage/image.go
- libimage/manifests/manifests.go
- libimage/runtime.go
- pkg/apparmor/apparmor_linux.go
- pkg/retry/retry.go
- pkg/subscriptions/subscriptions.go
- pkg/supplemented/supplemented.go
- pkg/sysinfo/sysinfo_linux.go
> Standardize on capatalize logrus messages, remove stutters

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Backport to v0.44: 
Add machine table to configure podman machine options. Move machine_image to the machine table, and add cups, disk size, and memory to the machine table.
> [v0.44] Backport add machine table to containers.conf

- go.mod
- go.sum
- libimage/copier.go
- libimage/corrupted_test.go
- libimage/image_config.go
- libimage/inspect.go
- libimage/runtime.go
- vendor/modules.txt
Use github.com/json-iterator/go instead of the standard library.
It is faster and battle tested.
> libimage: use faster json library

- pkg/config/config.go
- pkg/config/config_test.go
When toml writes the config file it does not use `omitempty` for numeric
values instead it requires `omitzero`. [1]
The problem is that without this change, `config.Write()` writes
```
[machine]
cpus = 0
disk_size = 0
memory = 0
```
to the user file. Because podman machine system connection add code will
do this the config file is broken afterwards. The first vm will be created
successfully but after this every other vm will be broken because the
cpu, memory and disk size are set to zero.
[1] https://github.com/BurntSushi/toml/pull/81
Fixes containers/podman#11824
> config: add omitzero for numeric types

- pkg/config/config.go
- pkg/config/config_test.go
When toml writes the config file it does not use `omitempty` for numeric
values instead it requires `omitzero`. [1]
The problem is that without this change, `config.Write()` writes
```
[machine]
cpus = 0
disk_size = 0
memory = 0
```
to the user file. Because podman machine system connection add code will
do this the config file is broken afterwards. The first vm will be created
successfully but after this every other vm will be broken because the
cpu, memory and disk size are set to zero.
[1] https://github.com/BurntSushi/toml/pull/81
Fixes containers/podman#11824
> [v0.44] config: add omitzero for numeric types

- libimage/pull.go
Exchange two debug logs in the pull-never policy.  Those were probably
not moved along with the code and could lead to confusions when reading
debug logs.
> libimage: Pull: fix logs

- pkg/config/config.go
- pkg/config/config_test.go
Reduce the logs for unknown keys from Warn to Debug level.
The containers.conf continuously receives new keys, and some consumers
(e.g., Podman) are updating it at runtime.  Even small divergences in
the vendored versions of containers/common can let one tool run fine and
the other print warnings for each invocation.  Reducing the log-level to
debug works around that problem at the cost of honest typos not being
as easy to detect as before.
> containers.conf: unknown keys: reduce to Debug level

- libimage/filters.go
- libimage/image.go
With commit 86afb94e0054 the dangling checks have been changed to be
compatible with Docker.  Since then, the dangling also need to compute
children.
Speed up the dangling and intermediate checks by computing the layer
tree *once* instead of for each filter invocation.
**Before:**
real    0m10.837s
user    0m11.308s
sys     0m4.231s
**After:**
real    0m0.476s
user    0m0.478s
sys     0m0.151s
Context: github.com/containers/podman/issues/11997
> libimage: speed up image filters

- pkg/config/config.go
This change is based on discussion in containers/podman#11960.  I don't especially like the way the multi-sentence style clashes with other log messages, especially since this is typically encapsulated within a higher-level error, but couldn't think of a better way to convey the relevant information.  I'm open to suggestions on a better approach.
> Add a hint to resolve a misconfigured helper_binaries_dir

- libimage/image_test.go
- libimage/inspect.go
buildkit is setting the health check in the image's config while Docker
and Podman set it in the image's container config.  Hence, if the
container config's healthcheck is nil, have a look at the config.
Fixes: #containers/podman/issues/12226
> libimage: inspect: extract healthchecks from configs

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
This field determines whether CNI or netavark will be used to create container networks. Default presently set to "cni".
> Add network_backend field for switching to netavark

- libimage/manifests/manifests.go
When we're given an image reference to add to a manifest list, if we're setting the instance info's architecture using information from the image, set its variant field, too.  Likewise, if we're setting the OS using information from the image, set the OS version and features fields.
> libimage/manifests.list.Add(): pull variant info from configs

- pkg/config/config.go
When searching for helpers, check $CONTAINERS_HELPER_BINARY_DIR.
If it points at an existing directory, prepend it to the
search path for binaries.
Intention is to use this for developer testing: a way to run make
(e.g. in podman) then use the locally-built rootlessport and pause
images
Signed-off-by: Ed Santiago <santiago@redhat.com>
> FindHelperBinary(): allow override via envariable

- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/testdata/containers_default.conf
The Engine.Env needs to be set very early in the setup process
to make sure no one attempts to use the environment.
Fixes: https://github.com/containers/podman/issues/12296
> Set the environment variables for the engine

- pkg/config/config_local_test.go
- pkg/config/default.go
Context: containers/podman/issues/11712
> increase default machine vm size to 100GiB

- pkg/report/doc.go
- pkg/report/formatter.go
- pkg/report/formatter_test.go
- pkg/report/template.go
- pkg/report/template_test.go
* Add additional replacer for ('\', 'n') -> "\n"
* New type Formatter embeds Template and writer/tabwriter handling
* tabwriter.Init() is exposed to allow updating the tabwriter settings
Note: If template origin is OriginPodman or has "table" keyword prefix
output will be filtered through tabwriter. Otherwise, output will be
rendered using given writer.
Note: Once all podman commands have been updated a follow on PR will
remove the old report.Template and report.Writer code.
See https://github.com/containers/podman/issues/10974
> Refactor report package to be more compatible

- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Add an option to containers.conf as a knob to enforce short-name
resolution to Docker Hub in Podman's compatibility REST API.
By popular request, turn it on by default.
@rhatdan @mtrmac PTAL
> containers.conf: add option to enforce docker.io for compat API

- libimage/image.go
- libimage/pull_test.go
- libimage/runtime.go
Make sure to enforce the "latest" tag when looking up images in the
local storage.  Also make sure that digested short-names are subject
to the extended digest lookups.
Context: containers/podman/issues/11964
> libimage: enforce "latest" tag when looking up images

- go.mod
- go.sum
- pkg/manifests/manifests.go
- pkg/supplemented/supplemented_test.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/modules.txt
In image-spec 1.0.2, the MediaType field is now available in OCI manifest types, so set it.
> manifests: set MediaType in OCI indexes

- pkg/flag/flag.go
- pkg/flag/flag_test.go
- version/version.go
Backports for fixing https://github.com/containers/podman/issues/12410#issuecomment-981693440 plus version bumps.
Cc: @mheon
> Backport podman fix 11933

- pkg/config/config_test.go
- pkg/config/nosystemd.go
- pkg/config/systemd.go
Because `sdjournal` library just ignores directories which are not
accessible, `journald` log driver is set as the default for a user who
cannot access the journal. As a result, the user cannot see logs of
containers via `podman logs`.
This change verifies accessibility of journal directories without
the library.
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
> Check accessibility to journal without sdjournal library

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
support changing the default compression format in the containers.conf
config file.
> config: add CompressionFormat option

- libimage/filters.go
- libimage/filters_test.go
- libimage/image.go
The previously inherited behavior from Podman was matching too
aggressively.  Now, the filter matches the exact behavior of
Docker, simplifies the code and is tested directly in libimage.
Context: containers/podman#11905
> reference filter: match exact behavior of Docker

- go.mod
- go.sum
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/manifest.go
- vendor/github.com/containers/image/v5/manifest/manifest.go
- vendor/github.com/containers/image/v5/manifest/oci.go
- vendor/github.com/containers/image/v5/manifest/oci_index.go
- vendor/github.com/containers/image/v5/pkg/docker/config/config.go
- vendor/github.com/containers/image/v5/pkg/shortnames/shortnames.go
- vendor/github.com/containers/image/v5/types/types.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
This is an alternative to #757 <s>, depends on UNMERGED https://github.com/containers/image/pull/1373</s> .
Now that `GetCredentials` allows looking up namespaced credentials, use that instead of `GetCredentialsForRef`, which avoids the `docker.io/vendor`→`docker.io/library/vendor` normalization issue; use reference parsing only to validate the syntax.
Also refactor a bit of the argument length handling and `logout --all`.
See individual commit messages for details.
Warning: Only unit-tested, and the actual functionality does not have test coverage. I didn’t actually try this in practice.
> Fix login/logout for docker.io/vendor

- pkg/retry/retry.go
See https://github.com/containers/image/pull/1299 for full rationale. Completely untested for now.
> Don’t retry on errcode.ErrorCodeDenied

- .cirrus.yml
***Depends on:*** https://github.com/containers/common/pull/846
***BIG FAT NOTE:*** This VM setup is reusing the same GCP backend (project) as for the https://github.com/containers/BuildSourceImage repo.  Though the service account keys are separate, so I made notes in their respective descriptions indicating which is for which.
> Cirrus: Switch to VMs for CI

- libimage/filters.go
- libimage/filters_test.go
It turns out that FamiliarMatch is only useful for matching Docker Hub
but we should not limit it to that and match values against registry.
For instance, FamiliarMatch is *not* able to match a FQN reference
against a Docker Hub image.  I am convinced that we should *not* behave
as Docker does in this case.
This brings us back to the behavior prior to commit 721661d9c60a but
with a fixed matching algorithm.  The specified value will now be
matched against 1) the FQN 2) without domain 3) without domain and path.
If specified also a second time without digest/tag.
@rhatdan PTAL
> libimage: fix reference filters

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_windows.go
This PR adds a new platform driven user setting used by the draft PR containers/podman#12503
Additionally it modifies "image" to also have a platform driven default.
> Add image and repo defaults for podman machine

- Makefile
- libimage/filters.go
- libimage/runtime.go
- pkg/seccomp/errno_list.go
The same filters types should be disjoint, while
each selected filter type is required. This will allow callers to pass
multiple reference filters and if an image matches it is returned.
Other filters the image has to match all filters to be returned.
Specifying "since", "after", "before", "containers", "dangling","intermediate",  "readonly", "until" more then once is an error.
[NO NEW TESTS NEEDED] I will open up a validation against buildah to
make sure this passes before merging.
> Support matching filters disjoint filters

- pkg/cgroups/cgroups.go
on a busy system, the conmon process could take longer to complete or
to be reaped by the parent, leaving the cgroup busy.  If the rmdir
fails with EBUSY, try again up to 5 seconds before reporting an
error.
Closes: https://github.com/containers/podman/issues/11946
> cgroup: retry rmdir up to 5 seconds on EBUSY

- pkg/cgroups/cgroups.go
- pkg/cgroups/cgroups_supported.go
- pkg/cgroups/cgroups_unsupported.go
Basically Windows build is failing when hitting unix contants in
cgroups.
[NO NEW TESTS ADDED] Just shifting code around.
Added build-cross to cirrus tests, which looks like it was not being
run.
> Fix build failure on Podman vendor

- pkg/cgroups/pids.go
add the same check we already have for other controllers, since
`createCgroupDirectory` is meant to be used on cgroup v1 only.
Closes: https://github.com/containers/common/issues/862
> cgroups: do not create $ROOT/pids on cgroupv2

- pkg/cgroups/cgroups.go
- pkg/cgroups/memory.go
`podman stats` show the `usage` memory is wrong.
it shows container memory usage is `12GB` while it only uses `1.5GB`.
because it contains network traffic.
podman related PR:  https://github.com/containers/podman/pull/12703
related podman issue:  https://github.com/containers/podman/issues/12702
> fix: fixup memory usage for cgroup v2

- libnetwork/cni/cni_suite_test.go
- libnetwork/cni/network.go
- libnetwork/netavark/ipam_test.go
- libnetwork/netavark/netavark_suite_test.go
- libnetwork/netavark/network.go
- libnetwork/netavark/run_test.go
- libnetwork/network/interface.go
- libnetwork/types/const.go
- libnetwork/types/network.go
- libnetwork/types/network_test.go
- pkg/config/default.go
When the network backend is unset in the config we have to to figure out
if we need CNI or netavark. New installs should use netavark while
existing installs should continue to use CNI to prevent breaking
systems.
We use the following conditions to determine what backend to use:
1. read ${graphroot}/defaultNetworkBackend
2. find netavark binary (if not installed use CNI)
3. check containers, images and CNI networks and if there are some
we have an existing install and should continue to use CNI
> libnetwork: add function to get the default network backend 

- libnetwork/cni/network.go
- libnetwork/netavark/network.go
- libnetwork/types/network.go
While we can store the default network name outside this network
interface it can become out of sync with the interface.
In buildah it can be useful to get the name from the interface.
> libnetwork: add method to get the default network name

- libnetwork/network/interface.go
It is possible that two processes write at the same time and this could
lead to an invalid value in the file.
I think this fixes a race condition which was observed in the buildah
integration tests.
> libnetwork: use atomic write for the backend file

- libimage/image_test.go
- libimage/runtime.go
When looking up an image by digest, make sure that the matching image is
also subject to further attribute checks (e.g., manifest list checks) as
specified by the user.
Fixes: containers/podman/issues/12729
> image lookup: apply checks for matching digest

- libimage/pull.go
- libimage/pull_test.go
- libimage/runtime_test.go
When pulling down an image with a user-specified custom platform, we
try to make sure that user gets what they are asking for.  An inherent
issue with multi-arch images is that there are many images in the wild
which do not get the platform right (see containers/podman/issues/10682).
That means we need to pessimistically assume that the local image is
wrong and pull the "correct" one down from the registry; in the worst case
that is redundant work but we have a guarantee of correctness.
Motivated by containers/podman/issues/12707 I had another look at the
code and found some space for optimizations.  Previously, we enforced
the pull policy to "always" but that may be too aggressive since we may
be running in an airgapped environment and the local image is correct.
With this change, we …
> libimage: refine pull-policy enforcement for custom platforms

- libnetwork/internal/util/validate.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
libnetwork: only validate static ip when ipam is host-local
If the dhcp ipam driver is used podman does not know any subnets so we
cannot verify if the given static ip is in the subnet.
Fixes containers/podman#12762
libnetwork: netavark allow mtu option for macvlan
We have to support the mtu option for netavark since it is also
supported by CNI.
> libnetwork: verify static ip only for host-local ipam and allow mtu option for netavark macvlan driver

- libimage/pull.go
- libimage/pull_test.go
After containers/podman/issues/10682, we decided to always re-pull
images of non-local platforms and match *any* local image. Over time, we
refined this logic to not *always* pull the image but only if there is a
*newer* one. This has slightly changed the semantics and requires to
perform platform checks when looking up a local image. Otherwise, bogus
values would match a local image and mistakenly return it.
> libimage: pull: platform checks for non-local platform

- .cirrus.yml
Until widely used and pre-installed in the VM image, simply pull the latest build from the upstream netavark CI system.
> Cirrus: Make netavark binary available to unit tests

- docs/containers.conf.5.md
- libnetwork/network/interface.go
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Since the network namespace is shared for all rootful libpod instances
we also need to make sure to use the same network config dir and run dir
to ensure that we do not use the same subnet or ip for more than one
container.
Also update the documentation about the network_config_dir field.
add network documentation for netavark
* change cni networks to just networks since they also refer to netavark
networks
* add documentation about the network_backend key and what the empty
value means
> netavark: use globally shared network config dir

- pkg/parse/parse.go
- pkg/parse/parse_test.go
Relax ValidateVolumeOpts to support more verbose options for overlay
example `upperdir, workdir` and in future maybe `volatile`.
Needed for: https://github.com/containers/podman/pull/12712
> parse: extend `ValidateVolumeOpts` to support advanced `overlay` options

- libnetwork/netavark/network.go
- libnetwork/netavark/run.go
* Tells netavark if invocation is for `rootful` or `rootless`
containers.
* Pass `tmpfs` based runRoot to netavark so it can write/read configs
from there.
Needed by: containers/netavark#168
> libnetwork: support `rootless` network with netavark and relay `runRoot` with `tmpfs`

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
- pkg/config/default_windows.go
- pkg/config/testdata/containers_default.conf
This field was only needed for machine to force cni, however you can set
netns="bridge" in the config to have the same effect. This is already
done in the machine setup.
The field was more of a hack and just creates confusion for users so we
remove it.
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> remove rootless_networking field from containers.conf

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
When we create a macvlan network we should not check if the subnet is
already in use on the host since this is expected for macvlan networks.
Only bridge networks should use this check.
Fixes containers/podman#12971
> libnetwork fix subnet validation for macvlan

- libnetwork/netavark/exec.go
- libnetwork/netavark/network.go
- libnetwork/netavark/run.go
- libnetwork/network/interface.go
We need to use the configured path from containers.conf for the
aardvark-dns binary location.
> netavark: use aardvark-dns path from containers.conf

- go.mod
The v1.0.0 tag no longer exists, but the Go proxy still remembers it.
So, we see things like
```console
skopeo % go get -u ./...
go: downloading github.com/containers/image/v5 v5.19.1
github.com/containers/skopeo/cmd/skopeo imports
github.com/containers/common/pkg/auth: cannot find module providing package github.com/containers/common/pkg/auth
github.com/containers/skopeo/cmd/skopeo imports
github.com/containers/common/pkg/flag: cannot find module providing package github.com/containers/common/pkg/flag
github.com/containers/skopeo/cmd/skopeo imports
github.com/containers/common/pkg/report: cannot find module providing package github.com/containers/common/pkg/report
github.com/containers/skopeo/cmd/skopeo imports
github.com/containers/common/pkg/retry: cannot find module providing package …
```
> Retract the v1.0.0 version

- libimage/copier.go
- libimage/manifests/manifests.go
Add a `SourceFilter` hook that allows a caller to intercept and filter attempts to read source blobs when pushing a manifest list.
> Add libimage/manifests.PushOptions.SourceFilter

- pkg/auth/auth.go
The windows handle is not on fd 0 (it's -10), so portably access through os.Stdin instead.
Signed-off-by: Jason T. Greene <jason.greene@redhat.com>
> Fix console password reading on Windows

- libnetwork/cni/config.go
- libnetwork/internal/util/validate.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/network.go
netavark + aardvark support this when we add a gateway ip to the config
so that aardvark can use this address to bind on it.
We only add the gateway when not internal or when dns is enabled. If
internal without dns we do not need the gw address.
> netavark: add support for dns with internal

- libnetwork/cni/cni_conversion.go
- libnetwork/cni/config_test.go
Since a internal network has no connectivity to the outside we should
not add a default route. Also make sure to not add the default route
more than once for ipv4/ipv6.
Ref containers/podman#13153
> cni: do not add default route for internal networks

- pkg/parse/parse.go
allow to pass extra information for idmap down to the OCI runtime.
> parse: allow extra options for idmap

- docs/containers.conf.5.md
`volumes` were mistakenly listed under the network table.
Fixes: #928
> docs: move `volumes` under containers table

- docs/Containerfile.5.md
- docs/Makefile
- docs/containerignore.5.md
These where moved to buildah but because they are useful for podman and
the other tooling they are moved back into the common project.
Reverts fc7cb9cf92020cc2f58683bba693f70332a9dca3
Signed-off-by: Morten Linderud <morten@linderud.pw>
> docs: Reintroduce Containerfile and containerignore

- pkg/seccomp/seccomp_linux.go
- pkg/seccomp/types.go
crun supports seccomp filter flags since https://github.com/containers/crun/commit/fefabffa2816ea343068ed036a86944393db189a
runc will get them with https://github.com/opencontainers/runc/pull/3390
youki will get them with https://github.com/containers/youki/pull/733
To support them generally, we now copy the flags during the seccomp
setup, otherwise they will get lost.
> Add support for seccomp filter flags

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Working on issue [13222](https://github.com/containers/podman/issues/13222) to make the API `exec` calls configurable after how much time their processes are exited.
This MR adds this `ExitCommandDelay` configuration to `containers.conf`, adds it as field to `config.go` and sets a default of 5 minutes (as is the standard in Docker). 
Signed-off-by: Rover van der Noort <s.r.vandernoort@student.tudelft.nl>
> Add ExitCommandDelay in containers.conf and set var and default

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
netavark: macvlan allow internal networks
When internal is used the default route will not be added,
see https://github.com/containers/netavark/pull/246
cni: macvlan allow internal networks
When we have the host-local ipam plugin we can support internal for
macvlan networks. In this case we just do not add the default route.
Since we cannot control this for dhcp we do not support internal there.
Fixes https://github.com/containers/podman/issues/13319
> libnetwork: macvlan allow internal networks

- pkg/seccomp/seccomp_linux.go
- pkg/seccomp/types.go
We have to copy both fields in the same way we did with the flags to
support them in container runtimes.
> Add support for seccomp `ListenerPath` and `ListenerMetadata`

- pkg/config/default.go
Different packaging for different distributions have their own prefix for where helper binaries should live. additionalHelperBinariesDir is a variable that can be set during link-time so that a packager can change the location without having to carry patches for their default location.
I have no idea how to test this.
> Add additionalHelperBinariesDir

- pkg/util/util_supported.go
Do not require 0700 permissions for the runtime directory but accept
anything that is writeable by the user.
> util: fix GetRuntimeDir permission check

- libnetwork/netavark/run.go
- libnetwork/network/interface.go
Use appropriate variable when producing warning for missing
aardvark-dns. Current output variable will always be empty when
aarvark-dns is missing.
Second commit overrides the first one:
Move generic warning to netavark/run and warns user if one or more
network has `DNSEnabled` and `aardvark-dns` binary is not set
Closes: https://github.com/containers/podman/issues/13412
> libnetwork: warn only if network has `DNSEnabled` and `aardvark-dns` binary is not there.

- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
- pkg/config/default_windows.go
We cannot use /var/tmp on windows, instead use the temp var which is
defined on windows, of fall back to appdata.
Fixes containers/podman#13434
> Fix ImageCopyTmpDir for windows

- libimage/filters.go
- libimage/image.go
- version/version.go
Changelog:
* bump to v0.44.6-dev
* v0.44.5
* libimage: speed up image filters
Backporting fixes for https://github.com/containers/podman/issues/11997
@containers/podman-maintainers @rhatdan PTAL
> backports for v0.44 (Podman v3.4) and cut v0.44.5

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/apparmor/internal/supported/supported.go
Previously, Podman would print an error if you tried to run a container
with an AppArmor profile as a non-root user, e.g.
$ podman run --security-opt apparmor=my-profile ...
Error: Apparmor profile "my-profile" specified, but Apparmor is not
enabled on this system
In fact, the only thing that Podman needs root privileges for is reading
/sys/kernel/security/apparmor/profiles to see if the profile is already
loaded, which isn't strictly necessary.
This commit removes the 'IsLoaded()' check that occurs when you try to
specify an AppArmor profile as a non-root user, as well as the other
checks in pkg/apparmor/ for whether the program is running as UID 0. The
check for whether the AppArmor profile is loaded should now be deferred
to the container runtime at the point where it writes to either …
> Allow rootless containers to use AppArmor profiles

- libnetwork/netavark/config.go
If we have to write a new configuration file, close the file handle when we finish writing to it, instead of just letting it pass out of scope.
> libnetwork/netavark.netavarkNetwork.networkCreate(): close the file

- libimage/remove_test.go
- libimage/runtime.go
Add a field to `RemoveImages` that would ingore if a specified image
does not exist and not throw an error.
The intended use case is adding a `podman rmi --ignore` flag.
> libimage: RemoveImages: add Ignore field

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/apparmor/internal/supported/supported.go
This reverts commit 55d217f7dd9ef4721cf32b32d0d8b8b029e877b3 since
it does not pass Podman CI (i.e., the rootless Ubuntu job fails).
@kernelmethod, we need to (temporarily) revert your previous changes as they are not passing Podman's CI.
> Revert "Allow rootless containers to use AppArmor profiles"

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
Also sort all syscalls in alphabetic order.
Fixes: https://github.com/containers/buildah/issues/3833
> Add ptrace as a default seccomp allow to match Docker

- libimage/filters.go
- libimage/filters_test.go
This PR closes [this issue](https://github.com/containers/podman/issues/13270#issuecomment-1063000849), which adds a negation option to all filters for the `podman images --filter` command. I tested this locally by building an image with a label of `version:0.1` and running `bin/podman images --filter 'label=version=0.1'` gives me only this image listed and running `bin/podman images --filter 'label!=version=0.1'` gives me all other images listed. I also tested the other filter options, and they all have the same effect!
Signed-off-by: rvandernoort <s.r.vandernoort@student.tudelft.nl>
> Add negation to filters

- pkg/config/config.go
Number types must use omitzero otherwise they are included in the toml
file when it is written and the value is 0, see commit 2f22f3dec91d.
> pkg/config: events_logfile_max_size add omitzero

- libimage/import.go
[Image-spec](https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/config.go#L93) already supports variant and if `ImportOptions` contains
any configured `Variant` it should be set on the imported image as well.
What does this fix:
Allows `podman import --variant <something> some.tar image-name` to
become functional from `no-op`
Ref: https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/config.go#L93
> libimage: import should not ignore configured `variant` in `ImportOptions`

- pkg/config/config_test.go
When we write a default(empty) config it should only add the default
stanza fields but never any actual config values.
This is important see commit 2f22f3dec91d for the reasons.
> config.Write(): test for empty writes

- .cirrus.yml
- pkg/secrets/passdriver/passdriver.go
- pkg/secrets/passdriver/passdriver_test.go
GPG has a homedir option that allows for placing the gpg keys in
different locations. This is especially useful for testing, where we can
create a GPG key in a tmp dir, without worrying about it affecting other
keys the user may have.
Fixes passdriver tests too.
Fixes: #750
> Add homedir option to passdriver

- pkg/config/config.go
Eliminating all of the stat calls should make this a bit faster.
> Switch all calls to filepath.Walk to filepath.WalkDir

- libnetwork/cni/cni_conversion.go
- libnetwork/cni/cni_types.go
- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/cni/run.go
- libnetwork/cni/run_test.go
- libnetwork/internal/util/bridge.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/ipam_test.go
- libnetwork/netavark/run_test.go
- libnetwork/types/const.go
Network create now uses the ipam driver. This allows the user to
configure the ipam driver manually instead of choosing a fixed default.
If the ipam driver is `none` no ips will be assigned to this container.
This means that only the interfaces are created.
This will require a patch in netavark since it rejects the config when
no static ips are provided.
Ref https://github.com/containers/podman/issues/13521
> libnetwork: allow new none ipam driver

- .codespellrc
- .github/workflows/validate.yml
- Makefile
- docs/containers.conf.5.md
- libimage/import.go
- libnetwork/netavark/config.go
- libnetwork/netavark/network.go
- pkg/report/camelcase/README.md
Apparently we do have codespell target in Makefile, but it is not used by any CI.
Fix all issues found by codespell, and create a small GHA CI job to run it for all PRs, branches and tags.
> CI: add codespell job to GHA

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/cni/run_test.go
- libnetwork/internal/util/create.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/run_test.go
When we create a network with the ipam driver none we should disabled
dns automatically. Since we mange no ips we cannot provide name
resolution anyway.
This fixes a problem I spotted when adding test to the podman CI.
> libnetwork: ipam driver none disable dns

- .cirrus.yml
- Makefile
Quite a few changes, mostly removing old stuff though.
1. "GO111MODULE=off" is no longer required to be set by default (and
it used to be overridden below anyway).
2. "go build" no longer requires explicit "-mod=vendor", as this is the
default since go 1.14.
3. GOPROXY is set to proxy.golang.org by default since go 1.13.
4. Always use default GOPATH (which is $HOME/go since Go 1.8; earlier
releases needed to set it explicitly).
5. Drop the code that handles multiple comma-separated GOPATH elements
(when using modules, GOPATH is no longer used for resolving imports,
which basically means using multiple paths is useless).
6. Drop go-get macro (which is used to install md2man), use go install
directly (supported since Go 1.16). While at it, do not check if
go-md2man is available, install it …
> Makefile: simplify for modern Go

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/default_test.go
This will allow users to specify which volumes they want podman machine
to automatically mount into the machine. These volumes can later be used
to volume mount into containers.
Environment variables like $HOME can be used and are translated at the
time of machine start.
> Add machine volumes to containers.conf

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_override.conf
Changing the value for events_logfile_max_size from 0 to 1048576. This allows
up to 10,000 events to be written to the events log file before rotation occurs.
Also adding new values to default.go
Signed-off-by: Niall Crowe <nicrowe@redhat.com>
> pkg/config: new value for events_logfile_max_size

- docs/containers.conf.5.md
- libnetwork/etchosts/hosts.go
- libnetwork/etchosts/hosts_test.go
- libnetwork/etchosts/ip.go
- libnetwork/etchosts/util.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Add a new libnetwork/etchosts package to manage reading/writing hosts files.
This package exports two functions New() and Add(). See the godoc comments
on the functions.
Both podman and buildah should use this function to make sure files are
generated identical.
libnetwork/util: add GetNetworkIPs()
Add helper function to get the first ipv4 and ipv6 from the network
status. Since this is stored as a map, calling this function multiple
times is not deterministic. The caller (Podman) should store this result
to make sure it will keep using the same ips.
add base_hosts_file field to containers.conf
base_hosts_file can be used to overwrite the default base host file
/etc/hosts which is used to copy hosts entries from this file into the
containers /etc/hosts file. As special value "image" can …
> add new etchosts package

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
Slirp4netns options were changed to always default to ipv6 so it does
not need the extra setting. Update the documentation to reflect this.
see https://github.com/containers/podman/pull/13929
> pkg/config: fix docs for network_cmd_options

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/pod_exit_policy.go
- pkg/config/pod_exit_policy_test.go
- pkg/config/testdata/containers_override.conf
Add a new `pod_exit_policy` field to the containers.conf's engine table.
A pod's exit policy determines the behaviour when the last container of
a pod exits.
Required-in: containers/podman/pull/13859
@Luap99 @mheon @rhatdan PTAL
> containers.conf: add pod_exit_policy

- pkg/cgroups/cgroups_supported.go
if the cgroup cleanup fails with EBUSY, attempt to kill the
processes.
Related to: https://github.com/containers/podman/issues/14057
> cgroups: kill processes when deleting a cgroup

- libimage/runtime.go
- libimage/runtime_test.go
- libimage/testdata/containers.conf
if image_copy_tmp_dir is set in containers.conf it needs to be used in
the systemcontext for BigFilesTemporaryDir value.
Fixes: https://github.com/containers/podman/issues/14091
> libimage should be using containers.conf for tmpdir

- .golangci.yml
- libimage/load.go
- libimage/runtime.go
- libnetwork/cni/config.go
- libnetwork/cni/run.go
- libnetwork/etchosts/hosts_test.go
- libnetwork/internal/util/create.go
- libnetwork/netavark/config.go
- libnetwork/network/interface.go
- pkg/apparmor/apparmor_linux.go
- pkg/auth/auth.go
- pkg/config/config.go
- pkg/configmaps/configmaps.go
- pkg/configmaps/configmapsdb.go
- pkg/configmaps/filedriver/filedriver.go
- pkg/filters/filters.go
- pkg/machine/machine.go
- pkg/retry/retry.go
- pkg/seccomp/filter.go
- pkg/secrets/filedriver/filedriver.go
- pkg/secrets/secrets.go
- pkg/secrets/secretsdb.go
- pkg/sysinfo/nummem_linux.go
unparam and exportloopref already work without changes.
For revive I had to silence many naming issues. I decided to silence them
instead of changing the name because I didn't want to break any code.
> enable unparam, exportloopref and revive linters

- Makefile
The cgo-enabled builds require Linux include files and libraries.
This change makes it possible to build the non-cgo versions on
non-Linux platforms.
> Only attempt CGO_ENABLED builds on Linux

- docs/containers.conf.5.md
We have received two Bugzilla's about the upstream
documentation being incorrect about the default value of the
events_logger field in containers.conf.  The are:
https://bugzilla.redhat.com/show_bug.cgi?id=2076664
https://bugzilla.redhat.com/show_bug.cgi?id=2076665
From what I can see, we use `file` in RHEL and the podman machine,
in all other distributions were' using journald.  I've
attempted to change the man page to reflect that.
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>
> Define default loggers in man page

- .github/workflows/validate.yml
- .golangci-extra.yml
The idea here is to run some more picky linters only on new code,
so we can keep the existing code as is, but impose some additional
requirements to any new code.
Currently, this enables godot linter which wants all comments to have a
period at the end of the sentence. This makes sense because otherwise
some comments might be read as unfinished.
Obviously, no one wants to fix all the existing comments to have
periods, but this will impose such requirement onto any new code
(which also includes the code that is moved around).
Hope that makes sense.
> CI: enable extra linters for new code

- .cirrus.yml
This is now performed by github actions (see commit
05a2076120acd2c8c0, PR #997), so there's no need to perform this twice.
> cirrus-ci: rm make validate

- pkg/completion/command.go
Add the completion command to pkg/completion, this would allow podman,
buildah and skopeo to use the same command instead of having to
duplicate the logic.
The code is mostly copied from podman/cmd/podman/completion. I have
modified it a little to make it more generic.
> pkg/completion: add common completion command

- libimage/load.go
- libimage/load_test.go
- libimage/pull.go
Close the reader of an Docker archive to make sure that artifacts in
TMPDIR are removed.
Closes: github.com/containers/podman/issues/14287
> libimage: load: close reader

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/pull_policy.go
- pkg/config/testdata/containers_default.conf
Begins to fix https://github.com/containers/podman/issues/14230
> Support setting image_volume_mode in containers.conf

- libimage/define/search.go
- libimage/search.go
To have tools using libimage be able to auto-complete the search filters
on the CLI, move the consts and vars to a new `libimage/define` package.
The new package prevents pulling in all the low-levels libraries.
> libimage/define: add search filters

- libnetwork/resolvconf/resolv.go
- libnetwork/resolvconf/resolv_test.go
- libnetwork/resolvconf/resolvconf.go
both buildah and podman currently use a slightly different resolvconf lib,
to prevent duplication and having to fix bugs twice they should both use
this new package instead.
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> libnetwork: add new resolvconf package

- libimage/inspect.go
- libimage/manifests/manifests_test.go
- libimage/pull.go
Please refer to the individual commits. No real changes needed.
The remaining FIXME requires https://github.com/containers/storage/issues/999 to be done but I think there are more important items for now.
@flouthoc @rhatdan PTAL
> libimage: address a number of TODOs

- .github/workflows/validate.yml
This corresponds to similar changes made in Buildah, Podman, and Skopeo: https://github.com/containers/podman/pull/13564 https://github.com/containers/buildah/pull/3872 https://github.com/containers/skopeo/pull/1652
+ Pin actions to a full length commit SHA is currently the only way
to use an action as an immutable release. Pinning to a particular SHA
helps mitigate the risk of a bad actor adding a backdoor to the action's
repository, as they would need to generate a SHA-1 collision for a valid
Git object payload. Ref:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
+ Explicitly set permissions for actions to minimum required.  The
defaults are (unfortunately) overly permissive: Ref: …
> [CI:DOCS] Pin actions to a full length commit SHA

- .cirrus.yml
Update CI VM Image to Fedora 36 w/ built-in netavark and aardvark-dns.
Ref: https://github.com/containers/automation_images/pull/134
> F36 update

- libimage/platform.go
- libimage/runtime.go
Do not check the platform of an image when it was looked up by it's ID.
In that case we must assume that the user/tool knows what they are
doing.
Further make the warnings configurable via a new `PlatformPolicy` field
in the `ImageLookupOptions`.  By default, the error will only be printed
on the debug logs.  User can opt-in to display the error on the warning
level.  Not all code paths should warn.  For instance, when inspecting
an image.  This way, consumers of libimage can opt-in.  The policy can
later on be extended to error out instead of logging.
> libimage: tweak platform checks

- go.mod
- go.sum
- pkg/cgroups/blkio_linux.go
- pkg/cgroups/cgroups_linux.go
- pkg/cgroups/cgroups_linux_test.go
- pkg/cgroups/cpu_linux.go
- pkg/cgroups/systemd_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
- vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
- vendor/github.com/seccomp/libseccomp-golang/README.md
- vendor/github.com/seccomp/libseccomp-golang/SECURITY.md
- vendor/github.com/seccomp/libseccomp-golang/seccomp.go
- vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
- vendor/modules.txt
in the first PR for improving cgroup creation, systemd was not included. This change is as simple as including a resource parameter in the `NewSystemd` function and leaving the creation
in podman to do the rest. Also, a new function has been added to convert spec.Linux limits into systemd properties
Signed-off-by: cdoern <cdoern@redhat.com>
> improve NewSystemd's capability for setting resources

- pkg/cgroups/cgroups_linux_test.go
- pkg/cgroups/systemd_linux.go
systemd truncates the given cpu quota value from us / cpu second to s / cpu second meaning
we need to mimic runc's logic here and change our value based on this internal truncation.
> cpu quota patch

- pkg/parse/parse.go
it is needed for supporting -v volume:/to:nocopy.
> parse: support copy and nocopy

- libimage/normalize.go
- libimage/platform.go
- libimage/platform_test.go
- libimage/pull.go
- libimage/runtime.go
Use containerd's platform package for platform checks. While the OCI
image spec requires the platform values to conform with GOOS and GOARCH
definitions of Go' runtime package, the values of uname are used by
convention.  Supporting these values silences annoying false-positive
warnings.
Fixes: #containers/podman/issues/14669
@rhatdan @Luap99 PTAL
> libimage: normalize platforms correctly

- pkg/cgroups/cgroups_linux_test.go
- pkg/cgroups/systemd_linux.go
upon trying to implement --memory for podman pod create, I realized that all memory limits in bytes
need to be uint64 not int64. Switched the type and added a test for ALL "implemented" fields to check that they work
> type conversion for systemd memory limits and additonal tests

- pkg/cgroups/cgroups_linux_test.go
- pkg/cgroups/systemd_linux.go
added some tests for more resource limits and put translation of cpu-weight in there. Podman and runc both only use cpu-shares but systemd has replaced CPUShares with CPUWeight in more recent versions, they are the same thing it seems.
> additional cgroup testing, implementation of cpu-shares, and introduction of blkio limits.

- docs/containers.conf.5.md
- libnetwork/netavark/exec.go
- libnetwork/netavark/network.go
- libnetwork/network/interface.go
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
companion PR for containers/netavark#323 
I've:
- added `dns_bind_port` setting to structs, example config and manual page
Note the default in go is 0, which means do not set the env var. Someone setting it to 53 explicitly in the config would set the variable if we ever change the default.
- added a test to validate we parse it; I've tested manually that invalid config value errors out but we don't have any value by value invalid parsing check (setting the value to an int < 0 or > 65535 would fail on Validate(), sure, but I don't see the point and it doesn't allow validating things like `dns_bind_port = yes` or other nonsensical value)
- I've taken the liberty to fix a typo where Default was spelled Defult
- likewise, tests didn't pass on my machine because /usr/libexec/foo doesn't …
> add netavark dns port option

- libimage/manifest_list.go
`podman manifest add` uses `ManifestList.Add(` but as of now `Add(` does
not locks while adding instances to the list thus causing race scenarios
where storage is not reloaded and overridden by another invocation of the
command.
Following problem is solved in two steps
* Add -> LockByID: Acquire a fs lock by instance ID so other
invocation waits until this invocation completes its write.
* Add -> LockByID -> reload: Reload instance digests from storage
just after acquiring lock to make sure we are not overriding any just
written instance.
Reproducer: https://github.com/containers/podman/issues/14667#issue-1277034660
Closes: **BZ#2105173**
Closes: https://github.com/containers/podman/issues/14667
This needs integration tests so its hard to verify …
> libimage, ManifestList: `fslock` and `reload` to provide race-free `Add` API

- libimage/filters.go
- libnetwork/util/filters.go
- libnetwork/util/filters_test.go
- pkg/filters/filters.go
there was some eerily similar code in c/common and in podman for
creating filter functions for various types. Move some of it here
and add support for the label!= filter in libimage and libnetwork that basically creates the inverse
function of label=
after this merges, will file a PR with the fix for containers within podman as well
there is already a label!= test in libimage/filters_test. Libimage somehow lets this syntax slide
even though it does not actually imact anything in podman
see containers/podman#14182
> move prune filter parsing to common

- pkg/cgroups/systemd_linux.go
I only included the v1 name for a cgroup wide IO weight in my previous PR, this fixes the --blkio-weight
flag in containers/podman#14876
> cgroup v2 support for IOWeight

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
support setting the metadata of the secret so that kube secrets can be marked as immutable
> add support for metadata in Store()

- libimage/manifest_list.go
- libimage/manifest_list_test.go
ManifestInspect should contain all known formats for a valid manifest
list as of now only supported formats are `OCIv1` and `Docker` so
inspect should support fields from `OCIv1` format as well. Following
commit adds a new field to inspect i.e `Annotations` from `OCIv1`.
Example output from podman
```console
podman manifest inspect test
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 528,
"digest": "sha256:9b2a28eb47540823042a2ba401386845089bb7b62a9637d55816132c4c3c36eb",
"platform": {
"architecture": "amd64",
"os": "linux"
},
"annotations": {
"annotationTest1": "annotationTest2"
}
}
]
}
```
Closes: https://github.com/containers/podman/issues/15069
> manifest_list: `inspect` add fields from both `OCIv1` and `docker` format

- version/version.go
@vrothberg @rhatdan @TomSweeneyRedHat RFC. @flouthoc FYI
For https://github.com/containers/podman/pull/15108 to land in Podman 4.2 (if that is an option at all), we need #1106 .
That, in turn, probably means making another c/common release (and vendoring it in Buildah first; and making another Skopeo release).
Do we want to do that?
---
If we do want to do it, should the new release be v0.50.0? There have been new APIs added since 0.49.0. Or is the branching driven primarily by Podman releases?
> RFC: tag v0.49.1

- libimage/image.go
- libimage/runtime.go
containers/common changes for podman rmi --no-prune flag.
--no-prune does not delete dangling parent images.
For compatibility with Docker
Signed-off-by: Karthik Elango <kelango@redhat.com>
> Podman rmi --no-prune flag

- libimage/image.go
Trying to remove an image that is in use by containers is a confusing
experience for users who may not be aware of "external" containers which
are not displayed in `podman ps` by default (see containers/podman/issues/15006).
Add some context to the error from containers/storage to guide the user
into listing external containers and force-removing the image.
> libimage: image removal: add hint to external containers

- .cirrus.yml
Getting CI to pass got frustratingly slow (>40 minutes).
A first step to make it faster is to bump the number of
CPUs and increase RAM to the same Podman CI is using.
> cirrus: bump cpus and ram

- pkg/config/config.go
- pkg/config/default.go
Adds the conmon-rs paths so Podman can find the right conmon-rs binary
when making a new runtime.
Signed-off-by: Jake Correnti <jcorrenti13@gmail.com>
> Add conmon-rs paths

- .github/workflows/validate.yml
Attempt at a fix or more information for #1118
> GHA: Use golang 1.18 + run in verbose mode

- libnetwork/cni/network.go
- libnetwork/network/interface.go
When the configuration directory is on a read-only filesystem, there's no risk of concurrency issues as there's no possibility of changing anything. As such, while it prevents the use of our default lock location, it also removes any need for a lock at all.
Making the lock entirely optional is a lot of code, so instead of doing that let's just put it in our temporary files directory, where it can't hurt anything.
> Use an alternative CNI lock for read-only config dirs

- libimage/inspect.go
[NO NEW TEST NEEDED]
Fixes: https://github.com/containers/podman/issues/15265
> Eliminate segfault when image does not have config

- pkg/config/default.go
- pkg/config/default_darwin.go
- pkg/config/default_freebsd.go
- pkg/config/default_linux.go
- pkg/config/default_windows.go
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
Fixes #1124 
Windows path values are unsafe to use with unix like environments, so, just replace with empty safe default.
> Adjust default volumes for windows compatibility

- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Add a new config knob for setting a default timeout for volume plugins. Just adds a field to containers.conf, real work will be in Libpod to wire it in.
> Add volume plugin timeout to containers.conf

- pkg/config/config.go
- pkg/config/config_darwin.go
This should make it easier to locate helper binaries relative to where the main binary was installed, which should be useful in installations such as Homebrew which install packages under a versioned directory.
Use a `$BINDIR` magic token as a prefix in the helper path to indicate it should be relative to the directory where the binary is located. This is somewhat familiar to the syntax used in the shell and Makefile and is still quite explicit about the behavior (as opposed to, say, making all relative paths be relative to the directory of the binary.)
Update `podman` config on Darwin to look for helpers such as `gvproxy` under `$BINDIR/../libexec/podman`, which is the ultimate objective of this code change.
Tested: Updated vendored package in podman, built it with `podman-remote`, …
> config: Allow specifying helper dirs with $BINDIR as base directory

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_override.conf
Allow distributions to specify the location of the podman image VM
images in the form of URIs with $ARCH and $OS specified.  This would
allow a distribution to pull the image based on the current OS and Arch.
> Add support for returning image path with ARCH and OS Substitutions
