pkg/config/config_unsupported.go

Add unsupported file for non linux.

add selinux unsupported

---

pkg/config/config_test.go

tests failures should be fixed since #11 add hooksdir to default config.

Fix tests failure #11

---

pkg/config/config.go
pkg/config/config_suite_test.go
pkg/config/config_test.go

Remove the validation of the hooks directory because this will cause CI failure.
Clean up the code I got from cri-o has not been used.

turn off the check of the hooks directory

---

pkg/unshare/unshare.go

@giuseppe @QiWang19 @rhatdan PTAL

unshare.HomeDir: get home dir of current user

---

docs/containers.config.5.md
pkg/config/config.go

Add support for CONTAINERS_CONF environment variable

---

pkg/config/default.go
pkg/config/default_linux.go
pkg/config/default_unsupported.go

Fix definitions for cross compilers

---

.travis.yml
Makefile

Needs https://github.com/containers/common/pull/53

Add 32bit build to travis

---

pkg/config/config.go

Directories should allow for empty paths

---

Makefile
pkg/config/default_linux.go

 Fix compiling on 32 bit machines 

---

docs/containers.conf.5.md
pkg/capabilities/capabilities.go
pkg/capabilities/capabilities_test.go
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go

Add kata containers support

---

SECURITY.md

After the original was merged, a few review
updates came in on the google doc.  This addresses
those updates.
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Update security policy per review comments

---

SECURITY.md

Tweak the title slightly of the Security Policy.
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Touch up Security title

---

pkg/config/config.go

These indicate that the user has modified the settings.

Do not set StaticDirSet, TmpDirSet,VolumePathSet

---

pkg/config/default.go

return Containers.PidsLimit iff rootless and cgroupmanager==systemd

---

Makefile
pkg/config/config.go
pkg/config/config_local.go
pkg/config/config_local_test.go
pkg/config/config_remote.go
pkg/config/config_remote_test.go
pkg/config/config_test.go
pkg/config/default.go

Add support for Remote flags in containers.conf

---

pkg/auth/auth.go

logout suggests logout with docker if credential exists in ~/.docker/config,json
close https://github.com/containers/libpod/issues/6499

logout suggests logout with docker

---

pkg/config/config.go
pkg/config/config_local_test.go

Add ability to read and write a default config file

---

docs/containers.conf.5.md
pkg/config/containers.conf

Fixup handling of remote_uri for documentation

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/containers.conf
pkg/config/testdata/containers_default.conf

Specify that the container engines are Podman, Buildah

Specify container engine in comments of engine env

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_local.go
pkg/config/config_local_test.go
pkg/config/config_remote.go
pkg/config/containers.conf
pkg/config/default.go

Add support for timezone

---

version/version.go

Bump to v0.15.0

---

version/version.go

Bump to v0.15.1

---

version/version.go

Bump to v0.15.2

---

version/version.go

Bump to v0.14.4

---

pkg/config/config.go

Fix the config reload race following the comments #219.

Fix config reload race

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_local.go
pkg/config/config_local_test.go
pkg/config/config_remote.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_default.conf

Add support for Umask

---

version/version.go

Bump to v0.16.0

---

pkg/config/config.go

Remove extra lock in Reload function

---

version/version.go

Bump to v0.17.0

---

version/version.go

Bump to v0.17.1

---

version/version.go

Bump to V0.14.6

---

version/version.go

Bump to v0.18.0

---

docs/containers.conf.5.md
pkg/config/containers.conf

Fix a bunch of formatting nits for consistency's sake
Newlines so it is readable on github

Fix documentation

---

pkg/auth/auth.go

Fix duplicated code found by codeverity.

---

version/version.go

Bump to v0.19.0

---

pkg/config/config_local.go

Some distributions have their zone information not in
`/usr/share/zoneinfo` but in `/etc/zoneinfo`. We now allow the package
to work on those distributions as well by looking in both paths for the
timezone data.

Support different zoneinfo locations

---

version/version.go

Bump to v0.20.0

---

version/version.go

Bump to v0.20.1

---

pkg/config/default.go

  Fix CONTAINER_STORAGE_CONF->CONTAINERS_STORAGE_CONF 

---

version/version.go

Bump to v0.20.2

---

version/version.go

Bump to v0.20.3

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_local_test.go
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_comment.conf
pkg/config/testdata/containers_default.conf
pkg/config/testdata/containers_invalid.conf

Fixes to support connections.

---

.golangci.yml
pkg/apparmor/apparmor_linux.go
pkg/auth/auth.go
pkg/config/config.go
pkg/config/libpodConfig.go
pkg/sysinfo/sysinfo_linux.go

This enables the missing gocritic checks and fixes all of the lints.

Fix all gocritic lints

---

pkg/retry/retry.go

Allow RetryIfNecessary()'s caller to specify the delay between retry attempts.  If the delay is not set, continue to default to 2 seconds for the first retry, doubling the delay for every subsequent attempt.

RetryIfNecessary: add a field for setting the delay in RetryOptions

---

pkg/config/config_windows.go
version/version.go

    fix windows containers.conf path

---

version/version.go

Bump to v0.21.0

---

version/version.go

Bump to v0.22.0

---

pkg/config/config.go
pkg/config/libpodConfig.go

Fix problems found by codespell

---

pkg/config/config.go
pkg/config/config_test.go

Add support for CONTAINER_CONNECTION environment variable

---

version/version.go

Bump to v0.23.0

---

pkg/completion/completion.go

Both podman and buildah can use these completion functions.
In order to prevent duplication lets define them here.
The new automplete functions are:
- AutocompleteSubuidName
- AutocompleteSubgidName
- AutocompleteCapabilities

Add shared autocomplete functions for podman/buildah

---

version/version.go

Bump to v0.24.0

---

version/version.go

Bump to v0.25.0

---

pkg/report/camelcase/LICENSE.md
pkg/report/camelcase/README.md
pkg/report/camelcase/camelcase.go
pkg/report/doc.go
pkg/report/template.go
pkg/report/template_test.go
pkg/report/validate.go
pkg/report/validate_test.go
pkg/report/writer.go
pkg/report/writer_test.go

Pulled code and tests from podman and buildah to be used across the containers stack.

Consolidate reporting functions

---

version/version.go

Bump to v0.26.0

---

version/version.go

Bump to v0.26.1

---

version/version.go

Bump to v0.26.2

---

pkg/report/template.go
pkg/report/template_test.go

Revert changes in 0.26.2 that broke podman

---

version/version.go

Bump to v0.26.3

---

version/version.go

Bump to v0.27.0

---

version/version.go

Bump to v0.28.0

---

pkg/subscriptions/subscriptions.go
version/version.go

Also add missing subscriptions directory.

Bump to v0.28.1

---

version/version.go

Bump to v0.29.0

---

docs/Makefile
docs/containers.conf.5.md
pkg/config/config.go
pkg/config/containers.conf

Also fixup some formatting issues in man pages.
Fix generation of multiple man pages.
Partial fix for: https://github.com/containers/podman/issues/7888

Add ability to set system wide options for slirp4netns

---

version/version.go

Bump to v0.30.0

---

pkg/config/containers.conf
pkg/config/default.go

Switch default runtime from runc to crun

---

version/version.go

Bump to v0.31.0

---

version/version.go

Bump to v0.31.1

---

pkg/seccomp/seccomp_unsupported.go
pkg/seccomp/supported.go
pkg/seccomp/supported_test.go

Currently this code is not building correctly on darwin builds.
This PR handles non linux platforms correctly.

Fix building on non linux platforms

---

version/version.go

Bump to v0.31.2

---

version/version.go

Bump to v0.32.0

---

version/version.go

Bump to v0.32.1

---

version/version.go

Bump to v0.33.0

---

version/version.go

Move the version to v0.34.0-dev for the main branch.
Any further work on v0.33 should happen on the v0.33 branch.

Move to v0.34.0-dev

---

pkg/secrets/secrets.go
pkg/secrets/secrets_test.go

Fix secret name regex to take one character secret names

Fix secret name regex

---

pkg/config/config.go

config: fix runtime_supports_nocgroup key name

---

Makefile
pkg/config/config.go
pkg/retry/retry.go
pkg/retry/retry_linux.go
pkg/retry/retry_unsupported.go
pkg/secrets/secrets.go
pkg/secrets/secrets_test.go
version/version.go

Back port a few fixes, Bump to v0.33.1

---

pkg/cgroupv2/cgroups_linux.go
pkg/cgroupv2/cgroups_unsupported.go

cgroupv2: fix typo in comment

---

pkg/config/util_supported.go

check whether the user owns the specified XDG_RUNTIME_DIR.  Hopefully
it will help catching errors when running in a "sudo -u" session that
uses the wrong value for XDG_RUNTIME_DIR.
Closes: https://github.com/containers/podman/issues/9114

pkg: check ownership for XDG_RUNTIME_DIR

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_override.conf

Change default log driver to journald

---

version/version.go

Bump to v0.34.0

---

version/version.go

Bump to v0.33.2

---

pkg/report/doc.go
pkg/report/template.go
pkg/report/template_test.go

Backport #426 to v0.29 for Podman 2.2.1

[v0.29] Backport: Add compatible template functions

---

version/version.go

Bump to v0.29.1

---

pkg/report/template.go
pkg/report/template_test.go
version/version.go

Bump to v0.33.4

---

version/version.go

Bump to v0.34.1

---

version/version.go

Bump to version v0.34.2

---

version/version.go

Bump to v0.35.0 

---

version/version.go

Bump to v0.35.1

---

pkg/auth/auth.go
version/version.go

Cherry-pick: v0.33  Stop logging messages about using DOCKER_CONFIG

---

version/version.go

Bump to v0.35.2

---

pkg/config/default.go

This patch updates the pause container image to the latest release.

Update pause image to 3.5

---

version/version.go

Bump to v0.35.4

---

pkg/filters/filters.go
pkg/filters/filters_test.go
pkg/timetype/timestamp.go
pkg/timetype/timestamp_test.go

Moved over from containers/podman.  A small step in the long journey to break
out a high-level image package.
@rhatdan PTAL

add pkg/{filters,timetype}

---

version/version.go

Bump to v0.36.0

---

version/version.go

Bump to v0.37.0

---

README.md

Highlighted and clickable the Contributing section
offtopic: Just a reminder Contributing section not noticeable
Signed-off-by: unknowndev233 <unknowndevQwQ@protonmail.com>

modify README.md: Contributing section finetuning

---

pkg/parse/parse_test.go

Fixes: https://github.com/containers/common/issues/462

Fix tests on lxd

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go

Based on https://github.com/containers/common/pull/507 PR.
Thanks to unknowndev233 unknowndevQwQ@protonmail.com whoever they are.

Add support for the runsc OCI Runtime

---

version/version.go

Bump to v0.37.1

---

Makefile
libimage/events.go
libimage/layer_tree.go
libimage/pull.go
libimage/push.go
libimage/save.go
pkg/config/config.go
pkg/config/containers.conf
pkg/filters/filters.go
pkg/secrets/filedriver/filedriver.go
pkg/secrets/secrets.go
pkg/secrets/secretsdb.go

[NO TESTS NEEDED] This is just code cleanup

Add support for codespell, and fix issues found

---

version/version.go

Bump to v0.38.0

---

version/version.go

Bump to v0.38.1

---

libimage/image.go

When comparing the digests of a local image and a remote image, we've been reading the manifest from the remote image using NewImage(), which may or may not return a list, and have been comparing the digest of that manifest to only one of the local image's manifests.
Start checking if the remote reference points to a manifest list, and if it is, find the image in the list that we'd choose to pull, and use its manifest digest for the comparison.
When looking up the digest of the local image to compare to the remote image, consider them to be the same image if any of the manifests in the image record has the same digest as the remote manifest, which is now known to not be a list.

libimage/Image.HasDifferentDigest: handle manifest lists

---

version/version.go

Bump to v0.38.2

---

version/version.go

Bump to v0.38.3

---

libimage/pull.go
libimage/runtime.go

Add some comments in the code that I found worth elaborating on while
rereading the code.

libimage: add some comments

---

pkg/defaultnet/default_network.go

This reverts commit 2452cebe646c2fe36a798d9a415d0eee956c88ab.
The default gateway should always be in the cni config to ensure it is
shown in podman network inspect and the compat api.
The reason why this did not worked was that the gateway was set to the
network address and not to the first ip in the subnet.

Include gateway in generated default networks

---

version/version.go

Bump to v0.39.0

---

OWNERS

add @Luap99 to OWNERS

---

pkg/secrets/passdriver/passdriver.go

This fixes the autodiscovery of options in the passdriver.
I was missing some strings.Trim() calls before, so gpg wouldn't recognize the gpg-id.
Additionally I added `.gpg` suffixes to the created files to be completely compatible with pass and gopass (with that you can now decrypt the secrets using normal pass/gopass tooling).
I tested this changes by building podman with a replace directive to point to my version of containers/common and it worked :) I was able to create a secret and then use it in a container. When starting the container it asked for my password to decrypt the secret and all went well.
```
> echo secret-value | ./bin/podman secret create --driver pass my-secret -
5111d3c7d95c9eb5547d50dfb
> ./bin/podman run --rm --secret my-secret alpine cat /run/secrets/my-secret …
```

fix autodiscovery of the secret passdriver.

---

libimage/corrupted_test.go
libimage/runtime.go
version/version.go

* libmage: Exists: catch corrupted images
* Plus another version bump

0.38 backports

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_test.go

Fixes: https://github.com/containers/common/issues/368

Add support for config drop in directories

---

version/version.go

Bump to v0.40.0

---

go.mod
go.sum
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Vendor in containers/image v5.13.2

---

version/version.go

Bump to v0.40.1

---

libimage/download.go
libimage/runtime.go
libimage/runtime_test.go
pkg/report/template.go
pkg/report/template_test.go

Final backports for Podman v3.2.2

Podman v3.2.2 backports

---

version/version.go

Bump to v0.41.0

---

version/version.go

Bump to v0.38.18

---

pkg/config/config.go

Signed-off-by: unknowndevQwQ@github <unknowndevQwQ@protonmail.com>

fix: fix #692

---

pkg/config/containers.conf

Finish the last unfinished part
close #693
Signed-off-by: unknowndevQwQ@github <unknowndevQwQ@protonmail.com>

style: complete containers#556 to-do list part 4

---

libimage/image.go
libimage/image_test.go

Make sure that tag and untag reject digested input.  Also add unit tests
for both to make sure we're not regressing in the future.
Fixes: #710

libimage: {un}tag: reject digests

---

docs/containers-containerfile.5.md
docs/containers-dockerfile.5

Add documentation for Containerfile and Dockerfile

---

version/version.go

Bump to v0.43.0

---

docs/containers-containerfile.5.md
libimage/image_test.go

[NO TESTS NEEDED] Just fixing spelling.

Add codespell fixes

---

pkg/config/containers.conf

Signed-off-by: unknowndevQwQ@github <unknowndevQwQ@protonmail.com>

style: fix commit 253bc38

---

pkg/config/containers.conf

#707 commit will be revert
this since was not tested and caused problem #723
> #693#issuecomment-891126410
but it does cause problems
Signed-off-by: unknowndevQwQ@github <unknowndevQwQ@protonmail.com>

fix: fix #723

---

version/version.go

Bump to v0.43.1

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_default.conf

add some possible paths for the cni plugin to be stored
Replaces: #728

add some cni plugin paths

---

version/version.go

Bump to v0.44.0 

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_default.conf

Make podman system service timeout configurable in containers.conf

---

docs/containers.conf.5.md

Add description of slirp options

---

version/version.go

Bump to v0.45.0

---

docs/containers.conf.5.md

Closes https://github.com/containers/common/issues/783.

containers.conf.5.md: simplify wording to avoit tautology

---

version/version.go

Bump to v0.46.0

---

libimage/load.go

Make sure to try loading the docker-archive first to account for the
"hybrid tarballs" created by buildkit.  docker-archive gets the name
right while oci-archive will not.
Fixes: containers/podman/issues/11619

libimage: load: try docker-archive first

---

pkg/parse/parse.go

needed by https://github.com/containers/podman/pull/12298

parse: accept idmap

---

pkg/config/config_local_test.go
pkg/config/config_test.go
pkg/config/default.go

Set netns to default to private like other namespaces

---

libimage/search.go

Add a new search option to specify custom search registries.
The search tests live in Podman and I currently do not have
enough cycles to add completely new ones to libimage.
@rhatdan @Luap99 @mtrmac PTAL

libimage: search custom registries

---

libimage/pull.go
libimage/pull_test.go

Fixes: https://github.com/containers/buildah/issues/3596

If we tell system to never pull we should not pull

---

.cirrus.yml

Also remove a useless script instruction.

Update to f35

---

libimage/filters.go

Further turn applying the filters into a method of `type Image`.
Also change the loop when filtering images to not append the
loop variable to the result slice; it's always the same pointer.
Fixes: containers/podman/issues/12582
@rhatdan @giuseppe @flouthoc PTAL

libimage: filter: check if image is corrupted in case of error

---

libimage/filters.go
libimage/filters_test.go

For compatibility mode, we need to have a filter that gets rid of
manifest lists from the list of all images.

Add filters for image and manifest

---

.cirrus.yml
Makefile

Make sure to test non linux builds

Run make build-cross in cirrus

---

libnetwork/netavark/exec.go
libnetwork/netavark/ipam.go
libnetwork/netavark/ipam_test.go

[NO NEW TEST NEEDED] Cross compile should be enough.

Fix darwin builds

---

pkg/config/config.go

This change makes a global rather then defining this list in multiple
places.

WEB Proxy is used in at least three different places in code

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/testdata/containers_override.conf

Document the events_logfile_path field in containers.conf

---

pkg/subscriptions/subscriptions.go

Revert "fix srcBackendDir to point to the right location"

---

version/version.go

Bump to v0.47.0

---

Makefile
libnetwork/netavark/network.go
pkg/config/config.go
pkg/flag/flag.go
pkg/secrets/shelldriver/shelldriver.go

Run codespell on code

---

pkg/subscriptions/subscriptions.go

in reviewing https://github.com/cri-o/cri-o/pull/5555 I found it difficult to process what these functions/variables did and why.
update the documentation to remind myself if I ever have to come back and remember again. (more details in commit messages)

Some documentation nits for FIPS and subscription functions

---

CODE-OF-CONDUCT.md

Change Libpod to Podman

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_comment.conf
pkg/config/testdata/containers_invalid.conf

Change infra_image default to ""

---

go.mod
go.sum
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt
version/version.go

Update vendor of containers/image and release new version of common.

---

version/version.go

Bump to v0.47.4

---

README.md

Signed-off-by: Rover van der Noort <s.r.vandernoort@student.tudelft.nl>
I was clicking through the repository when I noticed the link to podman was broken and some others had changed. I therefore updated the links to their newest address.

Update links of related projects in README

---

docs/Makefile
docs/links/.containerignore.5

[CI:DOCS] Add .containerignore.5 link file so users can find man page

---

OWNERS

OWNERS: add @kolyshkin

---

pkg/util/util_supported.go

Build this on freebsd as well as linux, darwin

---

pkg/config/config_freebsd.go

Add FreeBSD support for pkg/config

---

docs/containers.conf.5.md
libnetwork/netavark/network.go
pkg/config/containers.conf

[NO NEW TESTS NEEDED] Just a docs change.

Change rootfull->rootful

---

pkg/seccomp/conversion.go
pkg/seccomp/types.go

Add SCMP_ACT_NOTIFY to seccomp actions

Add SCMP_ACT_NOTIFY to seccomp actions

---

pkg/config/config.go
pkg/config/config_darwin.go
pkg/config/config_freebsd.go
pkg/config/config_linux.go
pkg/config/config_test.go
pkg/config/config_windows.go
pkg/config/containers.conf-freebsd
pkg/config/default.go
pkg/config/default_darwin.go
pkg/config/default_freebsd.go
pkg/config/default_linux.go
pkg/config/default_windows.go
pkg/parse/parse_unix.go

Config changes and pkg/parse fixes for FreeBSD

---

go.mod
go.sum
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/docker/docker_image_src.go
vendor/github.com/containers/image/v5/docker/lookaside.go
vendor/github.com/containers/image/v5/docker/paths_common.go
vendor/github.com/containers/image/v5/docker/paths_freebsd.go
vendor/github.com/containers/image/v5/pkg/sysregistriesv2/paths_common.go
vendor/github.com/containers/image/v5/pkg/sysregistriesv2/paths_freebsd.go
vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go
vendor/github.com/containers/image/v5/signature/policy_config.go
vendor/github.com/containers/image/v5/signature/policy_paths_common.go
vendor/github.com/containers/image/v5/signature/policy_paths_freebsd.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Vendor in latest containers/image

---

libnetwork/cni/cni_conversion.go
libnetwork/cni/cni_exec.go
libnetwork/cni/cni_types.go
libnetwork/cni/config.go
libnetwork/cni/config_freebsd.go
libnetwork/cni/config_linux.go
libnetwork/cni/network.go
libnetwork/cni/run.go
libnetwork/cni/run_freebsd.go
libnetwork/cni/run_linux.go
libnetwork/netavark/config.go
libnetwork/netavark/const.go
libnetwork/netavark/exec.go
libnetwork/netavark/ipam.go
libnetwork/netavark/network.go
libnetwork/netavark/run.go
libnetwork/network/interface.go
libnetwork/network/interface_freebsd.go
libnetwork/network/interface_linux.go

Build libnetwork on FreeBSD

---

pkg/retry/retry.go

[NO NEW TESTS NEEDED] No idea how to cause this situation.

Check if retry error is a Timeout

---

libimage/copier.go
pkg/retry/retry.go

Fixes: https://github.com/containers/common/issues/1058

Fix option names and functions to make lint happy.

---

libnetwork/cni/cni_conversion.go
libnetwork/cni/cni_types.go
libnetwork/cni/config_test.go
libnetwork/cni/testfiles/valid/isolate.conflist
libnetwork/netavark/config.go
libnetwork/netavark/config_test.go
libnetwork/types/const.go

libnetwork: add isolate network option

---

version/version.go

Bump to v0.49.0 

---

libimage/copier.go
libimage/manifest_list.go
libimage/manifests/manifests.go

libimage: Allow adding sigstore signatures, and submitting passphrases

---

.github/workflows/validate.yml
libimage/load.go
pkg/subscriptions/subscriptions.go

Fix spelling mistake

---

docs/containers.conf.5.md

docs: containers.conf: list all log drivers

---

libnetwork/network/interface.go

We are using CNI for systems that have run podman system reset, if storage is setup with additional stores.  This change will ignore additional store images and will use netarvark on clean systems.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2124887

Ignore additionalstore images when deciding to use netavark or CNI

---

pkg/util/util_supported.go

Partial Fix for containers#14606

Eval symlinks on XDG_RUNTIME_DIR

---

version/version.go

Bump to v0.50.1

---

version/version.go

Bump to v0.49.2

---

version/version.go

Bump to v0.48.1

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/containers.conf-freebsd
pkg/config/default.go

Signed-off-by: unknowndevQwQ@github unknowndevQwQ@protonmail.com

feat: add support for the youki OCI Runtime

---

pkg/ssh/connection_golang.go

Fixes: https://github.com/containers/podman/issues/16340

create known_hosts file path when missing

---

docs/containers.conf.5.md
pkg/config/containers.conf
pkg/config/default.go

This reverts commit 45b76f18a7b3dc32d62ed899650cebe5fad1b9d4.

Rework default list of capabilities to minimal

---

libnetwork/cni/network.go
libnetwork/netavark/network.go
pkg/configmaps/configmaps.go
pkg/configmaps/filedriver/filedriver.go
pkg/secrets/filedriver/filedriver.go
pkg/secrets/secrets.go

Don't use lockfile.Locker, it is deprecated

---

libimage/search.go

When we searching any image at a container registry,
the authentication could be required as well as push, pull, etc.
Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

libimage: search: add options for authentication

---

libimage/load.go

Must wait to write to an event until an image has
finished loading.
Related to #1325

libimage: wait to write an event until an image loaded

---

docs/containers.conf.5.md
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
version/version.go

Final backport to the v0.51 branch along with a version bump.  Will cut a release once merged.

0.51 backports

---

Makefile

Update list of codespell ignores

---

libnetwork/netavark/config.go
libnetwork/netavark/config_test.go

libnetwork/netavark: combine ipvlan macvlan code
Remove the code duplication and share some code between the ipvlan and
macvlan config creation.
Also fixes a problem with the macvlan dhcp selection, we have to set the
driver to dhcp if it is unset and no subnets are given.
Ipvlan does not support DHCP because the interfaces share the same mac
address.
Added tests for both the mcvlan dhcp selection and the ipvlan creation.
Fixes containers/podman#17630

Netavark add ipvlan support

---

docs/containers.conf.5.md
pkg/auth/auth.go
pkg/cgroups/cgroups.go
pkg/config/config.go
pkg/config/containers.conf
pkg/config/containers.conf-freebsd

Fix typos and other minor language issues

---

docs/containers.conf.5.md

[CI:DOCS] Cleanup man page display

---

pkg/config/config_test.go
pkg/config/default.go

Add kube_generate_type defaults

---

.github/dependabot.yml

Disable dependabot in favor of renovate

---

libnetwork/netavark/config.go
libnetwork/netavark/config_test.go
libnetwork/types/const.go
version/version.go

see https://github.com/containers/netavark/pull/699
https://bugzilla.redhat.com/show_bug.cgi?id=2183896

[v0.51] netavark: add bclim option for macvlan

---

pkg/retry/retry.go

thanks for the [comment](https://github.com/containers/common/pull/1492#discussion_r1226773237), we should follow the ownership principle.

fix: add a local variable 'isRetryable' to avoid modifying the caller's Options

---

docs/containers.conf.5.md
pkg/config/containers.conf

- Fix the type of the options.
- service_destinations should be engine.service_destinations
Related: https://github.com/containers/podman/issues/15615

Fix some containers.conf comments and docs

---

libnetwork/netavark/ipam.go
libnetwork/netavark/ipam_test.go

LeaseRange allows to set a custom start and end ip for our allocator. However in this case the allocator ignored that fact the the first ip (network ip) and the last ip (broadcast address only valid for ipv4) cannot be used. These ips are special and should never be assigned.
Interestingly the kernel allows to assign the broadcast address to a interface so it would appear to be working and no error was reported. Only the attempts to make a connection failed.
Fixes containers/podman#18906

libnetwork/netavark: fix ipam allocation for custom lease range

---

.github/workflows/validate.yml
Makefile
libimage/image.go
libimage/manifest_list.go
libimage/manifests/manifests.go
libnetwork/cni/config.go
libnetwork/etchosts/hosts.go
libnetwork/netavark/config.go
pkg/cgroups/cpuset_linux.go
pkg/completion/completion.go
pkg/config/default_test.go
pkg/configmaps/configmaps.go
pkg/hooks/hooks.go
pkg/manifests/manifests.go
pkg/secrets/secrets.go
pkg/supplemented/supplemented.go
pkg/supplemented/supplemented_test.go

Please refer to the individual commits.

bump golangci-lint to v1.53.3 and address new reports

---

libnetwork/slirp4netns/const.go
libnetwork/slirp4netns/slirp4netns.go
pkg/rootlessport/rootlessport_linux.go
pkg/servicereaper/service.go
pkg/util/util.go

add libnetwork/slirp4netns package

---

libnetwork/slirp4netns/slirp4netns.go

Buildah needs this option to ensure the child is killed when buildah is killed.
Also remove the unused ContainerPID option which is not needed and unused.

libnetwork/slirp4netns: add Pdeathsig option

---

version/version.go

Bump to v0.55.0

---

pkg/secrets/secrets.go
pkg/secrets/secrets_test.go

After secret --replace, make sure old ID is deleted

---

docs/containers.conf.5.md
pkg/config/config.go
pkg/config/config_test.go
pkg/config/containers.conf
pkg/config/default.go
pkg/config/testdata/containers_default.conf

Ref: https://github.com/containers/podman/pull/19140#discussion_r1254435823

containers.conf: Add `podmansh_timeout`

---

CODE-OF-CONDUCT.md

Update CODE-OF-CONDUCT.md with new mailing list

---

version/version.go

Bump to v0.56.0

---

libimage/manifests/manifests.go

chore: import packages only once

---

CODE-OF-CONDUCT.md

Update the Code of Conduct to ID the members of the CoC email list.

Add list members emails to the CoC

---

docs/Containerfile.5.md
libimage/copier.go
libimage/filters.go
libnetwork/netavark/network.go
pkg/config/config.go

URGENT: heal CI: fix codespell

---

pkg/cgroups/cgroups_linux.go

This function was accidently removed and is needed by podman.

Add back SystemCPUUsage

---

go.mod
go.sum
vendor/github.com/containers/image/v5/copy/compression.go
vendor/github.com/containers/image/v5/docker/errors.go
vendor/github.com/containers/image/v5/internal/imagedestination/impl/helpers.go
vendor/github.com/containers/image/v5/version/version.go
vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
vendor/github.com/go-jose/go-jose/v3/symmetric.go
vendor/github.com/klauspost/compress/README.md
vendor/github.com/klauspost/compress/fse/compress.go
vendor/github.com/klauspost/compress/zstd/enc_best.go
vendor/github.com/klauspost/compress/zstd/enc_better.go
vendor/modules.txt
version/version.go

Bump c/image to v5.29.0, common to v0.57.0, and then v0.57.1-dev

Bump c/image to v5.29.0, common to v0.57.0, and then v0.57.1-dev

---

version/version.go

[v0.57] bump to v0.57.1-dev

---

version/version.go

This version is intended for podman 5.0.

bump to 0.58.0-dev

---

pkg/seccomp/default_linux.go
pkg/seccomp/seccomp.json

seccomp: allow fchmodat2

---

go.mod

Move minimal golang to v1.20

---

version/version.go

[v0.57] Bump to v0.57.4, then v0.57.5-dev

---

libimage/push.go

Fix dockerDaemonTransport vendor

---

pkg/version/version.go

If there is a "slow" and a "quick" program (not missing), do not look for the package again (if it is not there).
Fixes #1924 
Each call to dpkg takes a second, and it is especially bad when installing from source instead of from packages...
* https://github.com/containers/podman/issues/22102

Only try each package format once

---

docs/containers.conf.5.md
pkg/config/config.go

@rhatdan PTAL
cc @albertofaria

mention default runtimes correctly

---

version/version.go

As the title says. Needed for Podman 5.0.1

Bump to v0.58.1

---

.codespellrc
libnetwork/internal/rootlessnetns/netns_linux.go
libnetwork/netavark/network.go

see commits
This fixes two issues reported in podman https://github.com/containers/podman/issues/22218 and https://github.com/containers/podman/issues/22168

libnetwork/rootlessnetns: fix some issues

---

version/version.go

Bumping to v0.58.2 for Podman v5.0.2
This time from the right branch.

Bump to v0.58.2

---

go.mod
go.sum
vendor/github.com/containers/image/v5/copy/progress_bars.go
vendor/github.com/containers/image/v5/copy/single.go
vendor/github.com/containers/image/v5/directory/directory_dest.go
vendor/github.com/containers/image/v5/directory/directory_src.go
vendor/github.com/containers/image/v5/directory/directory_transport.go
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/docker/docker_image.go
vendor/github.com/containers/image/v5/docker/docker_image_dest.go
vendor/github.com/containers/image/v5/docker/docker_image_src.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
vendor/github.com/containers/image/v5/docker/registries_d.go
vendor/github.com/containers/image/v5/openshift/openshift_src.go
vendor/github.com/containers/image/v5/ostree/ostree_dest.go
vendor/github.com/containers/image/v5/ostree/ostree_src.go
vendor/github.com/containers/image/v5/storage/storage_dest.go
vendor/github.com/containers/image/v5/storage/storage_image.go
vendor/github.com/containers/image/v5/storage/storage_reference.go
vendor/github.com/containers/image/v5/storage/storage_src.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Partially addresses CVE-2024-3727:
https://issues.redhat.com/browse/OCPBUGS-33266
https://issues.redhat.com/browse/OCPBUGS-33267
https://issues.redhat.com/browse/OCPBUGS-33268
https://issues.redhat.com/browse/RHEL-35438
https://issues.redhat.com/browse/RHEL-35439
https://issues.redhat.com/browse/RHEL-35440
https://issues.redhat.com/browse/RHEL-35441
https://issues.redhat.com/browse/RHEL-35442
https://issues.redhat.com/browse/RHEL-35443

Address CVE-2024-3737

---

go.mod
go.sum
vendor/github.com/containers/image/v5/copy/progress_bars.go
vendor/github.com/containers/image/v5/copy/single.go
vendor/github.com/containers/image/v5/directory/directory_dest.go
vendor/github.com/containers/image/v5/directory/directory_src.go
vendor/github.com/containers/image/v5/directory/directory_transport.go
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/docker/docker_image.go
vendor/github.com/containers/image/v5/docker/docker_image_dest.go
vendor/github.com/containers/image/v5/docker/docker_image_src.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
vendor/github.com/containers/image/v5/docker/registries_d.go
vendor/github.com/containers/image/v5/openshift/openshift_src.go
vendor/github.com/containers/image/v5/ostree/ostree_dest.go
vendor/github.com/containers/image/v5/ostree/ostree_src.go
vendor/github.com/containers/image/v5/storage/storage_dest.go
vendor/github.com/containers/image/v5/storage/storage_image.go
vendor/github.com/containers/image/v5/storage/storage_reference.go
vendor/github.com/containers/image/v5/storage/storage_src.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt
version/version.go

Partially addresses CVE-2024-3727:
https://issues.redhat.com/browse/OCPBUGS-33266
https://issues.redhat.com/browse/OCPBUGS-33267
https://issues.redhat.com/browse/OCPBUGS-33268
https://issues.redhat.com/browse/RHEL-35438
https://issues.redhat.com/browse/RHEL-35439
https://issues.redhat.com/browse/RHEL-35440
https://issues.redhat.com/browse/RHEL-35441
https://issues.redhat.com/browse/RHEL-35442
https://issues.redhat.com/browse/RHEL-35443

[v0.58] Address CVE-2024-3737 

---

pkg/version/version.go

Previously, the package field on Arch Linux looked like:
/usr/bin/crun is owned by crun 1.15-1
Now, it looks like:
crun-1.15-1
Closes #1934
I also moved `apk` because I think it's supposed to be in the if above instead of outside.

pkg/version: fix parsing of package names

---

docs/Containerfile.5.md

add relabel documentation to Containerfile man page

---

.cirrus.yml

Bump CI VM Images

---

OWNERS

[CI:DOCS] add jnovy

---

version/version.go

Bump to c/common for Podman v5.2.1

[v0.60] Bumpc to c/common v0.60.1

---

libnetwork/etchosts/hosts.go
libnetwork/etchosts/hosts_test.go

Hello, 
This PR is linked to https://github.com/containers/podman/pull/23802 on podman.

Add multiple host for single IP

---

libimage/copier.go
libimage/import.go
libimage/manifest_list.go
libimage/pull.go
libimage/push.go
libimage/save.go

This reverts commit be0910d4cbbe423db642c3a60eaf5db71a480831.

Revert "Export portions of Copier"

---

.github/workflows/validate.yml

ci/gha: bump ubuntu to 24.04

---

version/version.go

[v0.58] Bump to v0.58.5

---

OWNERS

Tidy up OWNERS file and remove duplicated reviewers.

Audit and update OWNERS file

---

.packit.yaml

Packit: constrain koji_build job to fedora package to avoid dupes

---

.packit.yaml

V0.60 packit backports

---

.cirrus.yml

update ci image to f41

---

OWNERS

OWNERS: remove edsantiago

---

go.mod
go.sum
vendor/github.com/containers/image/v5/signature/fulcio_cert.go
vendor/github.com/containers/image/v5/signature/pki_cert.go
vendor/github.com/containers/image/v5/signature/policy_config_sigstore.go
vendor/github.com/containers/image/v5/signature/policy_eval_sigstore.go
vendor/github.com/containers/image/v5/signature/policy_types.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Merge the tag back into main to make go modules aware that main is newer
than this tag.

Merge back v0.62.1 into main

---

libnetwork/netavark/run.go

While we already did clean up the allocated ips on the regular setup error this did not worked for errors from the rootlessNetns.Setup() call. To ensure we dealloc the ips on all error paths use a defer function that checks the return error value.
Fixes containers/podman#25422

libnetwork/netavark: dealloc ips on setup error

---

go.mod
go.sum
vendor/github.com/containers/image/v5/docker/body_reader.go
vendor/github.com/containers/image/v5/internal/manifest/oci_index.go
vendor/github.com/containers/image/v5/openshift/openshift-copies.go
vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
vendor/github.com/containers/image/v5/tarball/tarball_src.go
vendor/modules.txt

So the go tooling knows c/common main is newer

Merge back v0.62.3 into main and update c/image to latest
