containers/common

- libimage/image.go
As reported in containers/podman/issues/15485, Docker sends untag events
prior to removing the image.  Follow that example for compatibility
reasons.
> libimage: untag events on image removal

- libimage/copier.go
- libimage/manifests/manifests.go
- libimage/normalize.go
- libimage/pull.go
- libimage/search.go
- pkg/auth/auth.go
- pkg/cgroups/cgroups.go
- pkg/cgroups/cgroups_linux.go
- pkg/cgroups/cgroups_supported.go
- pkg/cgroups/utils.go
- pkg/configmaps/configmaps.go
- pkg/manifests/manifests.go
- pkg/parse/parse_unix.go
- pkg/secrets/secrets.go
- pkg/ssh/connection_golang.go
- pkg/subscriptions/subscriptions.go
- pkg/supplemented/supplemented.go
Podman adds an Error: to every error message. So starting an error
message with "error" ends up being reported to the user as
Error: error ...
This patch removes the stutter.
Also ioutil.ReadFile errors report the Path, so wrapping the err message
with the path causes a stutter.
> Fix stutters

- pkg/config/default_freebsd.go
Setting it to disabled triggers NoCgroups logic in podman which adds
extra validation and changes the conmon command line in ways that are
messy to work around. It turns out that pretending cgroups is enabled
even though the platform doesn't support it is easier.
> Change default cgroups mode to enabled on FreeBSD

- pkg/cgroups/utils.go
if cpuset.cpus[.effective] file is missing, then ignore the error
since it means the cpuset controller is not enabled in the kernel,
rather than returning an error.
Closes: https://github.com/containers/common/issues/1134
> cgroup: do not fail with missing cpuset file

- pkg/report/formatter.go
- pkg/report/formatter_test.go
- pkg/report/template_test.go
Docker tries to be smart and replaces \n with the actual newline character.
For compat we do the same but this will break formats such as '{{printf "\n"}}'
To be backwards compatible with the previous behavior we try to replace and
parse the template. If it fails use the original text and parse again.
This fix will not be enough. It requires many changes in podman since
most commands will do their own NormalizeFormat() call before using this
backend which seems wrong and creates a lot of duplication. This has to
be fixed in Podman.
Required for https://bugzilla.redhat.com/show_bug.cgi?id=2059658
and https://github.com/containers/podman/issues/13446.
> pkg/report: handle newline in template string

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Allow secrets to be labeled. Add new field in secrets package called label.
Part of: https://github.com/containers/podman/issues/14917
> Add labels to secrets

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Clean up store code by using StoreOpts instead of multiple args as opts for storing secrets.
Mentioned in: https://github.com/containers/common/pull/1147#discussion_r965635116
> Use StoreOpts for secret store API

- libnetwork/types/network.go
Both MAC and IP addresses are strings when serialized to JSON or deserialized from JSON. By default swagger will show a byte array which is wrong so we have to mauannly overwrite these fields.
Required for https://github.com/containers/podman/issues/13342 However we still have to update our swagger version to at least 0.30 in podman to make it work.
> libnetwork/types: add correct swagger types

- pkg/config/config_linux.go
- pkg/config/default.go
Change the check to look for the UID to decide whether to load the default configuration files from the user directory instead of the system path.
> config: look user id instead of rootless

- pkg/config/default.go
originally the code had the condition "!unshare.IsRootless()", and commit 52108b71e1a2abc82f1c104ca30792548d8937b9 introduced the issue by replacing it with "unshare.GetRootlessUID() != 0".
> config: correct the check for root

- libimage/platform.go
When checking the platform of an image, take into account that it may be corrupted.
Partially-fixes: containers/podman/issues/15853
> libimage: platform: check if image is corrupted

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/ssh/connection_golang.go
- pkg/ssh/types.go
- pkg/ssh/utils.go
podman machine and podman-remote need some softer handling when it comes to key verification
this ensures that podman machine will still work (until we want to make this mandatory). I made the call back function more verbose so we know what is happening from now on.
> add proper handling for golang ssh

- libimage/normalize_test.go
- libimage/platform.go
Following PR attempts to unify code being using in buildah and other part, so a common code chunk can be used as a source of truth for normalizing platforms.
As of now NormalizePlatform ignores normalizing or setting default variants for specific arch types thus producing empty variants in results even when default variants were expected for such cases.
Example consider: `linux/armhf` -> `{os:linux, arch: arm, variant: v7}`
See: https://github.com/containers/buildah/pull/4286 for more details.
> libimage.NormalizePlatform: normalize default `variant` as per specified `arch`

- pkg/util/util_supported.go
We must try out all possible alternatives for rootless users instead of failing eary if `XDG_RUNTIME_DIR` is not set.
Commit which introduced regression: https://github.com/containers/common/commit/48f90f538f3e49ee6a66f1e4efad1a6498800efe
> util, GetRuntimeDir: don't error out early if `XDG_RUNTIME_DIR` is not set.

- pkg/config/default.go
Before 52108b71e1a2abc this code used unshare.IsRootless() which on Windows always returns false (the behavior we want).
After 52108b71e1a2abc, a condition was unintentionally inverted, allowing Windows to function.
Commit f8f2c4f2ee56 fixed the inversion, but unintentionally excluded Windows since it used == 0 instead of <= 0 (Windows returns -1)
Move the logic behind a function with a comment since the Windows path is a bit exotic.
In the future, the Windows path should likely be refactored to be more intuitive; however, this will get things working for now.
> Fix Windows regression introduced by PR #1161

- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Backported to v0.49 branch for Podman v4.2.0 per RHBZ 2080458
> [v0.49] Backport #1129

- .github/workflows/validate.yml
Due to it's design, github-actions workflows source their configuration from different locations depending on the event-type.  This is impossible for humans to manage, let alone on repos with multiple release-branches.  One would need to:
1. Understand the config-source for all utilized trigger events.
2. Ensure upon creation of a new branch or tag, the relevant source is updated to support reliable long-term operations.
3. Repeat for infinity.
Fix this by removing all GHA trigger events except `pull_request`.  For all pull requests, only trigger code validation if the target is `main`.
Also, for `push` (merge) events, limit validation to `main` to prevent (new) validate from trying to run against (old) release branches - it will fail.
> GHA: Limit operations to `main` branch only

- .cirrus.yml
- .github/workflows/validate.yml
No release-branch monitoring or maintenance is/was performed for this repo.  Due to disuse, release-branch CI VM images were pruned.  Attempt to resuscitate the patient using high-voltage defibrillator:  Steal the CI VM images from the podman:v4.0-rhel branch.  Also update the meta task to help these images stay alive (maybe).
Signed-off-by: Chris Evich <cevich@redhat.com>
> [v0.48] Cirrus: Resuscitate CI

- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/default.go
Backport #1129  to v0.48 branch for Podman v4.1.1 per RHBZ 2080458
> [v0.48] Backport #1129

- .github/workflows/validate.yml
Codespell is getting angry on function name `ShouldNot` which should be acceptable.
Ignore in-code function name
https://github.com/containers/common/blob/main/pkg/config/config_test.go#L537 and unblock CI
> ci,codespell: ignore function `ShouldNot`

- libnetwork/types/network.go
Netavark now accepts `dns_servers` for each container which allows containers to use custom DNS servers as resolvers instead of falling back to host's resolver.
Following field allows users of libnetwork to pass newly added field to `netavark` and `aarvark-dns`
Actual feature implemented here:
* https://github.com/containers/aardvark-dns/pull/240
* https://github.com/containers/netavark/pull/452
> libnetwork: add `DNSServers` to `NetworkOptions`

- libimage/corrupted_test.go
- libimage/disk_usage.go
Add an API to query the sum of the layer sizes.  This data is needed to fix containers/podman/issues/16135.
> libimage: add LayersDiskUsage

- libimage/corrupted_test.go
- libimage/disk_usage.go
- libimage/image.go
- libimage/layer_tree.go
It turns out only counting the layers size is not sufficient for `podman systemd df` as it excludes the size of the manifests, configs and potentially attached meta data in the storage.
Instead, sum the image sizes but distract redundant layers.  That indeed gives the expected result and does not yield negative results for reclaimable space.
Remove the unrelease LayersDiskUsage function again to avoid expensive recalculation of the layer tree.  We are still below 1.0, and I am convinced the total image size belongs into DiskUsage.
NOTE: The DiskUsage function does not have test coverage in libimage.
This should be addressed at some point but in the interest of
time I leverage podman's system tests.
@rhatdan @giuseppe @flouthoc PTAL …
> DiskUsage: return total images size

- libimage/image.go
Cache the result of (*Image).Size() in the image-local cache to speed up subsequent calls.
> libimage: cache image size

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/default.go
Another experimental OCI runtime for FreeBSD, similar to runj but with a focus on podman/buildah compatiblity.
> config: Add config entry for ocijail

- libnetwork/netavark/config.go
- libnetwork/types/network.go
This is not supported in netavark so we should set to false by default to make sure podman inspect will show the correct info.
> libnetwork/netavark: disable dns for macvlan

- libimage/platform.go
Before:
`WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })`
After:
`WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)`
Fixes: containers/podman/issues/16392
> libimage: format platform warning

- pkg/report/validate.go
- pkg/report/validate_test.go
When a user request --format `{{json .}}` they would want the go template parser to handle it. Currently we overwrite this and assume that `{{json .}}` equals `json`. This is not correct. When the output is a range (array), i.e. podman ps, it should return one json object per line and not a json array which is the case with `json`.
This is required for docker compat.
Fixes containers/podman#16436
> pkg/report: fix IsJSON()

- pkg/report/validate.go
- pkg/report/validate_test.go
The PR #1226 was merged to soon, it breaks podman tests and backwards compat. `{{json}}` is not a valid template but it worked before the same as `json` so we should keep that.
Fixes up commit 152c8409709b
> pkg/report: fix IsJSON() #2

- pkg/config/config_darwin.go
- pkg/config/config_freebsd.go
- pkg/config/config_linux.go
- pkg/config/config_windows.go
- pkg/config/default.go
The correct location on FreeBSD is /usr/local/etc/containers/policy.json which is consistent with path conventions for installed packages. This fixes 'podman commit' on FreeBSD.
There are several definitions of this path:
- c/image/signature has builtinDefaultPolicyPath and DefaultPolicy
- c/podman/pkg/trust has systemDefaultPolicyPath and DefaultPolicyPath
- c/common/pkg/config has DefaultSignaturePolicyPath
As far as I can tell, buildah uses c/image/signature which is why 'buildah commit' was already working for me. Podman is using the c/common one. Very confusing.
> pkg/config: Fix DefaultSignaturePath on FreeBSD

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_override.conf
Containers.conf now supports `platform_to_oci_runtime` which allows end users to map variant of OCI runtime for a particular platform.
Most ideal use-case of this feature is switching to crun's variant when platform string is `wasm32/wasi`.
Example
```toml
[engine.platform_to_oci_runtime]
"wasi/wasm" = "crun-wasm"
"wasi/wasm32" = "crun-wasm"
"wasi/wasm64" = "crun-wasm"
```
> config: add support for `platform_to_oci_runtime` and default entries for `wasi/wasm`

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/testfiles/valid/metric.json
- libnetwork/types/const.go
All the gruntwork is done by Netavark, so all that's needed it to know the key exists and verify that it parses as a uint.
> Add support for route metric in network configs

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/types/network.go
libnetwork must allow to pass network_dns_servers so aardvark and netavark can consume it and enabled network scoped dns.
Feature implemented at netavark and aardvark end
* Netavark: https://github.com/containers/netavark/pull/497
> libnetwork, Network: add field `NetworkDNSServers` for network scoped dns

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/default.go
Podman and Buildah do not use this field, and I
know of no users of it, remove it from docs and
the default conf file, so users will not expect
it to do anything.
Leaving implementation in the slight chance someone has used it in a non containers project.
Fixes: https://github.com/containers/podman/issues/16562
> Deprecate UserNSSize, since we don't use it

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/default.go
For a couple of years now we have been shipping containers.conf settings to use only 10 capabities. Docker uses 14, with the difference being CAP_AUDIT_ALLOW, CAP_NET_RAW, CAP_MKNOD, CAP_CHROOT.
This allows us to run with a tighter security then Docker.
This PR makes the change to default config, so that if no containers.conf overrides are present, we will run with the tighter security. Currently most distros that ship the containers.conf already run with this setting, but this makes it formal, and changes the man page to match the defaults.
> Rework default list of capabilities to minimal

- pkg/config/config.go
- pkg/config/default.go
- pkg/config/default_test.go
This is taking time on every podman call, and provide limited protection. Versioning should be handled in the packaging system and this is an unlikely to happen.
Every exec done by container tools hurts us as we try to get container startup team to absolute minimal amounts.
> Remove conmon probe

- docs/Containerfile.5.md
Mention `readwrite, rw` option for `RUN --mount` instruction and mention correct default for `ro, readonly`.
Closes: https://github.com/containers/common/issues/1246
> [CI:DOCS] docs,containerfile: `RUN --mount` mention `rw` option

- pkg/cgroups/cgroups.go
do not start up a dbus daemon if it is not already running.
[NO NEW TESTS NEEDED] the fix is in a dependency.
Closes: https://github.com/containers/podman/issues/16718
> cgroups: use SessionBusPrivateNoAutoStartup

- libnetwork/cni/cni_types.go
- libnetwork/cni/config_test.go
When creating macvlan or ipvlan network configs with the none ipam driver we would always cause a segfault because of a nil pointer dereference.
Add a test for both to prevent a regression.
Fixes containers/podman#16620
> libnetwork/cni: fix panic with ipam driver none

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/cni/run_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/ipam_test.go
- libnetwork/netavark/run_test.go
- libnetwork/types/network.go
Having this flag is very useful when using scripts or systemd unit files
Signed-off-by: Ygal Blum <ygal.blum@gmail.com>
> Libnetwork: Add IgnoreIfExists flag to network create method

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/run.go
- libnetwork/types/network.go
New features in netavark/aardvark allows users to update network dns servers and all the containers attached to those networks uses updated resolvers.
Following PR adds support in `libnetwork` to support
* Add support for higher level `NetworkUpdate` API
* Add support for `Update` exec call which can invoke netavark with a new update option added here: https://github.com/containers/netavark/pull/503
> libnetwork: extend API to support `NetworkUpdate`

- pkg/report/doc.go
This adds some simple headers to the godoc for the reports package. This will allow, when viewed on https://pkg.go.dev/github.com/containers/common/pkg/report, to link directly to sections like the "Template Functions" section.
This is related to https://github.com/containers/skopeo/pull/1822
> Add godoc headers for report package

- libnetwork/cni/run_test.go
- libnetwork/netavark/run_test.go
- pkg/netns/netns_linux.go
I want to switch podman over to only using strings for the netns path. So we no longer pass this interface around. Buildah doesn't use this so we only need to fix it in Podman. I have a WIP PR[1] for that.
[1] https://github.com/containers/podman/pull/16756
> pkg/netns: UnmountNS() accept netns path as string

- docs/containers.conf.5.md
- pkg/config/default_darwin.go
On MacOS, mount /Users, /private/, /var/folders by default for better docker compat. The homedir on MacOS is /Users/<username>, so that will be mounted automatically anyway with this change.
Docker also mounts /Volumes and /tmp, /Volumes fails with a Too many levels of symbolic links, as Volumes on Mac is just a symlink to / which seems like a bad idea to mount anyway. /tmp fails because the Podman machine uses the tmp directory inside the machine and writes content to it on boot, causing the mount to fail. However, on Mac, /tmp is symlinked to /private/tmp anyway, so those files are accessible from there.
Part of: https://github.com/containers/podman/issues/16447
> Add to default machine volumes for MacOS

- pkg/cgroups/cgroups.go
- version/version.go
do not start up a dbus daemon if it is not already running.
[NO NEW TESTS NEEDED] the fix is in a dependency.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2153894
(cherry picked from commit 12a939e1048a65cb4085a4bb4d42f4ecf86a0faf)
We'll need to cut a new release afterward
> [0.49] cgroups: use SessionBusPrivateNoAutoStartup

- libnetwork/cni/network.go
- libnetwork/netavark/const.go
- libnetwork/netavark/network.go
The default /etc/containers/networks location might not be writeable, while this breaks podman network create it does not need to break all podman commands since the lock is created on libpod initialization.
ref https://github.com/containers/common/pull/1270
> libnetwork: change lock path to tmpfs for root

- libimage/pull.go
- libimage/pull_test.go
I verified that the test fails without the code changes.
Fixes: github.com/containers/podman/issues/17063
@rhatdan PTAL
> libimage: pull: do not enforce pull if local image matches

- libnetwork/cni/cni_conversion.go
- libnetwork/cni/config_test.go
- libnetwork/cni/network.go
Commit 4bf13f4b2946 caused a regression, previously the lockfile package create the config directory. Now this is no longer the case so we have to create it explicitly.
Note that netavark already did this so no change is needed there.
This was reported by the RHEL QE team.
> libnetwork/cni: mkdir network config dir

- libimage/copier.go
- libimage/manifest_list.go
- libimage/manifests/manifests.go
This is infrastructure for Podman supporting something like https://github.com/containers/skopeo/pull/1849 .
RFC . I’m not quite sure how to deal with the inevitable interactivity of Fulcio. Right now Fulcio interactivity is done here in c/common, and passphrase interactivity happens in Podman.
One consistent option would be to move all interactivity to Podman, i.e. to require Podman to provide a finished `c/image/signature/signer.Signer` (and then, within Podman, would that interactivity be in the top-level CLI, or only in the local engine implementation?).
Another consistent option would be to move all interactivity to c/common, i.e. to implement proper passphrase prompting down here in c/common.
I guess I weakly prefer Podman-side interactivity.
@vrothberg WDYT?
> `--sign-by-sigstore` infrastructure

- libimage/pull.go
- libimage/pull_test.go
This reverts commit ba3a9c0f770b7f77c7e95760d50f70216d505b8a as it caused a nasty flake on Buildah [1]
[1] https://github.com/containers/buildah/pull/4527
> Revert "libimage: pull: do not enforce pull if local image matches"

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
It is needed to implement https://github.com/containers/podman/issues/17116
The work in progress implementation used to verify POC could be found here https://github.com/arixmkii/podman/commit/e443a7034955d21347eed3bf6b708e1ca38cf093 It is not a PR for Podman yet as this will not compile without this change inside common.
Additionally fixed inconsistency between doc comment and field name for `Image` field.
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
> Add Provider to MachineConfig

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
With progress on netavark-dhcp-proxy, we can begin to macvlan with dhcp back into the fold for netavark.
Signed-off-by: Brent Baude <bbaude@redhat.com>
> Enable DHCP macvlan

- libimage/load.go
- libimage/pull.go
Make sure that all image events have an ID. I noticed that some (e.g., pull) did not include the ID which is confusing and renders the events less useful.
@rhatdan @flouthoc @giuseppe PTAL
> libimage: make sure all events have an ID

- libnetwork/cni/config.go
- libnetwork/cni/config_test.go
- libnetwork/internal/util/util.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
Following docker specific network options are supported via CLI
1. com.docker.network.driver.mtu
2. com.docker.network.bridge.name
Fixes https://github.com/containers/podman/issues/15830
> Support docker-specific network create options via CLI

- pkg/config/config.go
Fixes #1123 
Additionally tries `exec.LookPath` over Absolute path, when searching in predefined directories. `exec.LookPath` could handle absolute paths - verified on Windows and macOS.
On Windows was tested with `my.bat` file in `C:\Temp`, which is obviously not referenced by PATH variable.
Test program (my.go):
```go
package main
import (
"fmt"
"os/exec"
)
func main() {
lp, err := exec.LookPath("C:\\Temp\\my")
fmt.Printf("R: %q, E: %v", lp, err)
}
```
Run as `go run my.go` and outputs.
```
R: "C:\\Temp\\my.bat", E: <nil>
```
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
> LookPath like impelementations for OS specific executable searches

- libimage/search.go
IdentityToken will be needed if we use the search command
with authfile option.
Signed-off-by: Toshiki Sonoda [sonoda.toshiki@fujitsu.com](mailto:sonoda.toshiki@fujitsu.com)
> libimage: search: add IdentityToken option for authentication

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/db_backend.go
- pkg/config/db_backend_test.go
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
The on-going work of adding a new database backend to Podman requires it to be configurable in containers.conf.  To prevent any breaking changes, the backend defaults to Podman's current boltdb backend.  Also export the parsing function for it be usable by Podman.
NOTE: documentation will be added once the database rewrite in Podman has been completed.  I want to avoid any incomplete docs from leaking into a release.
Fixes: https://issues.redhat.com/browse/RUN-1772
@mheon @baude PTAL
> containers.conf: add database backend option

- pkg/auth/auth.go
- pkg/auth/cli.go
Add an option to not write back the credentials to the authfile or any credential helper.  The `/auth` compat endpoint of Podman is currently not using this code here which ultimately led to normalization errors surfacing in containers/podman/issues/17571.
The new option allows the endpoint to use this function without writing back the credentials.
> pkg/auth: add `NoWriteBack` option

- libnetwork/netavark/config_test.go
We cannot compare network with Expect().To(Equal()), the internal time.Time is not equal after parsing from file. There is some internal field offset that can be different but the date is still the same. Other tests have the same problem and to circumvent this we use EqualNetwork() there. Do the same here.
Fixes #1335
> fix netavark IgnoreIfExists config test flake

- libimage/pull.go
Set the input name in the names of pull events.  Otherwise, we'll loose the transport information which also breaks Podman's system tests.
@flouthoc @giuseppe PTAL
> libimage: pull events: set input name

- pkg/auth/auth.go
To preserve the knowledge about the error without string compares. Needed in Podman's REST API.
@Luap99 @mtrmac @edsantiago PTAL
See https://github.com/containers/podman/pull/17581#issuecomment-1438663276.
> pkg/auth/Login: return a typed error

- pkg/report/formatter.go
- pkg/report/formatter_test.go
Completely skipping the NormalizeFormat part also skipped the removal of the "table " directive.
Cc: @Luap99 , this is related to #1146 . I might be missing something.
> Fix the combination of "table " and \n in report formats

- libimage/copier.go
- libimage/search.go
- We need to set DockerAuthConfig even if we use of
non-IdentityToken credentials.
- This function should be failed when there are multiple
credential sources, not only `Username` + `Credentials`.
Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>
> libimage: Fix getDockerAuthConfig() for authentication

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
We enforced `NetworkDNSServers` to be IP addresses and we follow this enfore rule while a user is creating network, see comment https://github.com/containers/common/pull/1237#pullrequestreview-1188001727 and PR https://github.com/containers/common/pull/1237
Following check was missed in `NetworkUpdateOptions` hence add this check now.
> netavark,NetworkUpdate: `NetworkUpdateOptions` must be IP addresses

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_default.conf
This will allows users to set all containers to automatically set certain cgroup fields globally for all of their containers.
> Allow cgroup-conf settings to be stored in containers.conf

- docs/Containerfile.5.md
Document RUN --network added in https://github.com/containers/buildah/pull/4566
Content is similar to:https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run---network
[CI:DOCS]
> [CI:DOCS] docs/containerfile: document `RUN --network`

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_default.conf
> Add oom_score_adj to set default oom score adj

- .cirrus.yml
- libnetwork/netavark/run_test.go
Ref: https://github.com/containers/automation_images/pull/261
> Cirrus: Update CI VM images to F37

- pkg/hooks/docs/oci-hooks.5.md
Podman supports the version 1.0.2 hooks such as `createRuntime` since version 2.2.0
Closes #1370
> docs: Update OCI Runtime Specifications version referenced to 1.0.2

- pkg/auth/auth.go
- pkg/auth/cli.go
Backports to the newly created v0.51 branch. See individual commits for details.
@rhatdan you can backport https://github.com/containers/common/pull/1373 to the same branch and then we can cut a new release.
> V0.51 backports

- version/version.go
v0.51 is being used in RHEL, so I created a branch for it. To avoid confusion and potential risks, bump the main branch to the next minor v0.52.0-dev.
we didn't created a v0.51 branch during vendor dance
> bump to v0.52.0-dev

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
Add yet another environment variable for loading containers.conf. When CONTAINERS_CONF_OVERRIDE is set, the specified config file will be loaded last - even when CONTAINERS_CONF is set.
This mechanism is needed to preserve system settings and other environment variables.  Setting CONTAINERS_CONF will load only the specified config file and ignore all system and user paths. That makes testing hard as many Podman tests use CONTAINERS_CONF for testing.
The intended use of CONTAINERS_CONF_OVERRIDE is to set it during tests and point it to a specific configuration of Podman (e.g., netavark with sqlite backend).
Similar needs have popped up talking to users in the automotive and high-performance computing space.  In a way, such a setting allows for specifying a specific "flavor" of Podman while …
> pkg/config: add CONTAINERS_CONF_OVERRIDE

- libimage/disk_usage.go
- libimage/filters.go
- libimage/history.go
- libimage/image.go
- libimage/image_tree.go
- libimage/layer_tree.go
- libimage/push_test.go
- libimage/runtime.go
Checking whether an image is dangling and finding a parent image requires building a layer tree.  Computing a layer tree is expensive, so add options to `ListImages` to pre-compute the dangling and parent information ahead of time;  that requires 1 layer tree instead of N. The information will then be cached in the images such that subsequent calls to `IsDangling()` and `Parent()` can return the cached data.
Context: containers/podman/issues/17828
> libimage: ListImages: pre-compute dangling/parent

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
> libnetwork/netavark: error messages should start lower case

- .github/workflows/validate.yml
Digest-based references are technically safer, however they're more difficult to manage and harder on the eyes.  The safety-benefits for high-traffic actions is also likely overstated.  Switch back to using simple version numbers.
Fixes: #1407
> GHA: Use version numbers instead of digests

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
Document the `database_backend` option which has been added earlier but intentionally left undocumented to avoid the impression sqlite would be ready for prime-time.
@mheon @baude @giuseppe PTAL
> [CI:DOCS] containers.conf: database_backend

- pkg/sysinfo/numcpu.go
- pkg/sysinfo/numcpu_linux.go
- pkg/sysinfo/numcpu_other.go
- pkg/sysinfo/numcpu_windows.go
Use a single `NumCPU` implementation, so that the godoc string and the fallback to `runtime.NumCPU` can be maintained in one place.
> pkg/sysinfo: unify NumCPU implementations

- pkg/subscriptions/subscriptions.go
- pkg/umask/umask.go
- pkg/umask/umask_test.go
This call will be done in parallel which messes up the umask on CRI-O on container creation. This call will be done in parallel which messes up the umask on CRI-O on container creation. We now call `chmod` after directory and file creation to enforce the right permissions.
> Don't call `umask` in subscriptions

- pkg/subscriptions/subscriptions.go
- pkg/subscriptions/subscriptions_test.go
The name is actually a relative path, so rename the field to make it clear add add comments + test to prevent future people from making the same mistake.
Regression was caught in podman CI:
https://github.com/containers/podman/pull/18350
Fixes d4a3de3a ("Don't call `umask` in subscriptions")
> pkg/subscription: fix regression in saveTo()

- .cirrus.yml
This package is downloaded into the CI VM Images.  No need to runtime-install it from repos.
> Cirrus: Resolve TODO WRT podman-plugins RPM

- version/version.go
We require a new version to be able to use the new umask API. Therefore I'm proposing to bump to v0.53.0 (and v0.54.0-dev) in a second commit.
> Bump v0.53.0

- pkg/sysinfo/numcpu_linux.go
The man page for sched_setaffinity(2) states the following about the pid argument [1]:
> If pid is zero, then the mask of the calling thread is returned.
Thus the additional call to unix.Getpid can be omitted and pid = 0 passed to unix.SchedGetaffinity.
[1] https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html#DESCRIPTION
> pkg/sysinfo: omit Getpid call in numCPU

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_override.conf
The original SELinux support in Docker and Podman does not follow the default SELinux rules for how label transitions are supposed to be handled. Containers always switch their user and role to system_u:system_r, rather then maintain the collers user and role. For example
unconfined_u:unconfined_r:container_t:s0:c1,c2
Advanced SELinux administrators want to confine users but still allow them to create containers from their role, but not allow them to launch a privileged container like spc_t.
This means if a user running as
container_user_u:container_user_r:container_user_t:s0
Ran a container they would get
container_user_u:container_user_r:container_t:s0:c1,c2
If they run a privileged container they would run it with:
container_user_u:container_user_r:container_user_t:s0
If they want to …
> Add support for confined SELinux users

- docs/containers.conf.5.md
Correct a sentence stating that Podman would not run with CHROOT. It only did for a short period of time but CHROOT had to be added back since many uses (e.g., in-container builds) depend on it.
PTAL @Luap99 @giuseppe @flouthoc
> docs: containers.conf: CHROOT

- pkg/subscriptions/subscriptions.go
- pkg/subscriptions/subscriptions_test.go
- pkg/umask/umask.go
- pkg/umask/umask_test.go
Cherry-pick of 51d0f8fbb200335c5dd6b52d4903aeaad7a16810 and 2f6d017cc6d24c70cc55c0922f1a55666237c81a into a v0.50 branch, required for CRI-O in https://github.com/cri-o/cri-o/pull/6895
> [0.50] Don't call umask in subscriptions

- libnetwork/cni/network.go
- libnetwork/netavark/network.go
- libnetwork/types/network.go
- pkg/util/util.go
`NetworkInfo()` return the network binary path,
package version and program version.
Related to https://github.com/containers/podman/pull/18383
> libnetwork: add NetworkInfo() for get network information

- pkg/config/containers.conf
Fix the indentation of netavark_plugin_dirs
in the containers.conf
> Fix indentation for the containers.conf

- libnetwork/internal/util/validate.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/types/const.go
- libnetwork/types/network.go
This is the changes needed in common to facilitate adding a static route option to podman with the netavark backend.
containers/netavark#678
containers/netavark#680
containers/podman#18369
> Static Routes

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/types/const.go
see https://github.com/containers/netavark/pull/698
> netavark: add bclim option for macvlan

- docs/containers.conf.5.md
- pkg/config/containers.conf
https://github.com/containers/podman/issues/18708 points out that user did not understand how to disable detach-keys in containers.conf.
> [CI:DOCS] Document disabling detach-keys

- pkg/retry/retry.go
Sometimes we want to provide our own functions to detect errors or simply wrap the `isRetryable` function, so I add a detect function option in struct `Options` to make it more universal.
> feat: add a function to determine whether a retry is necessary when error occured

- libnetwork/netavark/config_test.go
- libnetwork/types/define.go
- libnetwork/util/filters.go
- pkg/util/util.go
By default we should do a standard prefix match.
See https://github.com/containers/podman/issues/18471 for context.
Also use the c/storage regex package to only compile the regex when needed.
> libnetwork: handle id filter better

- libimage/pull.go
Currently if you setup additional stores and pull the same image that exists in additionalstore, podman ends up reporting the ID twice.
Fixes: https://github.com/containers/podman/issues/18647
> When using additional stores, report id only once

- libnetwork/etchosts/ip.go
- libnetwork/util/ip.go
I want to use this function in both podman and buildah, move it to the util package as it is not specific to etchosts and export it.
> libnetwork/util: export GetLocalIP()

- libnetwork/pasta/pasta.go
Mostly copied from podman/libpod/networking_pasta_linux.go, this should
be moved to common so that we can use it in buildah as well.
I changed the function parameter to accept a single struct with all
options so that we can extend it when needed without breaking the API
The Container type is libpod/podman specific and not available here so
we only use the values we really need here.
Also I removed "pasta" from the function and constant name as this will
now be used as pasta.Setup() so it would be redundant.
> libnetwork: add pasta package to start pasta

- libnetwork/etchosts/hosts.go
See: https://github.com/containers/podman/pull/18936/files#diff-2c925d6ff6f9b6848d4c49e021e3ca1cc2641d631b871f1a59279a70fc4314deR621
> Ref: https://github.com/containers/podman/pull/18936
> refactor(hosts): export hostContainersInternal variable

- libnetwork/internal/util/parse.go
- libnetwork/internal/util/parse_test.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
The isolation is only enabled when both bridges are in `--opt isolate=true` mode.
This means it is possible to communicate with non-isolated and isolated.
So we adds `--opt isolate=strict` option to deny communication, even with non-isolated and isolated.
Passing this option to netavark creates iptables rules for strict isolation.
> libnetwork/netavark: add isolate option 'strict'

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
> config: add CompressionLevel to containers.conf

- libimage/layer_tree.go
Make operating on the layer tree more resilient towards parallel image removals by checking for unknown-image errors.  This partially fixes below linked BZ.
At the time of writing, I do not have a reliable easy (and short running) reproducer.  Hence, I suggest to merge this change without tests and rely on either Podman CI (which doesn't have a reliable test yet either) and the QE team (will be informed).
BZ: bugzilla.redhat.com/show_bug.cgi?id=2216700
@Luap99 @giuseppe @rhatdan PTAL
> layer tree: be more resilient

- pkg/hooks/exec/exec.go
- pkg/hooks/exec/exec_test.go
- pkg/hooks/exec/runtimeconfigfilter.go
- pkg/hooks/exec/runtimeconfigfilter_test.go
For fixing the wrong cwd bug in podman:
https://github.com/containers/podman/issues/18907
Basically this is the same as #1514, but instead of changing the signature of function, we create a new one with options struct and mark the old one as deprecated
> Add cwd argument for hooks exec Run func (API break-free version)

- libimage/image.go
- libimage/layer_tree.go
Commit 97961a6ad1df took a first stab at making operating on the layer
tree more resilient by detecting unknown-image errors.  Testing in
containers/podman/pull/18980 revealed that we also need to detect
unknown-layer and -size errors as well.
Move the errors checks into a convenience function and update the
relevant call sites to facilitate future changes.  Export the
function since Podman needs the very same checks when operating
on images, for instance, when looking up image labels.
> layer tree: handle more errors

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Users want to update the secret used within containers, without destroying the secret and recreating it.
Partial fix for #18667
> Add Replace option to secret store

- pkg/servicereaper/service.go
This is needed to support 'podman system service'.
> pkg/servicereaper: build this for FreeBSD as well as Linux

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
We decided that podman secret create --replace should match behaviour of podman container create --replace, so the ID should change.
> Change secrets Replace to modify the ID

- pkg/configmaps/configmaps.go
- pkg/configmaps/configmaps_test.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
The Kubernetes documentation states that the name of these resources much be a DNS subdomain name, which it defines[1] as being up to 253 characters.
Following the referenced RFC it does appear that the name should be further restricted to require the 253 characters be made up of multiple of multiple 63-character labels separated by dots. The Kubernetes[2] validation code does not apply this label restriction though, and will accept names longer than 63 characters.
This commit adjusts the length limits to match.
[1]: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
[2]: https://github.com/kubernetes/apimachinery/blob/6b1428efc73348cc1c33935f3a39ab0f2f01d23d/pkg/util/validation/validation.go#L215
Completes: …
> Relax name length restriction for Secrets/ConfigMaps.

- libimage/image.go
To fix a BZ on auto-updates, we need to improve the system tests. To improve the system tests, we need to use the existing test infrastructure.  To use the existing test infrastructure, we need to be able to skip TLS verification in tests.  To be able to skip TLS verification in the tests, we need a new --tls-verify flag for podman-auto-update.  And for that to work, we need a way to pass that down to libimage when checking if there's a new image on the registry.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2218315
@TomSweeneyRedHat @Luap99 PTAL
Needed to backport https://github.com/containers/podman/pull/19092 to Podman v4.6.  I did not bump the version as I also want to backport https://github.com/containers/common/pull/1505 (not yet merged) to the v0.55 branch.
> [v0.55] libimage: HasDifferentDigest: add InsecureSkipTLSVerify option

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
> Remove constraints on secret name

- docs/Containerfile.5.md
Update documentation to include information on naming a build stage using `AS <name>`  and using `COPY --from=<name>` to copy files from a previous stage.
Update `COPY` documentation with the `--chown` and `--chmod` parameters.
> Update from and copy documentation

- pkg/ssh/utils.go
- pkg/ssh/utils_test.go
This removes logic which forces the socket path (if present) to start with "/run" and uses (*URL).String to reconstruct the URI after applying port and user policy. Fixes #1551.
> pkg/ssh: simplify ssh.Validate

- libimage/filters.go
- libimage/filters_test.go
- libimage/image.go
- libimage/image_test.go
- libimage/manifest_list.go
- libimage/normalize.go
- libimage/normalize_test.go
- libimage/pull.go
- libimage/runtime.go
When looking up an image by digest, make sure that the entire repository
of the specified value is considered.  Previously, both the repository
and the tag have been ignored and we looked for _some_ image with a
matching digest.
As outlined in #1248, Docker stopped ignoring the repository with
version v20.10.20 (Oct '22) which is a compelling reason to do the same.
To be clear, previously `something@digest` would look for any image with
`digest` while `something` is entirely ignored.  With this change, both
`something` and `digest` must match the image.
This change breaks two e2e tests in Podman CI which relied on the
previous behavior.  There is a risk of breaking users but there is a
strong security argument to perform this change:  if the repository does
not match the (previously) …
> libimage: harden lookup by digest

- libimage/filters.go
- libimage/filters_test.go
- libimage/image.go
- libimage/image_test.go
- libimage/manifest_list.go
- libimage/normalize.go
- libimage/normalize_test.go
- libimage/pull.go
- libimage/runtime.go
- version/version.go
Backport of https://github.com/containers/common/pull/1505/
@Luap99 @flouthoc PTAL
> 0.55 backports plus bump to v0.55.3

- libnetwork/internal/util/util.go
- libnetwork/netavark/config_test.go
If no name is given we have to set a free one, however the logic was
broken since the beginning due some copy paste. This function as the
name suggests must return all network names so we know to not reuse an
existing one.
I just found this by accident no user ever reported this in almost two
years. This likely means no one uses the automatic names and everybody
set's their own name on the cli instead.
> libnetwork: correctly assign free names

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Podman run and podman create use the "," as a separator when parsing secrets. If a secretname contained a "," then this parsing would get confused.
> Secret names can not container ","

- libimage/filters.go
- libimage/filters_test.go
- libimage/image.go
- libimage/runtime.go
This is a set of small cleanups on top of #1505. Apart from the first commit, they should not change behavior, and are not worth backporting.
See individual commit messages for details.
> Beautify lookup after #1505

- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_freebsd.go
- pkg/config/config_linux.go
- pkg/config/config_test.go
- pkg/config/config_windows.go
- pkg/config/default.go
This fixes a regression in
https://github.com/containers/podman/pull/19241 which quite reasonably assumed that the default image volume mode from pkg/config was correct.
> Change default image volume mode to "nullfs" on FreeBSD

- libnetwork/etchosts/hosts.go
- libnetwork/etchosts/hosts_test.go
This change adds support for the special IP designator `host-gateway` to the etchosts package.
The first part of fixing https://github.com/containers/podman/issues/14390 as mentioned in https://github.com/containers/podman/pull/14392#pullrequestreview-988593151
> libnetwork: Add support for host-gatway

- pkg/util/util.go
The `dpkg -S` call is _really_ slow, taking some 500ms per call.
```console
$ time dpkg -S /usr/bin/podman
podman: /usr/bin/podman
real	0m0,583s
user	0m0,481s
sys	0m0,100s
```
Using `dlocate -F` is better, still not fast but tolerable (grep)
```console
$ time dlocate -F /usr/bin/podman
podman: /usr/bin/podman
podman: /usr/bin/podman-remote
real	0m0,099s
user	0m0,072s
sys	0m0,034s
```
This a problem for podman version and info, which calls PackageVersion a lot (more than 10 times)
When using a database, like rpm, there is no particular overhead. But when using files: 5 seconds
> Use dlocate where available, instead of dpkg search

- pkg/config/containers.conf-freebsd
- pkg/config/default.go
I added this support to ocijail a while ago but forgot to change the compiled-in default since I was overriding the value in my containers.conf.
> pkg/config: Add ocijail to the RuntimeSupportsJSON list

- pkg/config/config.go
- pkg/config/config_local_test.go
This check as part of validation errors out in conditions where Netavark is used instead of CNI which is rather misleading. Removing this check from Validation (early on) and expecting it to fail closer to time-of-use.
Closes https://github.com/containers/podman/issues/19327
> config: rm cni plugins dir check

- pkg/ssh/ssh_test.go
- pkg/ssh/utils.go
Fixes: https://github.com/containers/podman/issues/19162
> Default to port 22 when dialing

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
We want to allow HPC Customers and others to specify mounts inside of containers.conf, so that they can have a default list of mounts into all of thier containers.
> Allow mounts to be specified in containers.conf

- go.mod
- go.sum
- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/multiple.go
- vendor/github.com/containers/image/v5/copy/single.go
- vendor/github.com/containers/image/v5/docker/policyconfiguration/naming.go
- vendor/github.com/containers/image/v5/internal/set/set.go
- vendor/github.com/containers/image/v5/transports/alltransports/alltransports.go
- vendor/github.com/vbatts/tar-split/archive/tar/reader.go
- vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
- vendor/github.com/vbatts/tar-split/tar/storage/packer.go
- vendor/modules.txt
`c/image` recently added support for EnsureCompressionVariantsExist, following PR exposes the feature to `c/common` manifests so actual users can use it.
Needs: https://github.com/containers/image/pull/1987
> manifests,push: add support for `AddCompression`

- pkg/config/config.go
- pkg/config/config_local.go
It reported unused functions and I do not know how those happened.
> pkg/config: fix lint reports

- docs/containers.conf.5.md
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
- pkg/hooks/exec/exec_test.go
This should only be done in container-engines that are using a terminal.
Reverts: https://github.com/containers/common/pull/267
Related to : https://github.com/containers/podman/issues/19264
> We don't want TERM environment turned on by default

- libimage/manifest_list.go
Podman uses different API for pushing manifest list than buildah, add `AddCompression` to ManifestPushOptions, which is implemented here: https://github.com/containers/common/pull/1585
Tests are added here: https://github.com/containers/common/pull/1585
> libimage/ManifestPushOptions: add `AddCompression` for `Manifest.PushOptions`

- libnetwork/etchosts/hosts.go
- libnetwork/etchosts/hosts_test.go
Some tools hard code the `host.docker.internal` dns name so it is not possible to run them with podman right now. Adding the entry is simple so we should support it for better compatibility.
see containers/podman#19361
> libnetwork/etchosts: add docker.internal dns entries

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/default.go
- pkg/ssh/connection_golang.go
- pkg/ssh/types.go
Add 2 new fields to EngineConfig `Farms` and `DefaultFarm` for the podman buildfarm feature work.
Also update the ssh connection code to be able to add a new connection to a new or existing farm when the `--farm` is set in `podman system connection add`.
PR https://github.com/containers/podman/pull/19358 will vendor this in.
> Add Farms to config

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
Remove the zstd:chunked encryption algorithm from the docs and the containers.conf file.  This is aimed for RHEL 8.9/9.3 and it will not be supported there.
> [v0.55][CI-DOCS] remove zstd:chunked from docs

- pkg/config/default_windows.go
wsl no longer uses this field and for windows using hyperv, it should be set to "testing" like all other providers that use fcos as a base machine image.
> change default machine image for windows

- version/version.go
Bump to v0.55.3.  This will finalize c/common for Podman v4.6.1.  C/storage and c/image will not need a dance step.
> Bump to v0.55.3 

- pkg/config/default_windows.go
change the default windows user to core instead of user; which is what WSL uses.  WSL will need to hardcode the its value in podman
> default windows machine user change

- go.mod
- go.sum
- libimage/copier.go
- libimage/manifest_list.go
- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
- libimage/push_test.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/multiple.go
- vendor/github.com/containers/image/v5/internal/manifest/oci_index.go
- vendor/github.com/containers/image/v5/pkg/blobinfocache/internal/prioritize/prioritize.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/golang.org/x/exp/slices/cmp.go
- vendor/golang.org/x/exp/slices/slices.go
- vendor/golang.org/x/exp/slices/sort.go
- vendor/golang.org/x/exp/slices/zsortanyfunc.go
- vendor/golang.org/x/exp/slices/zsortordered.go
- vendor/golang.org/x/net/html/render.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/modules.txt
* Bump c/image to `v5.26.1-0.20230807184415-3fb422379cfa`
* libimage/copier: wire ForceCompressionFormat for image copy
* manifest: add support ForceCompressionFormat
ForceCompressionFormat allows end users to force selected compression format (set in DestinationCtx.CompressionFormat) which ensures that while copying blobs of other compression algorithms are not reused.
See: https://github.com/containers/image/pull/2068 for more details.
> libimage: add support for `ForceCompressionFormat` for image `copier` and `manifest`

- pkg/config/default.go
- pkg/config/default_linux.go
- pkg/config/default_unsupported.go
- pkg/config/default_windows.go
small refactoring for #1603 adn #1608 where we no longer have operating system differences.
> cleanup getDefaultMachineUser|Image

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/config_remote_test.go
- pkg/config/config_suite_test.go
- pkg/config/config_test.go
- pkg/config/default.go
- pkg/config/modules.go
- pkg/config/modules_test.go
- pkg/config/new.go
- pkg/config/testdata/modules/etc/containers/containers.conf.modules/first.conf
- pkg/config/testdata/modules/etc/containers/containers.conf.modules/fourth.conf
- pkg/config/testdata/modules/etc/containers/containers.conf.modules/second.conf
- pkg/config/testdata/modules/etc/containers/containers.conf.modules/sub/etc-only.conf
- pkg/config/testdata/modules/etc/containers/containers.conf.modules/third.conf
- pkg/config/testdata/modules/home/.config/containers/containers.conf.modules/first.conf
- pkg/config/testdata/modules/home/.config/containers/containers.conf.modules/second.conf
- pkg/config/testdata/modules/home/.config/containers/containers.conf.modules/sub/first.conf
- pkg/config/testdata/modules/home/.config/containers/containers.conf.modules/third.conf
- pkg/config/testdata/modules/override.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/fifth.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/first.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/second.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/sub/first.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/sub/share-only.conf
- pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/third.conf
Add a new concept to containers.conf called "modules".  A "module" is
a containers.conf file located at a specific directory.  More than one
modules can be loaded in the specified order, following existing
override semantics.
There are three directories to load modules from:
- $CONFIG_HOME/containers/containers.conf.modules
- /etc/containers/containers.conf.modules
- /usr/share/containers/containers.conf.modules
With CONFIG_HOME pointing to $HOME/.config or, if set, $XDG_CONFIG_HOME.
Absolute paths will be loaded as is, relative paths will be resolved
relative to the three directories above allowing for admin configs
(/etc/) to override system configs (/usr/share/) and user configs
($CONFIG_HOME) to override admin configs.
Also move some functions from config.go for locality. …
> containers.conf: implement modules

- pkg/cgroups/cgroups_linux.go
port Commit 12a939e1048a (cgroups: use SessionBusPrivateNoAutoStartup) from cgroups.go to cgroups_linux.go
do not start up a dbus daemon if it is not already running.
[NO NEW TESTS NEEDED] the fix is in a dependency.
> cgroups_linux: use SessionBusPrivateNoAutoStartup

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/apparmor/internal/supported/supported.go
Related issues:
- https://github.com/containers/common/issues/958 (closed in https://github.com/containers/common/pull/960, reverted by https://github.com/containers/common/pull/969)
- https://github.com/containers/podman/issues/15874
This PR re-implements https://github.com/containers/common/pull/960, allowing containers to execute under a specified AppArmor profile when run rootlessly. In addition, it changes the default AppArmor profile used by containers to `unconfined`.
The current implementation of Podman compiles and loads the default AppArmor profile at runtime. However, this is incompatible with providing rootless AppArmor compatibility, as loading an AppArmor profile requires root privileges. As discussed in https://github.com/containers/podman/issues/15874, the ideal mechanism …
> Allow rootless AppArmor

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_linux.go
- pkg/apparmor/internal/supported/supported.go
Revert the two commits from #1572; it was merged prematurely.
> Revert #1572

- libnetwork/cni/run_freebsd.go
This allows us to use a single jail for containers with networking since CNI can initialise the network without needing a separate jail to own the network namespace.
> libnetwork/cni: use 'ifconfig -j' on FreeBSD if it is supported

- libimage/copier.go
- libimage/pull.go
Set the `EXTEND_TIMEOUT_USEC` over DBUS when pulling an image from a registry and when running under systemd.  This will prevent a frequent issue when running Quadlets and exceeding the default systemd start timeout of 90 seconds when pulling the image takes too long.
Fixes: containers/podman/issues/18353
Entirely untested but it may aid in deciding what to do with containers/podman/issues/18353.
@rhatdan @ygalblum WDYT?
> libimage: pull: increase timeout running under systemd

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_default.conf
Allows users to set default value of `AddCompression` to Engine table so users of `podman` and `buildah` can use https://github.com/containers/buildah/pull/4912 by default.
Closes: https://github.com/containers/buildah/pull/4912#issuecomment-1661105029
> containers.conf: add field for `AddCompression` to Engine table

- libimage/define/manifests.go
- libimage/manifest_list.go
These structs are (for better or worse) a part of Podman's API, so `podman-remote` needs to include the subpackage that defines them - which is all of `libimage` (and `c/image/v5/copy`) right now.
Instead, move them to `libimage/define`.
Alternatively, maybe Podman's API should not directly depend on (unstable) c/common types?!
Only moves unchanged code, should not change behavior.
> Move libimage.ManifestList{Descriptor,Data} to libimage/define

- libimage/pull.go
- libimage/pull_test.go
When pulling from an OCI source, make sure to preseve the optional name. For instance, a `podman pull oci:/tmp/foo:quay.io/foo/bar:latest` should pull the image and name it `quay.io/foo/bar:latest`.
While at it, also fix a bug when pulling an OCI without the optional name.  Previously, we used the path to name the image which will error in most cases due to invalid characters (e.g., capital ones).  Hence, apply the same trick as for the `dir` transport and generate a sha.
> libimage: preserve optional name when pulling from OCI transport

- .golangci.yml
golangci-lint has a number of helpful linters and new ones are being continuously added.  Instead of enabling only a minimal subset of these linters, enable all by default and - for now - disable failing ones. This allows us to make use of new linters on updates and to selectively enable those we deem useful.
> golangci.yml: enable all, disable failing linters

- pkg/auth/auth.go
- pkg/util/util.go
- pkg/util/util_supported.go
- pkg/util/util_windows.go
This commit restores the terminal state in case the program is interrupted while being in password read mode. This ensures the terminal remains usable, also if the password input is being cancelled
This PR provides a solution for https://github.com/containers/podman/issues/17372
Signed-off-by: Felix Niederwanger <felix.niederwanger@suse.com>
> Add restore handler for password input

- libimage/filter/filter.go
- libimage/search.go
This allows podman to import them on the remote client without needing the full libimage.
Based on Miloslav's work: https://github.com/containers/podman/pull/19718
> libimage: split out search filters

- pkg/config/default.go
Replacing 'eturns' with 'returns'
> Fix typo in comment

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
> Fix specification of unix:///run

- libimage/layer_tree.go
Layer tree expectes to form a relation between child and parent instances, however it expects an instance from manifest list which is empty, following expectation is not possible and will always resuilt in error.
Closes: https://github.com/containers/podman/issues/19860
Image without layer cant be built in libimage, and `podman save` automatically malforms such image so no such external image can be loaded.
> libimage/layer_tree: if parent is empty and a manifest list then ignore check.

- libnetwork/cni/network.go
- libnetwork/netavark/network.go
- libnetwork/util/filters.go
- pkg/auth/auth.go
- pkg/detach/copy.go
- pkg/filters/filters.go
- pkg/password/password_supported.go
- pkg/password/password_windows.go
- pkg/util/util.go
- pkg/util/util_supported.go
- pkg/util/util_windows.go
- pkg/version/version.go
Fixes: https://github.com/containers/common/issues/1654
> Split up util package into pkg/password, pkg/copy, pkg/version

- pkg/config/config_local_test.go
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
1 CPU core typically is not enough for most use cases, so we default to available cores/2 for new machines.
Fixes: https://github.com/containers/podman/issues/17066
> Default machine CPUs to Cores/2

- pkg/config/config.go
- pkg/config/default.go
Let callers (i.e., Podman) decide which defaults to chose.  This way,
callers know when to override defaults (i.e., when the values are
empty).
There's also another commit removing unused fields.
Opened as a draft, as this needs a vendor-PR in Podman.
> pkg/config: do NOT set StaticDir and VolumeDir

- pkg/filters/filters.go
- pkg/filters/filters_test.go
Adds a proper way to match on negated label filters (label!). (label!) filters. The current logic used is to do !MatchLabelFilter() but this results in chained negated labels being ORed together instead of ANDed.
> Implement negated label match function

- libnetwork/cni/network.go
At this point we already read the config file but here we have to get timestamp here so we can hit another ENOENT if it was removed in the meantime. Just ignore this and do not log an error as this is normal behavior when another process is deleting a network in parallel.
Fixes containers/podman#20173
> libnetwork/cni: ignore ENOENT while reading networks

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/testfiles/valid/vrf.json
- libnetwork/types/const.go
Add support for the vrf option of the netavark network stack that was introduced on https://github.com/containers/netavark/commit/4b6d5ab26316b007779e0a504ab9a90a21b2e2dc.
> Add support for vrf option on netavark

- libimage/manifest_list.go
- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
manifest push API must implement and leverage `retry` logic similar to `image push` with similar defaults.
Closes: https://github.com/containers/common/issues/1664
> libimage: implement `retry` logic for  `manifest push`

- libnetwork/util/filters.go
Changes `createPruneFilterFuncs` to use `filters.MatchNegatedLabelFilters` instead of `!filters.MatchLabelFilters` when matching on negated labels (label!).
> Use MatchNegatedLabelFilter function for networks

- pkg/subscriptions/subscriptions.go
Make sure /etc/crypto-policies/config is bind mounted from the host so it does contain the proper FIPS value and a reinstall of crypto-policies-scripts does not overwrite the existing files with the default config.
Fixes https://issues.redhat.com/browse/RHEL-9836
> pkg/subscriptions: add /etc/crypto-policies/config in fips mode

- libimage/filters.go
- libimage/filters_test.go
- libimage/image.go
The id and digest filters for podman images was broken as it would only match on the full ID or Digest, so when users would give a substring of either not results would be given even though there were matches.
Fix to check on prefix now instead.
Helps fix https://github.com/containers/podman/issues/19966
> Fix ID and Digest filters

- internal/attributed-string-slice/attributed_string_slice.go
- internal/attributed-string-slice/attributed_string_slice_test.go
As discussed in https://github.com/containers/podman/issues/20000, we need an opt-in mechanism to _append_ string arrays during the loading sequence of containers.conf files.
At the moment, existing fields/data will be overriden with each loaded config that sets the specified field/option.  The TOML (toml.io) config format does not allow for attributing fields and structs are implicitly represented as "tables".  I wanted to extend a string array with a simple boolean field, for instance:
```TOML
env=["FOO=bar"]
env.append=true
```
TOML doesn't suppor tthe upper idea as it's not a properly formatted table.  So I looked for alternatives and found that TOML supports so-called "mixed-type arrays".  As the same suggests, such arrays allow for including more than one type and that seemed like a …
> POC: appendable string arrays in containers.conf

- pkg/apparmor/apparmor_linux.go
Copied from github.com/moby/moby who already has a fix for it. Tested manually on a Ubuntu 23.10 (beta) VM.
Fixes: #containers/podman/issues/20278
> apparmor: fix parsing beta/alpha version

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/db_backend.go
- pkg/config/db_backend_test.go
- pkg/config/default.go
Podman should default to sqlite for new installs, however to not break upgrades we should detect if a boltdb database exists and use that in such case. Now in order to distinguish between an explicitly set "sqlite" and "boltdb" and nothing set we use an empty default.
With that podman can know if we really should use the default or if it was configured for a db explicitly. The actual detection logic must be implemented in podman as we only know the file locations there.
This commit also drops the unused StateType as this was not used at all.
> pkg/config: use empty default for db_backend

- libimage/platform.go
Add compatibility interfaces for items which have been moved from the main libimage package to its new platform subpackage.
> libimage: add compat interfaces for the new platform subpackage

- libimage/history.go
- libimage/history_test.go
Computing the history did not walk the layers correctly.  Fix that and try to improve the code to make it easier to read and maintain for future pairs of eyes.
A regression will be added to the Podman PR vendoring this change.
Fixes: containers/podman/issues/20375
> libimage: fix computing history

- libimage/image.go
- libimage/image_test.go
The c/storage SetNames API is depracated because it is not race free to first get the list of names and then append our new name then write the full list back. Instead a better Add/RemovesNames API has been added.
Tag and Untag should use these to prevent race conditions that can be easily reproduce using podman tag in parallel. Tests have been added to ensure it is working correctly.
Fixes https://github.com/containers/podman/issues/17515
> libimage: support parallel tag/untag

- libimage/image.go
- libimage/image_test.go
podman untag should error out of a name is given which does not exists for the given image. This regression was added in commit 465dd3e8be.
There was even a test which meant to check for it but unfortunately it did not actually check for what it should. The doNotExist check failed early to the upper case in the repo name.
The tests have been updated to check for actual error messages to show ensure it is failing for the right reason.
This also showed that `normalizing name` message was included twice so I removed one case to not stutter.
Fixes 465dd3e8be ("libimage: support parallel tag/untag")
> libimage: Untag should error for non existent name

- libimage/copier.go
When trying an invalid image DockerReference maybe nil
This change addresses: https://github.com/containers/podman/issues/20432
> Copier: use StringWithinTransport instead of DockerReference

- pkg/config/default.go
Podman and Buildah have gone out of sync, this will allow us to make sure they stay in sync.
> Add masked paths and readonly paths to config

- docs/containers.conf.5.md
Document how the overriding behavior during the loading sequence can be changed to appending.
> containers.conf: append to string arrays

- pkg/cgroups/cgroups_linux.go
- pkg/cgroups/cgroups_supported.go
- pkg/cgroups/utils_linux.go
Take this oppurtunity to remove Get prefix on functions in cgroups.
> UserConnection is used by non linux platforms

- pkg/cgroups/cgroups_unsupported.go
> cgroups: provide UserConnection for non-linux platforms

- pkg/apparmor/apparmor_linux.go
Copied from github.com/moby/moby who already has a fix for it. Tested manually on a Ubuntu 23.10 (beta) VM.
Fixes: #containers/podman/issues/20278
Cherry-pick via v0.55, for CRI-O v1.28.x (see https://github.com/cri-o/cri-o/blob/release-1.28/go.mod#L23)
> [v0.55.x][git cherry-pick 5c81adc] apparmor: fix parsing beta/alpha version

- pkg/parse/parse.go
Requries crun 1.11+ where the option is called `copy-symlink`.
Required in containers/podman/pull/20356.
> parse: support `no-dereference` mount option

- libimage/inspect.go
… by not doing anything, like with the (much more common) signed schema1 images.
Fixes https://github.com/containers/podman/issues/20156 .
> Fix inspection of unsigned schema1 images

- docs/containers.conf.5.md
- libnetwork/netavark/exec.go
- libnetwork/netavark/network.go
- libnetwork/network/interface.go
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
> Add configurability to Netavark firewall driver

- pkg/config/config_darwin.go
- pkg/config/default.go
- version/version.go
Backport https://github.com/containers/common/pull/1754 and cut new release so podman 4.8.2 can vendor this.
> [0.57] backport #1754  + v0.57.1

- pkg/config/config_local.go
glibc supports the environment variable as additional search path. We now add this to the config validation to allow runtimes to search that path as well.
> Allow searching `$TZDIR` for timezone data

- pkg/config/config_local.go
The TZDIR environment variable override the lookup paths and does not append them. This patch fixes that behavior and is a follow-up on:
https://github.com/containers/common/pull/1772
Ref: https://github.com/containers/podman/pull/21063#discussion_r1432809463
cc @edsantiago
> Use `TZDIR` as override lookup path

- go.mod
- libnetwork/cni/cni_conversion.go
- libnetwork/cni/config.go
- libnetwork/etchosts/hosts.go
- libnetwork/internal/util/bridge.go
- libnetwork/internal/util/util.go
- libnetwork/netavark/config.go
- libnetwork/netavark/run.go
- libnetwork/resolvconf/resolv.go
- libnetwork/util/filters.go
- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
- pkg/cgroups/cgroups_linux.go
- pkg/config/config.go
- pkg/configmaps/configmaps.go
- pkg/configmaps/filedriver/filedriver.go
- pkg/secrets/filedriver/filedriver.go
- pkg/secrets/secrets.go
- pkg/ssh/connection_golang.go
- pkg/util/util.go
This PR replaces raw loops with functions from [slices](https://pkg.go.dev/golang.org/x/exp/slices) and [maps](https://pkg.go.dev/golang.org/x/exp/maps) packages. By doing this, we are simplifying our code base, enhancing readability, and improving maintainability.
Also, deprecate unneeded function `util.StringInSlice` that can be replaced with [`slices.Contains`](https://pkg.go.dev/golang.org/x/exp/slices#Contains).
When we upgrade to Go 1.21, `golang.org/x/exp/slices` will be replaced by [`slices`](https://pkg.go.dev/slices) from std.
> Refactor: replace raw loops with funcs from slices and maps

- .github/workflows/validate.yml
- libimage/runtime.go
This PR fixes two `staticcheck` lint issues `SA1019: storageTransport.Transport.GetStoreImage is deprecated`.  Additionally, change `lint` CI step to show all issues.
Fixes failed action https://github.com/containers/common/actions/runs/7417114742/job/20183119311.
> Fix staticcheck issues; show all lint issues in CI

- libimage/corrupted_test.go
- libimage/filters_test.go
- libimage/history_test.go
- libimage/image_test.go
- libimage/import_test.go
- libimage/load_test.go
- libimage/manifest_list_test.go
- libimage/manifests/manifests_test.go
- libimage/pull_test.go
- libimage/push_test.go
- libimage/remove_test.go
- libimage/runtime_test.go
- libimage/save_test.go
- pkg/chown/chown_test.go
- pkg/configmaps/configmaps_test.go
- pkg/configmaps/filedriver/filedriver_test.go
- pkg/hooks/exec/exec_test.go
- pkg/secrets/filedriver/filedriver_test.go
- pkg/secrets/passdriver/passdriver_test.go
- pkg/secrets/secrets_test.go
- pkg/secrets/shelldriver/shelldriver_test.go
- pkg/supplemented/supplemented_test.go
- pkg/sysinfo/sysinfo_linux_test.go
This PR refactors tests by removing code lines. Changes:
- Use [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir) instead of [`os.MkdirTemp`](https://pkg.go.dev/os#MkdirTemp). `T.TempDir` automatically removes the temporary directory.
- Remove `defer cleanup()` that previously calls `os.RemoveAll(tempDir)`.
- Move global variable `var opts map[string]string` to `setup()`.
- Use [`T.Cleanup`](https://pkg.go.dev/testing#T.Cleanup) for executing `runtime.Shutdown(true)`.
> Simplify tests with testing.TempDir instead of os.MkdirTemp

- internal/attributedstring/slice.go
- libimage/manifest_list_test.go
- libnetwork/cni/cni_types.go
- libnetwork/cni/run.go
- pkg/cgroups/cgroups_linux.go
- pkg/config/default.go
- pkg/secrets/secrets_test.go
This PR refactors initialization for simple maps by using short declaration syntax. The syntax is more readable and shorter for simple maps.
> Refactor map init with short declaration syntax

- .golangci.yml
- internal/attributedstring/slice.go
- libnetwork/cni/cni_conversion.go
- libnetwork/cni/cni_types.go
- libnetwork/cni/run.go
- libnetwork/netavark/exec.go
- libnetwork/netavark/ipam.go
- libnetwork/netavark/netavark_suite_test.go
- libnetwork/slirp4netns/slirp4netns.go
- pkg/apparmor/internal/supported/supportedfakes/fake_verifier_impl.go
- pkg/formats/formats.go
- pkg/formats/templates.go
- pkg/report/formatter.go
- pkg/report/template.go
- pkg/ssh/types.go
- pkg/systemd/systemd_linux.go
The PR replaces `interface{}` with the alias `any` for consistency (`interface{}` - 43 occurrences, `any` - 63). It's done by running `gofmt -w -r "interface{} -> any" -l .`. And enables `gofmt`'s rewrite rule to ensure `interface{}` won't be committed.
> chore: replace 'interface{}' with 'any' for consistency

- pkg/apparmor/apparmor_linux.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.26, part of OpenShift 4.13 release.
None
None
```release-note
None
```
> [release-0.52] [crio-1.26] Cherry-pick changes from containers/common/pull#1689

- pkg/apparmor/apparmor_linux.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
None
None
```release-note
None
```
> [release-0.52] [crio-1.25] Cherry-pick changes from containers/common/pull#1689

- pkg/apparmor/apparmor_linux.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.28, part of OpenShift 4.15 release.
None
None
```release-note
None
```
> [release-0.55] [crio-1.28] Cherry-pick changes from containers/common/pull#1689

- pkg/apparmor/apparmor_linux.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.24, part of OpenShift 4.11 release.
None
None
```release-note
None
```
> [release-0.46] [crio-1.24] Cherry-pick changes from containers/common/pull#1689

- pkg/apparmor/apparmor_linux.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.27, part of OpenShift 4.14 release.
None
None
```release-note
None
```
> [release-0.53] [crio-1.27] Cherry-pick changes from containers/common/pull#1689

- pkg/subscriptions/subscriptions.go
quay.io/buildah/stable and quay.io/podman/stable images now forward the mounts.conf subscriptions into their containers but if the host is not using subscription manager these pass throughs warn about missing files, which is not useful to the user.
fixes: https://github.com/containers/podman/issues/20812
> Drop warning to info on missing content from mounts.conf

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/docker_transport.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
As the title says.  
Bumping c/image to 5.29.1, then common in this branch to 0.57.2, then to 0.57.3-dev.
This in preparation for the Podman 4.9 release on RHEL 8.10/9.4
> Bump c/image to v5.29.1, common to 0.57.2, then to common 0.57.3-dev

- docs/containers.conf.5.md
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
> containers.conf: add crun-vm as a runtime

- libimage/filters.go
- libimage/filters_test.go
- pkg/filters/filters.go
- pkg/filters/filters_test.go
Fix the libpodFilters parsing to ensure that
we get a list of filters in the form of key=value.
This matches what the docker endpoint does for filter
parsing as well.
When multiple filters are given, only return objects
that match all the filters given by the user.
This matches Docker behavior.
> Fix image filters parsing

- libimage/manifests/manifests_test.go
Use `assert.NoError`/`assert.Error` instead of `assert.Nil`/`assert.NotNil` when the variable being checked is an `error` result.
> libimage/manifests/manifests_test.go: use assert.NoError

- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
Add SetMediaType()/MediaType() and SetArtifactType()/ArtifactType() for modifying information about instances in the list.
> pkg/manifests.list: add SetMediaType(), SetArtifactType()

- pkg/manifests/manifests.go
The OCI image index structure has grown a few new fields since the last time we looked, so we should be paying attention to whether any of them are being used when deciding if we need to use the OCI format instead of the Docker format.
The Docker format also grew a "URLs" field, so we can't use its mere presence as a heuristic any more.
> pkg/manifests.list.preferOCI() learn about some new OCI fields

- pkg/timezone/timezone.go
- pkg/timezone/timezone_unsupported.go
> add ConfigureTimeZone for all Unix based platforms

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local.go
- pkg/config/config_local_test.go
- pkg/config/config_remote.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
Add a new containers.conf attribute to define how to set interface name inside containers.
Related to https://github.com/containers/podman/issues/21313
Signed-off-by: Vikas Goel <vikas.goel@gmail.com>
> New global option interface_name in containers.conf

- libimage/layer_tree.go
Fix panic when running `podman system df` where a `node.layer` is nil.
Fixes https://github.com/containers/podman/issues/20942
> Fix `podman system df` panic

- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_freebsd.go
- pkg/config/config_linux.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
We have not supported type=bind image volumes since pre-1.0 Podman - we phased them out when we added support for actual volumes. Also, our image volume valid modes checker did not even allow the actual default (anonymous). This is technically a breaking change, so it will go into Podman 5.0 - but I strongly doubt anyone is actually using this field if no one has noticed this issue before now.
> Change default image volume mode to "anonymous"

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_darwin.go
- pkg/config/config_freebsd.go
- pkg/config/config_linux.go
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/config_unix.go
- pkg/config/config_windows.go
- pkg/config/connections.go
- pkg/config/connections_test.go
- pkg/config/containers.conf
- pkg/config/new.go
- pkg/ssh/connection_golang.go
- pkg/ssh/connection_native.go
see commits
WIP podman PR https://github.com/containers/podman/pull/21384
> pkg/config: rework system connections and farm storage

- pkg/filters/filters_test.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
If the Platform struct for an OCI instance being added to an image index is empty, set the Platform pointer field in the Descriptor struct to `nil` instead of setting it to point to a Platform struct filled with empty values.  I expect this to be the case for at least some OCI artifacts being added to indexes.
Likewise, if we're updating the Platform for an OCI instance and its value goes to zero, set its pointer to `nil` to avoid the same case.
When reading information back from a descriptor, or setting a field in the Platform struct, don't assume that Platform is (already) set to a non-nil value.
> pkg/manifests.list.AddInstance(): don't set Platform to an empty struct

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/daemon/client.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
As the title says.  Bumping stuff in preparation of Podman v4.9.1
> [v0.57] Bump c/image to v5.29.2, common to v0.57.3, then v0.57.4-dev

- .golangci.yml
- Makefile
- libnetwork/cni/cni_conversion.go
- libnetwork/cni/cni_exec.go
- libnetwork/cni/cni_suite_test.go
- libnetwork/cni/cni_types.go
- libnetwork/cni/config.go
- libnetwork/cni/config_freebsd.go
- libnetwork/cni/config_linux.go
- libnetwork/cni/config_test.go
- libnetwork/cni/network.go
- libnetwork/cni/run.go
- libnetwork/cni/run_test.go
- libnetwork/network/interface.go
- libnetwork/network/interface_cni.go
- libnetwork/network/interface_cni_unsupported.go
- add `cni` build tag to `libnetwork/cni`
- split `libnetwork/network` into multiple files so that cni support can be made optionally available
See also https://issues.redhat.com/browse/RUN-1943
> Gate CNI support behind the `cni` build tag

- pkg/timezone/timezone.go
- pkg/timezone/timezone_linux.go
- pkg/timezone/timezone_unix.go
- pkg/timezone/timezone_windows.go
> Make timezone work on freebsd

- pkg/timezone/timezone_linux.go
I discussed this with @TomSweeneyRedHat on Slack and opened a backport PR to get this functionality in v0.57.
> [0.57] backport: #1775

- pkg/strongunits/config.go
- pkg/strongunits/config_test.go
The code is imported by libhvee from podman which causes a circular dependency which results in big problems[1] when trying to update the podman go module to v5. Port the code over and then libhvee and podman can use the code directly from here.
[1] https://github.com/containers/podman/pull/21469
> import pkg/strongunits from podman

- pkg/manifests/manifests.go
- pkg/manifests/testdata/fedora.index.json
Account for the presence of annotations in the OCI version of an index or list when deciding if the structure should be saved in OCI format. This requires removing an annotation from the test data so that the presence of "features" information for one of its instances will be the deciding factor.
I thought we could get by in #1816 without this, but without it, setting annotations in the index doesn't force us to save it in OCI format, even without any of the indicators present that would force us to use the Docker format, effectively throwing away those annotations.
> pkg/manifests.list.preferOCI(): pay attention to annotations in indexes

- libimage/manifests/manifests.go
After we've dealt with potentially-missing files, don't accidentally return the missing file error.
> libimage/manifests.LoadFromImage(): don't return a stale error

- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
In the case where AddArtifact() is given both a file name and a configuration descriptor, pay attention to both, using the media type from the descriptor, and setting the digest and size based on the file's contents.
Updated a unit test to exercise this combination.
> libimage/manifests.list.AddArtifact(): handle descriptor+file

- pkg/config/connections.go
- pkg/config/connections_test.go
As per Dan's feedback .conf sounds like a config file that can edited but this file is really only managed by podman so just use the .json suffix to make it more clear hopefully.
> pkg/config: rename podman-connections.conf to .json

- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
- pkg/supplemented/supplemented.go
When saving artifacts to OCI layout directories to use as supplemental references, use a different directory for each artifact(!)
When supplementing a reference in CopySpecificImages mode, only mark a supplemental reference as the source for a specified instance if it actually corresponds to the instance's digest.
If an artifact manifest doesn't have any file layers, remember to catalog the empty descriptor that we add to its layer list to keep it from being empty, as recommended.
Extend libimage/manifests.TestReference() to ensure that we're able to copy everything that we should be able to copy.
> Handle multiple artifacts correctly

- pkg/ssh/connection_golang.go
- pkg/ssh/connection_native.go
- pkg/ssh/ssh.go
- pkg/ssh/ssh_test.go
These changes are needed to support https://github.com/containers/podman/pull/21420
Supporting an input file for SSH commands can avoid the use of temporary files.
> Support the execution of SSH commands with optional input.

- docs/containers.conf.5.md
- pkg/config/containers.conf
The existing documentation only describes containers and pods, but volumes also consume locks as well (and have for years), so update documentation to reflect that.
Fixes RHEL-24333
> [CI:DOCS] Update documentation to note that volumes use locks.

- libimage/manifest_list.go
- libimage/manifest_list_test.go
- libimage/manifests/manifests.go
* Add a libimage.ManifestList.AddArtifact() method.
* Add IndexAnnotations and Subject to libimage.ManifestListAnnotateOptions, for setting annotations on the index itself, and the index's subject, respectively.
* In libimage/manifests.list.AddArtifact(), if the subject has an artifactType in its manifest, add its value to the subject descriptor.
> libimage.ManifestList: add AddArtifact()

- pkg/subscriptions/subscriptions.go
- pkg/umask/umask.go
- pkg/umask/umask_test.go
This call will be done in parallel which messes up the umask on CRI-O on container creation. We now call `chmod` after directory and file creation to enforce the right permissions.
Cherry-picked: d4a3de3ace5f6bc3464aa8c53c04b7e6ac62f3cd
Required for https://github.com/cri-o/cri-o/pull/7775
> [crio-1.26] Don't call `umask` in subscriptions

- pkg/subscriptions/subscriptions.go
- pkg/umask/umask.go
- pkg/umask/umask_test.go
This call will be done in parallel which messes up the umask on CRI-O on container creation. We now call `chmod` after directory and file creation to enforce the right permissions.
Cherry-picked: d4a3de3ace5f6bc3464aa8c53c04b7e6ac62f3cd
Required for https://github.com/cri-o/cri-o/pull/7774
> [crio-1.25] Don't call `umask` in subscriptions

- docs/containers.conf.5.md
The fourth module had a copy-paste error and mistakenly claimed to be number 3.
> containers.conf.5.md: fix append example

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
> Config for Retry and RetryDelay for pulling images

- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
- pkg/machine/machine.go
- pkg/machine/machine_test.go
We now only use the marker file, see pkg/machine.
The advantage of this is that pkg/machine no longer imports pkg/config and we use it in rootlessport which means it will debloat the binary there significantly.
The file approach has been added in podman 4.1 (2 years ago) so basically all machines should have it now and this shouldn't break anything.
> pkg/config: remove deprecated MachineEnabled field

- libimage/pull.go
- libimage/push.go
libimage should be using the settings in containers/pkg/config for Retry and RetryDelay if they were not set by a caller.
[NO NEW TESTS NEEDED] since it would be difficult to test.
> Default Pull/Push to use containers.conf Retry, RetryDelay

- libnetwork/pasta/pasta.go
We want to log pasta warnings/errors even if pasta did not fail to start, however by default it prints a bit to noisy for us. With --quiet we get the things users should care about.
Note right now --quiet defaults to errors only but it should also do warnings based on the discussion with Stefano[1]. However this change is still safe to do right now.
[1] https://archives.passt.top/passt-dev/20240216114304.7234a83f@elisabeth/T/#m42652824644973674e84baf9e0bf1d0e88104450
> libnetwork/pasta: always pass --quiet

- libnetwork/pasta/pasta.go
We pass --no-map-gw to pasta and when run on a system with only localhost resolvers pasta cannot find a valid nameserver in resolv.conf it will print a warning. We do not use the dns functionality so the warning is just bogus to podman users. Let's disable dns which is only used for the dhcp option or --dns-forward which we do not use by default. If a users sets such an option we use them instead.
> libnetwork/pasta: pass --dns none

- docs/containers.conf.5.md
- libimage/push.go
- pkg/config/containers.conf
If user does not specify a compression format and transport is docker-archive of manifesttype is DockerV2Schema2MediaType then we need to force Gzip compression.
This is needed when we transition to zstd or zstd:chunked by default.
> docker-archive/DockerV3Schema2MediaType only support Gzip compression

- docs/containers.conf.5.md
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
We no longer use `testing` as the default image from fcos for machine. Adjust default to "" temporarily, as we're still stablizing the location and images for machine images, but still allow the user to specify a custom image via containers.conf.
> Adjust machine image default

- docs/containers.conf.5.md
- libnetwork/internal/rootlessnetns/netns_linux.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
This makes the code for setting up rootless network namespaces dependent on what the default rootless network provider is, and allows Pasta to be used for traffic forwarding on the rootless netns.
> Allow creation of a rootless netns backed by Pasta

- libimage/events.go
- libimage/pull.go
Fixes: https://github.com/containers/podman/issues/21458
> Report error events on pull failures

- pkg/config/connections.go
- pkg/config/connections_test.go
Add a lock to EditConnectionConfig to make it race free for parallel
modification. It is possible that several podman system connection
commands are called simultaneously so we should read/file in a consistent
way to ensure no modifications are "silently dropped".
A test is added that reliably fails without the lock.
> pkg/config: make EditConnectionConfig race free 

- .github/workflows/validate.yml
- .golangci.yml
- Makefile
- libimage/copier.go
- libimage/filters.go
- libimage/load.go
- libimage/manifests/manifests.go
- libimage/pull.go
- libimage/runtime.go
- libimage/save.go
- libnetwork/internal/util/validate.go
- libnetwork/netavark/config.go
- libnetwork/netavark/testplugin/main.go
- libnetwork/pasta/pasta.go
- libnetwork/slirp4netns/slirp4netns.go
- pkg/auth/auth.go
- pkg/cgroups/cgroups_linux.go
- pkg/cgroups/systemd_linux.go
- pkg/config/default.go
- pkg/filters/filters.go
- pkg/flag/flag_test.go
- pkg/formats/templates.go
- pkg/ssh/connection_golang.go
- pkg/ssh/connection_native.go
- pkg/ssh/ssh.go
- pkg/ssh/utils.go
- pkg/subscriptions/subscriptions.go
- pkg/supplemented/supplemented.go
- pkg/umask/umask_test.go
Adds a couple of new linters with many new warnings:
- perfsprint (fixed in code, excluded for tests)
- revive (fix the problems, disabled the dot import check as we use it for ginkgo)
- inamedparam (disabled because it is opinionated)
- testifylint (great linter but we have like 1000+ issues that I have no time fixing now)
> lint: update golangci-lint to v1.56.2

- .github/workflows/validate.yml
1.19 is eol and likely no longer works to compile new code thus failing all lints jobs that uses go 1.20 or newer features.
To fix that lets update to the latest stable version go 1.22.
> github: bump go version for lint to 1.22

- pkg/subscriptions/subscriptions.go
- pkg/subscriptions/subscriptions_test.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1437 as these changes contain a fix that needs to be backported to CRI-O release 1.26, part of OpenShift 4.13 release.
Related:
- https://github.com/containers/common/pull/1421
- https://github.com/containers/common/pull/1437
None
None
```release-note
None
```
> [release-0.52] [crio-1.26] Cherry-pick changes from containers/common/pull#1437

- pkg/subscriptions/subscriptions.go
- pkg/subscriptions/subscriptions_test.go
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1437 as these changes contain a fix that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
Related:
- https://github.com/containers/common/pull/1421
- https://github.com/containers/common/pull/1437
None
None
```release-note
None
```
> [release-0.52] [crio-1.25] Cherry-pick changes from containers/common/pull#1437

- .golangci.yml
- libnetwork/cni/config_test.go
- libnetwork/cni/run_test.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/ipam_test.go
- libnetwork/netavark/plugin_test.go
- libnetwork/netavark/run_test.go
- pkg/auth/auth_test.go
- pkg/config/config_local_test.go
- pkg/config/config_test.go
- pkg/config/modules_test.go
This linter creates better assertions in ginkgo tests. Fixes were made with `ginkgolinter -fix ./...`.
> lint: enable ginkgolinter

- .cirrus.yml
...and remove the "dnf install podman-plugins", that package no longer exists.
[takeover of #1927 because manual intervention is needed]
> CI: bump VMs to 2024-03-20

- pkg/config/config_test.go
- pkg/config/pull_policy.go
> Simplify PullPolicy handling

- libnetwork/etchosts/ip.go
- libnetwork/internal/rootlessnetns/netns_linux.go
- libnetwork/pasta/pasta_linux.go
- libnetwork/pasta/types.go
- libnetwork/slirp4netns/const.go
- libnetwork/slirp4netns/slirp4netns.go
- libnetwork/util/ip.go
Backport https://github.com/containers/common/pull/1905
Needed to fix https://github.com/containers/podman/issues/22044 in podman 5.0, note this will require a full vendor dance into buildah 1.35 and only then into podman 5.0 branch
> [v0.58] Backport pasta fixes

- pkg/version/version.go
Previously dlocate was only used for half of the process, not both.
* https://github.com/containers/common/pull/1578
It is better to use dlocate for both lookups, and avoid dpkg here.
Also makes results consistent, as the dlocatedb is updated daily.
----
This speeds up the execution time by 10x, when dlocate is installed.
It makes podman info takes 5-10 seconds, because it queries so many...
* https://github.com/containers/podman/issues/22102
* ~~https://github.com/containers/podman/issues/19317~~
> Use dlocate list instead of dpkg query

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_local_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/default.go
- pkg/config/testdata/containers_comment.conf
- pkg/config/testdata/containers_default.conf
- pkg/config/testdata/containers_invalid.conf
- pkg/config/testdata/containers_override.conf
- pkg/config/testdata/containers_override2.conf
In response to:
https://github.com/containers/podman/issues/18292
Adds config to pass CDI spec directory, so that it can be overridden. The enables rootless containers since otherwise users have to write to one of the shared, usually only root writeable paths at in /etc or /var.
Named to match cri-o's name
> feat: add cdi path to engine config

- libimage/load.go
- libimage/load_test.go
- libimage/pull.go
Add a `LoadReference()` method, for when we already know what format the local image should be treated as, and we don't have the patience for `Load()`'s guessing at it.
> Add a libimage.Runtime.LoadReference for loading images

- libimage/manifest_list_test.go
- libimage/manifests/manifests.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
When adding items from one index into another, preserve the annotations and URLs which are set in the descriptors in the source index.
> manifests: preserve Annotations when adding from indexes

- libimage/manifest_list.go
- libimage/manifest_list_test.go
- pkg/config/config_local_test.go
When adding a reference to a manifest list or image index, if we are guessing that it's a reference to an image in a registry, check if we can read something from that location instead of assuming it's correct, and if we can't, check for a local image.  This will let use use local image IDs to refer to items that we want to add to a list or index.
This would at least provide more of a workaround for https://github.com/containers/common/issues/1896, in that specifying the desired image using only its ID would start working.
> manifest add: check for local images last

- libnetwork/netavark/config.go
- libnetwork/netavark/ipam.go
- libnetwork/netavark/ipam_test.go
This is good to prevent any leaks but more important here there is a bug because we cache the last assigned ip. However when a network is removed the recreated with a different LeaseRange that ip might be very well outside the expected range and the logic seems to handle this correctly. I could fix it there but deleting the full bucket seems best as it avoid other issues and leaking the bucket forever.
Fixes containers/podman#22034
> libnetwork/netavark: remove ipam bucket on network rm

- OWNERS
Synchronizing the OWNERS with the CRI-O repository to have full maintenance access.
> [crio-1.28] Sync CRI-O owners

- OWNERS
Synchronizing the OWNERS with the CRI-O repository to have full maintenance access.
> [crio-1.27] Sync CRI-O owners

- OWNERS
Synchronizing the OWNERS with the CRI-O repository to have full maintenance access.
> [crio-1.26] Sync CRI-O owners

- OWNERS
Synchronizing the OWNERS with the CRI-O repository to have full maintenance access.
> [crio-1.25] Sync CRI-O owners

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
This is required for podman v4.9 to use crun-vm on F38/39.
(cherry picked from commit 7b056a0cab69cbcc2426aca628b7767f529b2d9f)
@rhatdan @TomSweeneyRedHat @Luap99 @mheon PTAL
cc @albertofaria
> [v0.57 backport] containers.conf: add crun-vm as a runtime

- .codespellrc
- libnetwork/internal/rootlessnetns/netns_linux.go
- libnetwork/netavark/config.go
- libnetwork/netavark/ipam.go
- libnetwork/netavark/ipam_test.go
- libnetwork/netavark/network.go
Backport https://github.com/containers/common/pull/1946 and https://github.com/containers/common/pull/1945
> [v0.58] backport my networking fixes

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Some users wish to turn of healthcheck events in Podman so add a config
option to allow that. The actual logic must live in Podman.
Link: https://issues.redhat.com/browse/RHEL-18987
> pkg/config: add new healthcheck_events field

- pkg/secrets/define/secrets.go
- pkg/secrets/filedriver/filedriver.go
- pkg/secrets/passdriver/passdriver.go
- pkg/secrets/passdriver/passdriver_test.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
- pkg/secrets/secretsdb.go
- pkg/secrets/shelldriver/shelldriver.go
- pkg/secrets/shelldriver/shelldriver_test.go
Consolidate all errors between the different secret drivers.
Fixes: https://github.com/containers/podman/issues/22000
Fixes: https://github.com/containers/podman/issues/21952
> Don't error out on secret create --replace on missing secret

- pkg/config/config.go
The error message currently includes the full attributedstring.Slice struct which looks wrong and can confuse users. Make sure we actually show the list of directories.
Fixes 82e88cc97c ("pkg/config: use NewSlice, Get and Set where possible")
> pkg/config: fix FindHelperBinary() error message

- .cirrus.yml
- .github/workflows/validate.yml
For the last long time, Fedora CI VMs have had a disk /tmp. Real-world setups typically have tmpfs /tmp. This switches to CI VMs that reflect the real world.
See https://github.com/containers/automation_images/pull/340
> CI VMs: bump to new versions with tmpfs /tmp

- libnetwork/pasta/pasta_linux.go
- libnetwork/pasta/pasta_linux_test.go
likely best to look at commit by commit, first two are just preparation/cleanup and unit tests, third one is the important one to fix the bug.
libnetwork/pasta: fix --map-gw parsing
If a port option was given after --map-gw then parsing failed as the
next arg was always skipped due the modification of the slice.
Modifing the slice inside the loop is bad and does not do what some
might think. Append here basically creates a new slice (thus you always
have to assign the result to the variable) with the same pointer to the
same underlying array of data[1]. The loop however will still continue to
loop over the slice as it saw it at the begining of the loop.
So in the bug case the underlying array would look like this:
{"--config-net", "--map-gw", "-T", "80"}
and after the append call to …
> libnetwork/pasta: fix --map-gw parsing

- libnetwork/pasta/pasta_linux.go
- libnetwork/pasta/pasta_linux_test.go
It is possible for a user to set --map-gw more than once so we should
handle it correctly.
> libnetwork/pasta: fix multiple --map-gw parsing

- pkg/config/config.go
- pkg/config/config_unix.go
- pkg/config/config_windows.go
- pkg/config/new.go
Add `%PROGRAMDATA%/containers` to the list of possible config folders on Windows.
For all OSes returns the "the default config path overridden by the root user" using a function rather than a `const` to allow composing it with variable `PROGRAMDATA` on windows.
Fixes https://github.com/containers/podman/issues/22411
> Support system-wide containers config folder on windows

- libimage/pull.go
- libimage/runtime.go
Before, here's what happens if you forget a `-v` in your bind mount for example:
```
$ podman run /dev:/dev docker.io/busybox echo hello
Error: invalid reference format
$
```
After:
```
$ podman run /dev:/dev docker.io/busybox echo hello
Error: parsing reference "/dev:/dev": invalid reference format
```
This error prefixing is common in other callers.
```release-note
None
```
> libimage: Add input to error context when normalizing

- .codespellrc
- .packit.yaml
- contrib/redhat/registry.access.redhat.com.yaml
- contrib/redhat/registry.redhat.io.yaml
- rpm/containers-common.spec
- rpm/update-config-files.sh
- rpm/update-lib-versions.sh
This commit enables:
- upstream copr build jobs on PRs
- rpm builds on podman-next copr after every commit to main
- Fedora and CentOS Stream 10 downstream update jobs on every upstream
release
- Fetch RPM-GPG-KEY-redhat-release from https://access.redhat.com/security/data/fd431d51.txt
- Config file patching during rpm build is managed via `rpm/update-config-files.sh`,
modified from the original script at
https://gitlab.com/redhat/centos-stream/rpms/containers-common/-/blob/c9s/update.sh
and modified to include Fedora and RHEL-10
> [skip-ci] Packit: New workflow for downstream Fedora and CentOS Stream 10

- .packit.yaml
The copr name got mistakenly changed during a replace-all in #1960.
> [skip-ci] Packit: fix copr name

- rpm/containers-common.spec
This will allow users to edit these configs and have those changes persist.
Will be needed if users experience issues with using the `lookaside` setting instead of the current `sigstore` setting that these files ship with.
Ref: https://github.com/containers/common/pull/1983
> [skip-ci] RPM: redhat registry config files should be config(noreplace)

- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
Add some tests to make sure secrets do not regress.
>  Make code checking for secret --replace cleaner 

- contrib/redhat/registry.access.redhat.com.yaml
- contrib/redhat/registry.redhat.io.yaml
The old `sigstore` setting was confusing to users now that "Sigstore" is an independent open-source project. Use the newer `lookaside` setting as described in https://github.com/containers/image/pull/1606
(This is a resubmission of https://src.fedoraproject.org/rpms/containers-common/pull-request/6)
> use new "lookaside" setting for RH registries

- .cirrus.yml
- libnetwork/cni/config_test.go
- libnetwork/cni/testfiles/invalid/invalid_gateway.conflist
- libnetwork/cni/testfiles/invalid/invalidname.conflist
- libnetwork/cni/testfiles/invalid/noname.conflist
- libnetwork/cni/testfiles/invalid/samename1.conflist
- libnetwork/cni/testfiles/invalid/samename2.conflist
- libnetwork/cni/testfiles/valid/bridge.conflist
- libnetwork/cni/testfiles/valid/dualstack.conflist
- libnetwork/cni/testfiles/valid/ipam-empty.conflist
- libnetwork/cni/testfiles/valid/ipam-none.conflist
- libnetwork/cni/testfiles/valid/ipam-static.conflist
- libnetwork/cni/testfiles/valid/label.conflist
- libnetwork/cni/testfiles/valid/mtu.conflist
- libnetwork/cni/testfiles/valid/vlan.conflist
Also removes the podman-plugins (dnsname) package. As such I had to fix the the cni tests that use dnsname.
> CI: update VM to fedora 40

- libnetwork/cni/run.go
- libnetwork/internal/rootlessnetns/netns_freebsd.go
- libnetwork/internal/rootlessnetns/netns_linux.go
- libnetwork/netavark/run.go
- libnetwork/types/network.go
When using the bridge network mode as rootless we use the rootless netns logic, for podman this looks like just as using bridge as root. The issue is however due the extra namespace we block certain address there. This can be seen best with pasta but actually effects other cases too. The podman logic tries to use any host ip address for host.containers.internal but we must make sure to exculde all these address in the rootless netns as they are not actually the hostns as thus cause great confusion.
For the --network pasta case I already fixed this by returning the ips on the pasta.Setup2() call in b809d7231132.
For the bridge mode this more complicated due several layers of function calls. I decided to implement this as extra function call on the interface to return the ips as this makes …
> libnetwork: add option to return rootless-netns ips

- pkg/config/config.go
move the specific code from Podman, so that also other packages can take advantage of it.
Closes: RHEL-36146
> config: attempt to guess DBUS_SESSION_BUS_ADDRESS

- .codespellrc
- .packit.yaml
- contrib/redhat/registry.access.redhat.com.yaml
- contrib/redhat/registry.redhat.io.yaml
- rpm/containers-common.spec
- rpm/update-config-files.sh
- rpm/update-lib-versions.sh
Backporting rpm and packit changes from main to v0.58
@Luap99 @edsantiago @TomSweeneyRedHat @ktdreyer @rhatdan @mheon PTAL
> [backport v0.58] [skip-ci] packit rpm backports

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/copy/progress_bars.go
- vendor/github.com/containers/image/v5/copy/single.go
- vendor/github.com/containers/image/v5/directory/directory_dest.go
- vendor/github.com/containers/image/v5/directory/directory_src.go
- vendor/github.com/containers/image/v5/directory/directory_transport.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
- vendor/github.com/containers/image/v5/docker/registries_d.go
- vendor/github.com/containers/image/v5/openshift/openshift_src.go
- vendor/github.com/containers/image/v5/ostree/ostree_dest.go
- vendor/github.com/containers/image/v5/ostree/ostree_src.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/storage/storage_reference.go
- vendor/github.com/containers/image/v5/storage/storage_src.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Bump c/image to v5.29.3.  This partially addresses:
CVE-2024-3727
https://issues.redhat.com/browse/OCPBUGS-33266
https://issues.redhat.com/browse/OCPBUGS-33267
> Bump c/image to v5.29.3, c/common to v0.57.5, CVE-2024-3727

- pkg/apparmor/apparmor_linux_template.go
AppArmor v4.0.0 introduced podman, runc and crun profiles for /usr/bin/podman, /usr/sbin/runc and /usr/bin/crun respectively[1]. This change breaks the stopping of containers, because the built-in profile assigned to containers doesn't accept signals from podman, runc and crun peers.
This commit extends the default profile with rules that allow receiving signals from processes that run confined with the podman, runc or crun profile. It is backward compatible because the peer value is a regular expression (AARE) so the referenced profile doesn't have to exist for this profile to successfully compile and load.
The signal set from runc or crun remains unconstrained as the user can issue any signal via the kill sub-command of podman.
Signals from podman itself are restricted to the common …
> Update apparmor profile to support v4.0.0

- pkg/hooks/monitor.go
Fix data race with hooks map where writes happen without acquiring a lock [here](https://github.com/containers/common/blob/b6437602fcba8bc63da18c5391c80a89d00e2c8f/pkg/hooks/monitor.go#L51) and reads [here](https://github.com/containers/common/blob/b6437602fcba8bc63da18c5391c80a89d00e2c8f/pkg/hooks/hooks.go#L70-L75).
> Fix data race with hooks map

- docs/containers.conf.5.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/default.go
- pkg/config/testdata/containers_default.conf
Adds a new configuration section `podmansh` to configure the shell,
container and the timeout for podmansh.
See https://github.com/containers/podman/pull/22683 for more context.
> Allow configuration of podmansh

- version/version.go
Bump the version to the initial dev for the new c/common v0.59 release branch.
> [v0.59.0] Bump c/common to v0.59.1-dev

- .packit.yaml
- rpm/containers-common.spec
Packit failed to trigger an automatic fedora package update on the upstream release v0.59.0 which brought to light further issues which this commit corrects.
Packit doesn't honor a global `downstream_package_name` key when the upstream repo and downstream package name don't match. For this very repo, upstream repo is `common`, while downstream package is `containers-common`. For such cases, `downstream_package_name` should be specified at the package level.
The `Source0` URL in rpm spec has also been corrected. This wasn't noticed in packit jobs on PRs because packit replaces Source0 with a locally created archive.
The `mv` commands in rpm spec have also been replaced by `cp` so that consecutive `rpmbuild` runs will not complain about not finding the source files.
The autosetup step in …
> [v0.59 backport] [skip-ci] Packit/RPM: more fixes

- pkg/config/config_windows.go
The path no longer included the path separator between the env and our config dir. The regression was added in commit 6c651dfac1.
Fixes #2025
> fix windows config path regression

- rpm/containers-common.spec
- rpm/update-config-files.sh
This commit copies over shortnames.conf, registries.conf and storage.conf to the rpm build dir before running the patching script.
Prior to this, the script would complain about not finding those files but the rpmbuild process itself didn't fail.
> [skip-ci] RPM: ensure config files are patched

- rpm/containers-common.spec
- rpm/update-config-files.sh
This commit copies over shortnames.conf, registries.conf and storage.conf to the rpm build dir before running the patching script.
Prior to this, the script would complain about not finding those files but the rpmbuild process itself didn't fail.
(cherry picked from commit 06a4eef094ad34bd3e88c641aac0ddbe93ba45c4)
> [v0.59 backport] [skip-ci] RPM: ensure config files are patched

- docs/containers.conf.5.md
- pkg/config/containers.conf
nftables was implemented for netavark v1.10
> fix outdated firewall_driver docs

- rpm/containers-common.spec
The rpm creates and installs to dirs /usr/share/rhel and /usr/lib/containers . So, it should own them as well.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2283290
> [skip-ci] RPM: own dirs

- rpm/containers-common.spec
The rpm creates and installs to dirs /usr/share/rhel and /usr/lib/containers . So, it should own them as well.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2283290
(cherry picked from commit c7070a9ba2f725f4b044806ddb7f844aaa0324fd)
> [v0.59 backport] [skip-ci] RPM: own dirs

- pkg/config/config_bsd.go
- pkg/config/default_bsd.go
- pkg/config/default_common.go
- pkg/password/password_supported.go
Hi folks, I've been patching your repo to build podman on NetBSD.
The resulting podman seems to work well enough.
(Needs https://github.com/containers/storage/pull/1935 too, and a hack to overcome an issue with the unix package not having SEEK_SET defined on NetBSD)
>  Trivial patches to minimize patches needed by NetBSD

- version/version.go
Bumping to ready for the Podman v5.1.1 release.  This change will put Windows-related fixes in place.
> [v0.59] Bump c/common to v0.59.1, then to v0.59.2-dev 

- libimage/manifest_list.go
- libimage/manifests/manifests.go
Both slices.Clone() and maps.Clone() return `nil` when passed `nil`, so we don't need to check for a `nil` pointer before calling them.
Imports that used the golang.org/x/exp versions of the maps and slices packages can now use the versions in the standard library, since we require Go 1.21.
> Remove nil checks before calling slices.Clone/maps.Clone

- rpm/update-config-files.sh
Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>
(cherry picked from commit d3ca62d55d5b4797860c37888db040954e5aa7e0)
xref https://github.com/containers/common/pull/2026#issuecomment-2161246999
> [skip-ci] RPM: `zstd:chunked on fedora > 40 and rhel > 10

- libnetwork/internal/rootlessnetns/netns_linux.go
Currently it does the mkdir only implicitly because the code creates run/systemd but this only happens when /run/systemd exists on the host. As such the rootless code was broken on all non systemd distros[1].
[1] https://github.com/containers/podman/discussions/22903
> libnetwork/rootlessnetns: create run dir explicitly

- libimage/manifests/manifests_test.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_default.conf
We see issues in CI where we fail to pull from k8s.gcr.io. As k8s uses a new registry URL migrate to that[1] and hope it fixes the issues.
[1] https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> replace k8s.gcr.io with registry.k8s.io

- libnetwork/pasta/pasta_linux.go
- libnetwork/pasta/pasta_linux_test.go
Now the user can't pass --debug/--trace option to pasta in order to get more logs when pasta fails. Indeed, the option --quiet is added by default and it is exclusive with  --debug/--trace option.
The PR remove the --quiet option when  --debug/--trace option are set by the user.
Example :
--network=pasta:--map-gw,--debug,--log-file=/tmp/log,--trace
> Allow --debug/--trace options for pasta

- rpm/containers-common.spec
netavark and aardvark-dns dependencies have updated Epoch, we need to handle them correctly in containers-common.
> [skip-ci] RPM: fix netavark dependency epoch

- go.mod
- go.sum
- libimage/manifests/manifests_test.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_default.conf
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Setting c/common v0.59.2 up to handle  containers/skopeo#2346, that happens
in the wild.
> [v0.59] Don't abort listing tags when we encounter a digest 

- go.mod
- go.sum
- libimage/manifests/manifests_test.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_default.conf
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Setting c/common v0.58.4 up to handle https://github.com/containers/skopeo/issues/2346, that happens
in the wild.
> [v0.58] Don't abort listing tags when we encounter a digest

- go.mod
- go.sum
- libimage/manifests/manifests_test.go
- pkg/config/config_test.go
- pkg/config/testdata/containers_default.conf
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Setting c/common v0.57.7 up to handle https://github.com/containers/skopeo/issues/2346, that happens
in the wild.
>  [v0.57] Don't abort listing tags when we encounter a digest

- .packit.yaml
This allows centos stream jobs to be triggered for PRs by authors who don't have commit access to the repo.
> [skip-ci] Packit: isolate rhel jobs from centos

- docs/Containerfile.5.md
Available for quite some time, but often useful and undocumented.
Fix that and a minor whitespace problem.
Also (minor), rename "buildah bud" to "buildah build".
Fixes: #1935
[Ref. Dockerfile docs](https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope)
> Docs: Semiautomatic platform ARGs

- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
- libnetwork/netavark/netavark_suite_test.go
This option is also supported by netavark for macvlan and ipvlan
networks.
Fixes #2051
> libnetwork/netavark: accept metric option for mac/ipvlan

- libimage/copier.go
- libimage/types.go
Move the definition of our LookupReferenceFunc type alias to a file that isn't conditionally compiled, as an alternative to https://github.com/containers/buildah/pull/5628.
> Make the definition of LookupReferenceFunc unconditional

- libimage/filters.go
Partial fix for https://github.com/containers/podman/issues/23120
Working on a fix for this crash, but want same error to come back as non-remote case.
> Display same error as split

- docs/Containerfile.5.md
A missing leading '*' in '*FROM**' caused FROM to be rendered as italic rather than bold in markdown/html and as '*FROM**' (i.e. no styling) in the man page.
> doc: fix typo in Containerfile.5.md

- pkg/cgroups/systemd_linux.go
Podman can request the pod cgroup cleanup from different processes.
Do not report an error if the cgroup is already stopped.
> cgroups: systemdDestroyConn ignores stopped units

- pkg/config/default_windows.go
- pkg/config/default_windows_test.go
Currently on Windows, volumes are mounted differently based on the provider:
- WSL automatically mounts the main drive `C:/` under `/mnt/c` on every Linux VM
- For HyperV instead, `podman` mounts `C:\Users\name` under `/Users/name`
Issues like [this one](https://github.com/containers/podman/issues/21036) are the consequence of such behavior.
With this PR `getDefaultMachineVolumes()` is updated to be consistent with WSL default behavior. That means that on both WSL and HyperV machines, the default volumes will be the `%userprofile%` drive (e.g. `C:/`) mounted under `/mnt/` (e.g. `/mnt/c`).
The old Hyper-V mount is still supported. Users can still use the notation `podman run -v /Users` when the provider is Hyper-V although the notation `podman run -v C:\Users` should be preferred.
> Use the WSL convention for the windows machines default volumes

- libnetwork/internal/rootlessnetns/netns_linux.go
- pkg/netns/netns_linux.go
> improve netns cleanup

- rpm/update-config-files.sh
Given we ship podman-next copr packages on quite a few envs now, config file handling should follow distro policy as much as possible.
Resolves: #2123
> RPM: No blanket conditionals for configs on COPR envs

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/signature/fulcio_cert.go
- vendor/github.com/containers/image/v5/signature/internal/rekor_set.go
- vendor/github.com/containers/image/v5/signature/internal/sigstore_payload.go
- vendor/github.com/containers/image/v5/signature/policy_config_sigstore.go
- vendor/github.com/containers/image/v5/signature/policy_eval_signedby.go
- vendor/github.com/containers/image/v5/signature/policy_eval_sigstore.go
- vendor/github.com/containers/image/v5/signature/policy_types.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
As the title says.
In preparation for Podman v5.2.2
> [v0.60] Bump c/image to v5.32.2, c/common to v0.60.2

- libimage/disk_usage.go
- libimage/filters.go
- libimage/filters_test.go
- libimage/history.go
- libimage/image.go
- libimage/image_tree.go
- libimage/layer_tree.go
- libimage/manifest_list.go
- libimage/push_test.go
- libimage/runtime.go
- libimage/runtime_test.go
- libimage/save_test.go
This PR changes `runtime.layerTree` method to use consistent values for the creation of layerTree. Before images and layers could vary between calls that obtain images and layers now using `storage.MultiList` to obtain consistent images and layers. Also, this PR adapts callers of `runtime.layerTree` to use consistent images and layers and vendor pre-release of `c/storage` with  `storage.MultiList` method. 
Fixes: https://github.com/containers/podman/issues/23331
Depends on: #2131
> libimage.runtime.layerTree: Use consistent layers and images

- rpm/update-config-files.sh
`rpm/update-config-files.sh` has now been simplified and will now fail if a pattern is not found instead of inserting a rule by default.
> RPM: Update config file patching

- .packit.yaml
When a new Fedora target (41 currently), is branched from rawhide, `fedora-latest` packit target will point to fedora-41, while `fedora-latest-stable` will point to `fedora-40`. Once fedora-41 has released, `fedora-latest` and `fedora-latest-stable` will both point to fedora-41.
So, to have Packit continue to create PRs for Fedora 40 once Fedora 41 has released, it's best to set the target back to `fedora-all`.
Similar patch for Podman: https://github.com/containers/podman/pull/23669
> [skip-ci] Packit: update targets for propose-downstream

- rpm/containers-common.spec
iptables and nftables are best handled in netavark package.
Ref: https://github.com/containers/netavark/pull/1033
> [skip-ci] RPM: move netavark deps to netavark package

- libnetwork/etchosts/ip.go
- libnetwork/internal/rootlessnetns/netns_linux.go
- libnetwork/pasta/pasta_linux.go
- libnetwork/pasta/pasta_linux_test.go
- libnetwork/pasta/types.go
- libnetwork/types/network.go
see commits, I still need to test and integrate this into podman
> pasta: use new --map-guest-addr option

- pkg/cgroups/cgroups_linux.go
writing to cgroup.subtree_control can fail with ENOENT either if the file itself doesn't exist, or a specified controller is not available.
Try to detect the reason and improve the error message.
Adding to help debugging https://github.com/containers/podman/issues/15074
> cgroups: improve ENOENT and EBUSY handling

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/progress_bars.go
- vendor/github.com/containers/image/v5/directory/directory_dest.go
- vendor/github.com/containers/image/v5/directory/directory_src.go
- vendor/github.com/containers/image/v5/directory/directory_transport.go
- vendor/github.com/containers/image/v5/docker/body_reader.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
- vendor/github.com/containers/image/v5/docker/registries_d.go
- vendor/github.com/containers/image/v5/openshift/openshift_src.go
- vendor/github.com/containers/image/v5/ostree/ostree_dest.go
- vendor/github.com/containers/image/v5/ostree/ostree_src.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/storage/storage_reference.go
- vendor/github.com/containers/image/v5/storage/storage_src.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
As the title says, bump c/image to v5.24.3 to address CVE-2024-3727, then bump c/common to include it in Podman v4.4.1-rhel.
> [v0.51] Bump c/image to v5.24.3, c/common to v0.51.4

- pkg/cgroups/cgroups_linux.go
if the system is running on cgroup v2, ignore the ownership of cgroup v1 controllers when the current process is at the root cgroup.
Closes: https://github.com/containers/podman/issues/23990
> cgroups: ignore ownership for cgroup v1 controllers

- pkg/cgroups/memory_linux.go
calculate the memory usage on cgroup v1 using the same logic as cgroup v2.
Since there is no single "anon" field, calculate the memory usage by summing the two fields "total_active_anon" and "total_inactive_anon".
Closes: https://github.com/containers/common/issues/1642
Closes: https://issues.redhat.com/browse/RHEL-16376
(cherry picked from commit 1a9d45ced26ca62aacc8d6ba4fa7e870acbf9eac)
> [v0.51] cgroups: fix memory usage on cgroup v1

- libimage/copier.go
For artifact support, the copier needs to get all tags; as such, we need to pass in the correct value for ImageListSelection.
> Add ImageListSelection to copier options

- pkg/netns/netns_linux.go
see commits, marking as draft until I ported in podman and passed CI there
> pkg/netns: some netns improvements 

- libimage/copier.go
- libimage/import.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/push.go
- libimage/save.go
To support artifact handling, we need to export some of the methods for copier. The Copy and Close method have been exported.  In addition, a new constructor that is exported was created so we could introduce a different SystemContext for artifacts.
> Export portions of Copier

- libimage/manifest_list.go
- libimage/manifest_list_test.go
- libimage/manifests/manifests.go
* Add `libimage.Image.ConvertToManifestList()`, which will convert an image to a manifest list if it isn't already possible to use it as one.
* Tweak the godoc for the `libimage/manifests.AddArtifactOptions` type so that it gets wrapped correctly for display.
> libimage.Image: add ConvertToManifestList()

- rpm/update-config-files.sh
keyctl is in ALLOW by default and `socket` should not always be ALLOW, per @giuseppe.
This change removes seccomp.json customizations and we'll use the distro's default seccomp profile.
> RPM: use default seccomp.json profiles

- pkg/netns/netns_linux.go
- version/version.go
Back port of https://github.com/containers/common/pull/2168, I had to fix some merge conflicts as main uses the new go 1.22 loop while here we still support go 1.21 so I had to change them back.
Needed for https://issues.redhat.com/browse/RHEL-59703
> [v0.60] Backport + version 0.60.3

- libimage/copier.go
- libimage/import.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/push.go
- libimage/save.go
To support OCI artifacts in Podman, we need to export the Copier type and create an exported constructor (NewCopier).  Additionally, the actual copy and close methods are now exported.
> Export Copier to support OCI artifacts

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
Partially resolves https://github.com/containers/common/issues/2117 .
> Document that zstd:chunked is downgraded to zstd when encrypting

- pkg/subscriptions/subscriptions.go
If we join a path from the container image we must always use securejoin to prevent us from following a symlink onto the host.
Fixes CVE-2024-9341
> pkg/subscriptions: use securejoin for the container path

- pkg/subscriptions/subscriptions.go
- version/version.go
> [v0.60] Backport pkg/subscriptions: use securejoin for the container path + new 0.60.4 release

- pkg/subscriptions/subscriptions.go
- version/version.go
If we join a path from the container image we must always use securejoin
to prevent us from following a symlink onto the host.
Fixes CVE-2024-9341
Needed for:
https://issues.redhat.com/browse/RHEL-60964
https://issues.redhat.com/browse/RHEL-60962
https://issues.redhat.com/browse/RHEL-61116
https://issues.redhat.com/browse/RHEL-61113
> [v0.57] Backport pkg/subscriptions: use securejoin for the container path + new 0.57.7 release 

- pkg/subscriptions/subscriptions.go
If we join a path from the container image we must always use securejoin to prevent us from following a symlink onto the host.
Fixes CVE-2024-9341
--- 
@Luap99 is it possible to cut a patch release for 0.58?
> [v0.58] Backport pkg/subscriptions: use securejoin for the container path

- docs/containers.conf.5.md
- pkg/config/containers.conf
Follow-up to https://github.com/containers/podman/pull/24043 and https://github.com/containers/podman/pull/24122
This just clarifies a few minor things about these configs after we've updated the docs of Podman's `--add-host`, `--no-hosts`, et. al. CLI options.
@Luap99: Is it true that `host_containers_internal_ip` has *no effect at all* with `podman machine`, or is it just not possible to disable the `host.containers.internal` and `host.docker.internal` hostnames?
> Update docs of `containers.conf` configs affecting `/etc/hosts`

- pkg/config/default.go
Now that Fedora has packaged docker-compose v2, /usr/bin/docker-compose is provided by the docker-compose-switch project which is a shim that translates `docker-compose ...` into `docker compose ...` while translating any deprecated CLI arguments into the new compose v2 counterparts.
This has been a problem for podman users that have podman-docker installed, because `podman compose` tries to call the docker-compose-switch shim and the shim assumes that `docker compose` will be provided by the actual docker command that calls the appropriate CLI plugin, not a podman wrapper that tries to call the docker-compose shim again, resulting in an endless loop.
Changing `podman compose` to prefer calling the docker-compose CLI plugin directly should fix this issue.
Ref: …
> config: prefer compose CLI plugin over docker-compose binary

- pkg/config/default.go
- pkg/config/default_linux.go
it is wrong for two reasons: 1) we set the current process limits from a library, and 2) it sets a too high value for root, since it is the maximum allowed value on the system.
> config: do not set the default nproc to the max available

- docs/containers.conf.5.md
- pkg/config/containers.conf
> Document krunkit for AI Workloads

- rpm/containers-common.spec
Fedora completely ignores `Suggests` by default [1].  So, listing anything as `Suggests` is as good as not mentioning it at all, unless it's intended for tools and users who specifically respect it.
Downgrading the dependency on `fuse-overlayfs` to `Suggests` can make it go missing from the user's system, and break old Toolbx containers [2].
This is a problem because when Fedora 40 was released, it included `containers-common-0.58.0-2.fc40` [3,4], which still had:
```
Recommends: fuse-overlayfs
Requires: (fuse-overlayfs if fedora-release-identity-server)
```
The change to `Suggests` in Fedora commit [447945e59a01cb67](https://src.fedoraproject.org/rpms/containers-common/c/447945e59a01cb67) ("Move fuse-overlayfs to suggests") was made after that.
Such breaking changes are not meant for …
> Revert "Move fuse-overlayfs to suggests" for Fedora 40 and older

- rpm/containers-common.spec
Commit 5ad221daa4d8d182 ("Revert \"Move fuse-overlayfs to suggests\" for Fedora 40 and older") restored the dependency on fuse-overlayfs for Fedora 40 and older to not disrupt stable Fedora releases by breaking backwards compatibility with existing containers.
Fedora completely ignores Suggests by default [1].  So, listing anything as Suggests is as good as not mentioning it at all, unless it's intended for tools and users who specifically respect it.
It turns out that there are important use-cases where the Linux kernel's overlay file system doesn't work, and one could really benefit from having fuse-overlayfs(1).  A container cannot use an overlayfs when the underlying file system is also an overlayfs, such as on the Fedora Workstation live media, or a network file system.
Therefore, …
> Revert "Move fuse-overlayfs to suggests" for all Fedoras

- CONTRIBUTING.md
- README.md
Change the DCO wording so that it is clear that we do not need the real
name, just someting the properly identifies that person within the
community.
Touch up the old Reporting Issues and Submitting Pull Requests section
based on Matt's work in podman[1] and add some extra step in there.
Add new sections for the vendor process and and how to use git bisect.
[1] https://github.com/containers/podman/pull/24261
> update CONTRIBUTING.md 

- libimage/pull.go
This should fix https://github.com/containers/storage/pull/2130#issuecomment-2405971361 .
<s>Untested at this point.</s>
Reading the code makes it tempting to keep refactoring and improving, but to keep the scope reasonable, I have just added FIXMEs.
Cc: @edsantiago
> Only return one image ID, and hopefully a more precise one, from pulling.

- rpm/update-config-files.sh
See: https://fedoraproject.org/wiki/Changes/zstd:chunked
See: https://pagure.io/fesco/issue/3252
See: https://github.com/containers/common/pull/2048
See: https://src.fedoraproject.org/rpms/containers-common/c/9f4dd38589309fbc189eac94367f520c105c3c1c?branch=f41
> rpm/update-config-files: zstd:chunked not enabled in Fedora yet

- rpm/update-config-files.sh
xref commit 1ad44cb67c70370f15d1981621824d1256a10041 "rpm/update-config-files: zstd:chunked not enabled in Fedora yet"
Basically it doesn't make sense to keep this enabled in RHEL10 but not in Fedora, that *seriously* undermines the testing story.
My immediate practical issue is that zstd:chunked in RHEL10 as of right now still breaks the bootc path, xref: https://github.com/containers/bootc/issues/509#issuecomment-2419695362
> rpm/update-config-files: Don't set zstd:chunked default anywhere

- rpm/update-config-files.sh
Fixed in main with #2208 and #2213.
> [skip-ci][v0.60] RPM: do not set zstd:chunked default anywhere

- pkg/timezone/timezone.go
The special value local must always be higher priority then the TZDIR env so make sure local is matched before. Without this we joined local on the TZDIR path which of course does not result in a valid timezone path.
I will add a regression test in podman.
Fixes: containers/podman#23550
> pkg/timezone: handle TZDIR and local correctly

- libnetwork/internal/rootlessnetns/netns_linux.go
- libnetwork/pasta/pasta_linux.go
This was just added as alias to allow vendoring without having to fix all callers at the same time.
These are the PRs that updat the callers:
https://github.com/containers/podman/pull/24417
https://github.com/containers/buildah/pull/5724
> libnetwork/pasta: remove Setup2()

- go.mod
- go.sum
- pkg/ssh/connection_golang.go
- vendor/github.com/skeema/knownhosts/CONTRIBUTING.md
- vendor/github.com/skeema/knownhosts/LICENSE
- vendor/github.com/skeema/knownhosts/NOTICE
- vendor/github.com/skeema/knownhosts/README.md
- vendor/github.com/skeema/knownhosts/knownhosts.go
- vendor/modules.txt
**TL;DR** This PR addresses [this issue](https://github.com/containers/podman/issues/23575). In this [containers/podman PR](https://github.com/containers/podman/pull/24340), I have added some specific tests.
The package [golang.org/x/crypto/ssh/knownhosts](https://pkg.go.dev/golang.org/x/crypto/ssh/knownhosts) has an issue when an SSH server has many public keys (i.e., supports multiple crypto algorithms). 
For instance, if the local `known_hosts` file entries don't match the first SSH server key but match other SSH server keys, the handshake fails with a key mismatch error.
See https://github.com/golang/go/issues/29286 and https://github.com/containers/podman/issues/23575.
Package [github.com/skeema/knownhosts](https://github.com/skeema/knownhosts) is a wrapper of …
> Use skeema/knownhosts, not x/crypto/ssh/knownhosts

- docs/containers.conf.5.md
I read the contributing guidelines and I think I am up to speed.
PR was done when scrolling about `containers.conf` and saw this might affect users who copy-paste and don't look.
very low priority but keeping here.
if any changes are required let me know
> docs(container.conf): command typo

- pkg/cgroups/cgroups_linux_test.go
- pkg/cgroups/systemd_linux.go
The cpuset value setting for cgroup is not set correctly.
Fixes https://github.com/containers/common/issues/2229
> cgroups: fix incorrect cgroups cpuset via systemd

- pkg/subscriptions/subscriptions.go
`/etc/system-fips` is deprecated in CentOS Stream 9 and has been removed from CentOS Stream 10. UBI8 containers still contain `/etc/system-fips -> /run/secrets/system-fips`, but UBI9 containers do not, so creating `/run/secrets/system-fips` on UBI9 (or later) does not serve a useful purpose. See [[1], [2]].
Instead of checking `/etc/system-fips` to determine whether FIPS mode is enabled on the host, read `/proc/sys/crypto/fips_enabled`, which works for all supported RHEL versions and likely even earlier.
In CentOS 10 Stream, the crypto-policies package does now contain `/usr/share/crypto-policies/default-fips-config`, which is meant to serve as a file to bind-mount over `/etc/crypto-policies/config` when in FIPS mode [[3]]. Manual creation of this file is thus no longer required in …
> pkg/subscriptions: Modernize FIPS mounts

- libnetwork/resolvconf/resolv_test.go
- libnetwork/resolvconf/resolvconf.go
One thing I noticed in the recent aardvark-dns bug[1] that we copy link local nameservers into the container. This makes no sense as the link local address contains a zone (interface name/index) and cannot work without it. However a container by design will have a different interface name/index so the address can never work in the normal case.
Only when we do share the host netns then we should keep it.
[1] https://github.com/containers/aardvark-dns/pull/537
> libnetwork/resolvconf: filter out ipv6 link local

- libnetwork/types/network.go
This allows us to pass through data to netavaark without bloating this struct. See #24523.
Required by:
https://github.com/containers/podman/pull/24535
https://github.com/containers/netavark/pull/1125
> PerNetworkOptions: add driver specific options

- libimage/image_test.go
- libimage/pull_test.go
- libimage/push_test.go
- libimage/remove_test.go
- libimage/runtime_test.go
- libimage/save_test.go
These images can and will change at any time and thus can break our CI without any external changes which is very bad. The TestPush test is failing because it expects two not one image as it converts from docker to oci on push. However the upstream docker.io/library/alpine was switched to an oci image thus the test started failing as the local storage now has the same id and just stores two different tags for the same image.
Switch to our own controlled quay.io images where possible. This is neither complete nor do I fully understand the tests here. I did a quick search and replace and will see what works or not.
> libimage tests: try to avoid docker.io images

- docs/containers.conf.5.md
- libnetwork/types/network.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
- pkg/config/testdata/containers_default.conf
* Added ContainerHostname to NetworkOptions. Podman will set this
and Netavark will read it.
* Added the `container_name_as_hostname` option to the
CONTAINERS table in containers.conf.  Currently, if you don't
explicitly set a hostname when creating a container, podman will
set it to the short ID. If this option set to `true` and a
hostname isn't explicitly set, podman will use the container's
name, with characters not in the set `[0-9a-zA-Z.-]` removed,
as the hostname instead of the short ID. Set to false by default
to preserve existing behavior.
Signed-off-by: George Joseph <g.devel@wxy78.net>
Required by containers/podman#24675
Required by containers/netavark#1130
> Allow Podman to send the container's hostname to Netavark

- libimage/push.go
If we reset the default compression method, force compression no longer works.
Fixes https://github.com/containers/podman/issues/23942
Podman test https://github.com/containers/podman/pull/24673
> Only reset compression if its not valid

- libnetwork/pasta/pasta_linux.go
Starting with pasta 2024_11_27.c0fbc7e there is new "local mode"[1] in pasta that defaults to setting up link local addresses in the netns when no suitable interface was found. this is done to fix the podman issue[2] where we fail to start in these cases which was a poor UX. Now the pasta change alone works fine for these users but there is one problem.
Podman adds hosts entries for the container ip/name tuple and for the host.containers.internal. These entries are filtered out thus neither ipv4 or ipv6 bool was set and no addresses where added to IPAddresses. Thus podman had no info to add entries and just left them empty, while for most cases this is fine there might be a few users who expect host.containers.internal and the container name to resolve correctly.
This commit changes the …
> libnetwork/pasta: do not ignore ipv4 link local

- pkg/ssh/connection_golang.go
Using the path package is not correct on windows as it always defaults to the "/" as path separator. Instead one must use the filepath package.
Fixes containers/podman#24616
> pkg/ssh: fix windows path logic

- rpm/containers-common.spec
In some cases if /etc/ is mounted read-only the non-existence of the `/etc/containers/networks` directory will cause basic functionality to fail.
```
bash-5.2# mount --bind -o ro /etc/containers/ /etc/containers/
bash-5.2# podman info
Error: mkdir /etc/containers/networks: read-only file system
```
Since it's going to get created anyway let's just have the directory exist from the beginning.
> spec: create/own /etc/containers/networks

- libnetwork/netavark/config.go
- libnetwork/netavark/network.go
Podman creates/initializes the network backend for every command. However most commands will not need it so we should keep the required actions we do to a minimum.
In this case the config directory /etc/containers/networks by default as root may not exists and then we try to create it which can fail, i.e. when /etc is read only[1].
The code here are a bit more changes then I would have liked but we must make sure the default in memory network always exists and do not create the directory there.
[1] https://github.com/containers/common/pull/2265
> libnetwork/netavark: do not create config dir in init

- libimage/image_test.go
- libimage/pull_test.go
- libimage/push_test.go
- libimage/remove_test.go
- libimage/runtime_test.go
- libimage/save_test.go
- libnetwork/pasta/pasta_linux.go
- pkg/ssh/connection_golang.go
- rpm/containers-common.spec
Backports of https://github.com/containers/common/pull/2250
https://github.com/containers/common/pull/2258
https://github.com/containers/common/pull/2256
https://github.com/containers/common/pull/2265
> [v0.61] Some backports

- pkg/config/config.go
follow-up for commit 464e79b7b0957b27f51d7736e0e2978748815b8a.
use the homedir package to find the runtime directory, and look there for the dbus session socket when XDG_RUNTIME_DIR is not set.
> config: detect XDG_RUNTIME_DIR if empty

- libnetwork/cni/config.go
- libnetwork/internal/util/bridge.go
- libnetwork/netavark/config.go
- libnetwork/netavark/config_test.go
When a vlan is used there should be no bridge name conflict check. It is totally valid to have the same bridge with different vlans in two configs and that is the intended use case.
Fixes #2095
> libnetwork/netavark: allow same bridge name with different vlan

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/registries_d.go
- vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go
- vendor/github.com/containers/image/v5/pkg/tlsclientconfig/tlsclientconfig.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Bump c/image to v5.34.0 in preparation for Podman v5.4
> Bump c/image to v5.34.0

- version/version.go
Bumping c/common to v0.62.0.  This is in preparation for Podman v5.4.  There were separate PRs for c/storage and c/image bumps that have already merged.
> Bump c/common to v0.62.0, then to v0.63.0-dev

- pkg/apparmor/apparmor_linux_template.go
This change updates the default apparmor profile to allow podman to send any signal rather than the allow listed "SIGINT", "SIGQUIT", "SIGKILL", and "SIGTERM". This fixes podman with signal proxying turned on (``--sig-proxy``) not being able to forward signals from the terminal such as "SIGWINCH" when attached to a TTY.
> update apparmor profile to allow podman to send any signal

- .github/renovate.json5
- .github/workflows/validate.yml
- internal/deepcopy.go
- libimage/load_test.go
- libimage/manifest_list_test.go
- libimage/manifests/manifests_test.go
- libimage/push_test.go
- libimage/runtime_test.go
- libimage/save_test.go
- libnetwork/slirp4netns/slirp4netns.go
- pkg/apparmor/internal/supported/supported_test.go
- pkg/cgroups/cgroups_linux.go
- pkg/chown/chown_test.go
- pkg/chown/chown_unix.go
- pkg/config/default.go
- pkg/config/default_test.go
- pkg/manifests/manifests_test.go
- pkg/ssh/ssh_test.go
> update golangci-lint to v1.64.4

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/signature/fulcio_cert.go
- vendor/github.com/containers/image/v5/signature/pki_cert.go
- vendor/github.com/containers/image/v5/signature/policy_config_sigstore.go
- vendor/github.com/containers/image/v5/signature/policy_eval_sigstore.go
- vendor/github.com/containers/image/v5/signature/policy_types.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Bumping c/image to v5.34.1 and c/common to v0.62.1.  This will allow us to deliver BYOPKI signature verification
for RHEL 9.6/10.0 ZeroDay.
> [v0.62] Bump c/image to v5.34.1, c/common to v0.62.1

- libimage/image.go
- libimage/inspect.go
- libimage/manifest_list.go
- libimage/manifest_list_test.go
- libimage/manifests/manifests.go
- libimage/manifests/manifests_test.go
- pkg/supplemented/supplemented.go
... to validate that the manifests match expected digests, if any.
Do this everywhere, even where we read local storage which is mostly trusted, because it is cheap enough and being consistent makes it less likely for the code to be copied into other contexts shere the sources are not trusted.
> Use UnparsedInstance.Manifest instead of ImageSource.GetManifest

- .golangci-extra.yml
- .golangci.yml
- Makefile
It is not needed since commit c347a01f ("Bump c/image to v5.31.0, c/storage v1.54.0", PR #2011), which removes device mapper support.
> Makefile,.golangci.yml: rm exclude_graphdriver_devicemapper

- .cirrus.yml
- .golangci.yml
- Makefile
Currently, "make validate" is not used from any CI workflows, meaning
it is there for local developer consumption only. For that case, we
can safely assume that a developer can maintain a recent golangci-lint
installation.
This also fixes the problem of golangci-lint version discrepancy between
Makefile and .github/workflows/validate.yml, introduced by commit 9378a51a1
("renovate: teach it to update the lint version").
This fixes the following warnings from golangci-lint v1.64.6:
WARN [lintersdb] The linter "gomnd" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The linter "execinquery" is deprecated (step 2) and deactivated. It should be removed from the …
> ci: fixups to golangci lint configuration

- libimage/disk_usage.go
- libimage/disk_usage_test.go
- libimage/layer_tree.go
The old implementation only counted full images when sharing content between them. That is wrong, the store is layer based. We can have two images with no parent image that shares layers.
As such get rid of the image tree that only is able to walk child/parent images. Instead we actually walk all layers now and correctly notice when they are shared.
To this this correctly, first convert all layers to map so we can look them up by ID. And add missing size information if needed. Then we walk all images layers and count how often each layers is used. Then walk again but this time we know if the layer size must be shared or not so we can actually acount things correctly.
Fixes: containers/podman#24452
Fixes: https://issues.redhat.com/browse/RHEL-29641
> libimage: rework DiskUsage() to count layers

- .packit.yaml
rhel copr targets are often outdated causing failed builds and tests. Best to only have CentOS Stream targets upstream, so we ensure everything that enters RHEL at some point has been tested upstream.
> [skip-ci] Packit: remove epel/rhel copr targets

- docs/containers.conf.5.md
- pkg/config/containers.conf
- pkg/config/containers.conf-freebsd
The current docs are confusing and partly wrong even.
Fixes containers/podman#25377
> docs: update network description

- libnetwork/internal/util/create.go
- libnetwork/internal/util/validate.go
- libnetwork/netavark/config_test.go
- libnetwork/types/define.go
The Linux kernel imposes a 15-character limit on network interface names. Currently,
Podman allows creating networks with interface names longer than this limit, which
leads to runtime failures when attempting to use these networks.
```bash
podman network create my_net --interface-name abcdefghij123456
podman run -it --network my_net alpine
Error: preparing container: netavark (exit code 1): get bridge interface: 
Netlink error: Numerical result out of range (os error 34)
```
This change adds validation during network creation by adopting the same approach
used in the [CNI project](https://github.com/containernetworking/cni/blob/main/pkg/utils/utils.go#L32), which already handles this kernel limitation.
> fix(libnetwork): interface name length validation

- pkg/config/default.go
- pkg/config/default_linux_test.go
On Linux, mask "/proc/interrupts" and
"/sys/devices/system/cpu/*/thermal_throttle" inside containers by default.
It is the equivalent of https://github.com/moby/moby/pull/49560 for Moby.
Mitigates potential Thermal Side-Channel Vulnerability Exploit (https://github.com/moby/moby/security/advisories/GHSA-6fw5-f8r9-fgfm).
> config: mask thermal interrupt info paths

- libimage/copier.go
- libimage/image_test.go
- libimage/import.go
- libimage/load.go
- libimage/manifest_list.go
- libimage/pull.go
- libimage/push.go
- libimage/save.go
Following commit fixes a `race` condition in `libimage` because in `Pull(` after performing `copy` from remote sources it agains attempts to resolve image via `LookupImage`, any operation between `copy` and `LookupImage` can remove `name` from the recently pulled image. Causing race in builds.
Removing unnecessary `image -> name -> image` round-trip from `Pull(`
This issue was discoverd while working on PR https://github.com/containers/buildah/pull/5971
```
buildah build -t test --jobs=2 --skip-unused-stages=false .
```
Containerfile
```
FROM quay.io/jitesoft/alpine
RUN arch
FROM --platform=linux/arm64 quay.io/jitesoft/alpine AS foreign
```
Following commit also addresses the commit https://github.com/containers/common/pull/2202/commits/e2324ddbb2a729945bbf4e7127066be008fe5056 by …
> pull,load: use `*Image` instead of re-resolving via `name`

- libimage/image.go
> image: look for mountpoint in mapped layers too

- .github/workflows/validate.yml
- .golangci-extra.yml
Commit 84128ce8 ("CI: enable extra linters for new code", PR #1040) introduced the feature of running some extra linters for any newly added code (see the commit description for motivation).
Alas, commit 13bf5e99 ("use runc cgroup creation logic", PR #936) broke the feature, because it contains:
mv .golangci-extra.yml golangci.yml
(Note the missing dot in the destination file name.)
As a result, golangci-lint was running twice with the same config.
Let's fix it by using args: action parameter.
Also, some time later, a new golangci-lint removed support for deadline
option, and commit fbedd992 ("update golangci.yml", PR #2152) fixed it
for the main config. Let's do the same for the extra config.
> ci: fix running extra linters

- libimage/copier.go
ImageReference is an interface and we generally have no idea about the underlying layout here and if that can be printed as string. In case of the docker transport we get:
`{{{docker.io library/busybox} latest} %!s(bool=false)}`
That is clearly wrong and confusing, instead use transports.ImageName() which is the recommended way to refer to images in the UI.
> libimage: fix one copyToStorage error message

- .github/workflows/validate.yml
- .golangci-extra.yml
- .golangci.yml
- libimage/image.go
- libimage/load.go
- libimage/normalize.go
- libimage/search.go
- libnetwork/cni/network.go
- libnetwork/internal/util/bridge.go
- libnetwork/internal/util/create.go
- libnetwork/netavark/config.go
- libnetwork/netavark/network.go
- libnetwork/slirp4netns/slirp4netns.go
- libnetwork/types/define.go
- pkg/auth/auth.go
- pkg/cgroups/utils_linux.go
- pkg/configmaps/configmaps.go
- pkg/parse/parse_unix.go
- pkg/retry/retry.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
- pkg/subscriptions/subscriptions.go
- pkg/timetype/timestamp.go
- pkg/timezone/timezone.go
This can be logically split into 3 parts:
1. Configuration cleanup (first 2 commits)
* .golangci.yml: switch to list of enabled linters
Instead of enabling all linters, and when disabling some of them because
we don't like them, switch to list of explicitly enabled linters. The
upside of this is we can easily upgrade golangci-lint (i.e. any new
linters won't break our CI). The downside is, we need to explicitly
enable extra linters.
To me, this is better from the maintainability perspective.
NOTE this commit does not change the configuration in any way, in other
words, the list of linters being run is the same as before. The next
commit will address this.
PS this is my second attempt of doing this. The first one was in
commit 3bb7e636 ("Bump golangci-lint to 1.45.2", PR #997),
which was …
> Switch to golangci-lint v2, cleanup config, fix new linter warnings

- docs/containers.conf.5.md
* Document that variables can be listed without a value. Experimentally, this worked for me, and it's documented in podman's `--env`. I'm guessing supporting this in containers.conf too was intentional?
* Document that this config setting is ignored by `podman exec`, see https://github.com/containers/podman/issues/25685
Fixes: https://github.com/containers/podman/issues/25685
> Clarify the documentation of containers.env

- CONTRIBUTING.md
- CONTRIBUTING_GO.md
- CONTRIBUTING_RUST.md
This now includes separate files for Go and Rust, plus a central file with generic information that applies to all contributions. This will let us get Netavark and Aardvark onboarded onto the standard containers/common Contributing docs.
> Update CONTRIBUTING.md and split by language

- libimage/copier.go
After https://github.com/containers/common/pull/2339 there is no need for this argument so remove this.
Closes: https://github.com/containers/common/issues/2392
> libimage: remove unnecessary reportResolvedReference from `NewCopier`

- pkg/seccomp/default_linux.go
- pkg/seccomp/seccomp.json
Closes: https://github.com/containers/common/issues/2411
> seccomp: allow fanotify_init without CAP_SYS_ADMIN

- libimage/history.go
- libimage/image.go
- libimage/image_tree.go
- libimage/layer_tree.go
- libimage/manifests/manifests.go
- libimage/runtime.go
I saw a flake in parallel podman testing, podman images can fail if the manifest was removed at the right time. In general listing should never be able to fail when another image or manifest is removed in parallel.
Change the logic to convert to manifest and only collect the digests in the success case and ignore all other errors to make the listing more robust.
I observed the following error from podman images: Error: locating image "xxx" for loading instance list: locating image with ID "xxx": image not known
> libimage: fix manifest race during listing

- docs/containers.conf.5.md
Fixes: https://github.com/containers/podman/issues/25763
Avoid confusion with the `network` configuration using `podman machine`.
> Clarify configuration when using podman machine
